### ISSUE TITLE
503 Service Unavailable: Back-end server is at capacity

### ISSUE THREAD

**Issue by developerinlondon** [deis/deis#1255]
```
$ deis login http://deis.stats-production.cronycle.net
username: nayeem
password: 
503 Service Unavailable: Back-end server is at capacity
```

nothing in the deis-controller log tho?

**Comment by kingkevin** [comment]
@carmstrong running into this issue when running stress tests. I'm not quite sure what this error means or what to do for debugging

**Comment by carmstrong** [comment]
@kingkevin Not sure, honestly. Are you seeing the error from applications or on controller requests? I'd try to get a snapshot of the router's nginx config when you're seeing this, as well as the status of upstream services.

**Comment by carmstrong** [comment]
I would also suspect that maybe we've hit the maximum concurrent questions to controller? If you're doing stress testing, maybe there are connections that haven't timed out and closed yet.

**Comment by kingkevin** [comment]
Both the controller and the router became unresponsive. The issue cleared up after several minutes, and it first showed up after we turned up the log level.

**Comment by carmstrong** [comment]
> it first showed up after we turned up the log level.

Any logs you can provide would be helpful. This may just be a tuning/configuration change.

**Comment by Grindizer** [comment]
Hello everyone, 

I have been having the same issue quite a lot, on one of our cluster. 
At the same time I have seen a lof of those message on the controller

```
Feb 14 22:50:30 ip-10-0-117-69.ec2.internal sh[8519]: 2016-02-14T22:50:30Z 7e211248b0ce confd[128]: ERROR template: confd_settings.py:30:58: executing "confd_settings.py" at <getv "/deis/registry...>: error calling getv: key does not exist
Feb 14 22:50:35 ip-10-0-117-69.ec2.internal sh[8519]: 2016-02-14T22:50:35Z 7e211248b0ce confd[128]: ERROR template: confd_settings.py:30:58: executing "confd_settings.py" at <getv "/deis/registry...>: error calling getv: key does not exist
Feb 14 22:50:40 ip-10-0-117-69.ec2.internal sh[8519]: 2016-02-14T22:50:40Z 7e211248b0ce confd[128]: ERROR template: confd_settings.py:30:58: executing "confd_settings.py" at <getv "/deis/registry...>: error calling getv: key does not exist
Feb 14 22:50:45 ip-10-0-117-69.ec2.internal sh[8519]: 2016-02-14T22:50:45Z 7e211248b0ce confd[128]: ERROR template: confd_settings.py:30:58: executing "confd_settings.py" at <getv "/deis/registry...>: error calling getv: key does not exist
Feb 14 22:51:25 ip-10-0-117-69.ec2.internal sh[8519]: 2016-02-14T22:51:25Z 7e211248b0ce confd[128]: ERROR template: confd_settings.py:30:58: executing "confd_settings.py" at <getv "/deis/registry...>: error calling getv: key does not exist
```

I checked in the template and the missing value is /deis/registry/host which is weird sine it is running and when I check the value it exists. 

Though I noticed the way the registry publishes his host name through
```
while [[ ! -z $(netstat -lnt | awk "\$6 == \"LISTEN\" && \$4 ~ \".$PORT\" && \$1 ~ \"$PROTO.?\"") ]] ; do
		if etcdctl --no-sync -C "$ETCD" mk "${ETCD_PATH}/masterLock" "$HOSTNAME" --ttl "$ETCD_TTL" >/dev/null 2>&1 \
		|| [[ $(etcdctl --no-sync -C "$ETCD" get "${ETCD_PATH}/masterLock") == "$HOSTNAME" ]] ; then
			etcdctl --no-sync -C "$ETCD" set "$ETCD_PATH/host" "$HOST" --ttl "$ETCD_TTL" >/dev/null
			etcdctl --no-sync -C "$ETCD" set "$ETCD_PATH/port" "$EXTERNAL_PORT" --ttl "$ETCD_TTL" >/dev/null
			etcdctl --no-sync -C "$ETCD" update "${ETCD_PATH}/masterLock" "$HOSTNAME" --ttl "$ETCD_TTL" >/dev/null
		fi
		etcdctl --no-sync -C "$ETCD" set "$HOST_ETCD_PATH/host" "$HOST" --ttl "$ETCD_TTL" >/dev/null
		etcdctl --no-sync -C "$ETCD" set "$HOST_ETCD_PATH/port" "$EXTERNAL_PORT" --ttl "$ETCD_TTL" >/dev/null

		sleep $((ETCD_TTL/2)) # sleep for half the TTL
	done

```

I am wondering could it be possible that the ttl for /deis/registry/host expires before the registry re write it. So during a small laps of time the value is not set, this cause the controller to fail writing the confd_settings, 
which in its turn would cause the controller to become unavailable for a very short time (but repeatedly) ?

Also I noticed when I scaled the registry to 2 (deisctl scale registry=2) I stopped having the logs in the controller shown above, I supposed since the value /deis/registry/host is updated more often with both registry, controller does not complain about that anymore. 

To be honest, I find it a bit hard to debug this problem, so I am suuming a lot of things here, but do you thing this scenario is possible ?

Thank you in advance.
