### ISSUE TITLE
Evaluate running a LRU cache for the docker-registry

### ISSUE THREAD

**Issue by johanneswuerbach** [deis/deis#1794]
According to @dmp42 https://github.com/docker/docker-registry/pull/560#issuecomment-54878095 using a small LRU cache (lets say ~50MB) could speed up the developer experience when running the deis registry with S3 significantly or a bit when running it using the default local storage. This would also resolve the warning in #1780.

What do you think?

**Comment by bacongobbler** [comment]
FWIW we still want this in master -- it just cause too many issues with `deis pull` as seen in #3218. A further investigation is required.

Re-opening for discussion/findings with re-enabling the cache.

**Comment by dmp42** [comment]
@bacongobbler OT and out of curiosity: are you guys investigating/testing the new golang registry?

**Comment by bacongobbler** [comment]
sorry @dmp42; haven't had time yet to test. It's on my TODO list! :)

**Comment by mboersma** [comment]
@dmp42 I've done work on Docker registry V2 in Deis. It's effectively blocked since Deis can't move beyond Docker 1.5.0 right now, but we intend to move forward as soon as there is a clear path.

Recently there has been some clear sentiment in engineering and from our BDFL toward removing the deis-cache component completely, to simplify. Registry V2 still *could* use it if that were desirable. And strictly speaking that would be a backward-incompatible change. Just noting that for public record.

**Comment by mboersma** [comment]
deis-cache was removed with #4486.
