### ISSUE TITLE
Application SSL support

### ISSUE THREAD

**Issue by gabrtv** [deis/deis#18]
The controller currently supports HTTP and HTTPS cluster-wide by installing an SSL cert on the load balancer fronting Deis.  We need to provide a way of distributing SSL keys to the router for applications.

**Comment by jparkerCAA** [comment]
Sorry, I've been off the grid for a long stretch.
@nathansamson let me explain my approach to some of these points.
 
- Wildcard certificates can be used by multiple applications
  perhaps I am oversimplifying but I figured that for the splat cert use case one would simply add the    same cert to each app that requires it. Perhaps I'm oversimplifying this but this actually happens to match my use case (the reason I'm adding this feature) and I'm ok with it. (at least as a first step towards some more sophisticated solution)

- mulit-domain same as above

- not every domain will have a cert. My assumption (perhaps a foolish one) was that a mult-domain ssl app would employ a single multi-domain certificate. I have not tested this like I have tested the wildcard but seems like it should work. Can you describe the scenario where one domain is secure and another is not for a single app? I suppose it shouldn't be too difficult to attach the cert to an app domain but I'd prefer to keep it as simple as possible.

**Comment by jparkerCAA** [comment]
@nathansamson ah, I see your use case on the other issue

**Comment by nathansamson** [comment]
* Wildcard certificates can be used by multiple applications.
* Multidomain. 
 Yes I agree in both cases, it should just be added by the different applications for their respective domains.
I just believe it is worth nothing in combination with the other requirements (mostly that not applications should be linked to certs, but rather domains)

I think the main thing that needs to change from your existing implementation in #2799 (although I didn't take an exact look) is to change the nginx configuration.
So rather than just adding all domains in one server block add them one by one... But I think this might get rather complicated in the case of multidomain & wildcard certificates.
Also it needs to be taken into account that some domains of an app won't have the certificate so should still listen on HTTP port 80 without redirect to HTTPs

Nathan

**Comment by bacongobbler** [comment]
I've created an initial proposal at #2911 which follows https://devcenter.heroku.com/articles/ssl-endpoint. I'd really appreciate your input there!
