### ISSUE TITLE
config:set --global for common variables

### ISSUE THREAD

**Issue by boffbowsh** [deis/deis#1804]
It'd be extremely useful for a Deis deployment of common applications to have the concept of cluster-wide environment variables, for example a REDIS_URL if all apps hit a common Redis server, or perhaps some email service credentials.

Regarding the action that would take place when these get updated, I think it would be best to allow the operators to re-release and thus restart apps at their own pace.

**Comment by carmstrong** [comment]
Renamed issue to config:set --global, as dropping the notion of clusters would have made this command confusing.

**Comment by sforsman** [comment]
This feature would definitely be useful in our use cases as well. It would simplify management and deployment of our applications.

**Comment by mboersma** [comment]
A workaround for now is something like `deis create && deis config:set -p ~/.env`.

**Comment by jwaldrip** [comment]
Pulled this from another request I had:

## As a developer I would like to set ENV variables across my organization, so that I don't have to configure it for each application

### Example Use Case:
```
deis config:set --all NEW_RELIC_LICENSE_KEY=abc123
```

### Acceptance Criteria:
* New builds will reflect the ENV variable.
* New applications will reflect the ENV variable.
* ENV variable can be overridden if set at the application level.

### Nice to haves:
Aliasing. It would be great if I could set `SOME_VAR=$OTHER_VAR`. This would allow me to do `NEW_RELIC_APP_NAME=$DEIS_APP`.

**Comment by deis-admin** [comment]
This issue was moved to deis/controller#1219
