### ISSUE TITLE
git push: insufficient permission for adding an object to repository database

### ISSUE THREAD

**Issue by vincentpaca** [deis/deis#1843]
This just happened out of nowhere. I was able to push to my deis master just fine until this happened.

```
> git push deis master                                                                                                                                                                            
Counting objects: 9, done.                                                                                                                                                                        
Delta compression using up to 4 threads.
Compressing objects: 100% (5/5), done.
Writing objects: 100% (5/5), 477 bytes | 0 bytes/s, done.
Total 5 (delta 3), reused 0 (delta 0)
error: insufficient permission for adding an object to repository database ./objects

fatal: failed to write object
error: unpack failed: unpack-objects abnormal exit
To ssh://git@deis.staging.asia.gce.redacted.com:2222/redacted-website.git
 ! [remote rejected] master -> master (n/a (unpacker error))
error: failed to push some refs to 'ssh://git@deis.staging.asia.gce.redacted.com:2222/redacted-website.git'
```

Edit:
Permissions log: http://pastebin.com/zjsER1e8

Edit 2:
For anyone else that is experiencing this issue, the fix was we deleted the repository from the builder. It works but it's not ideal.

**Comment by Blystad** [comment]
Today I encountered this for the second time. First time I just restarted the builder and that solved it, but this time I wanted to get to the bottom of things. Together with the deis maintainers, we were able to find the root cause of the issue, and I have a pull request on the way to solve it.

What happened was that some folders and files were suddenly owned by root:
```
drwxrwxr-x 1 git  git  132 2015-01-07 17:55:42.795319423 +0000 .
drwxrwxr-x 1 git  git  140 2015-01-07 17:29:50.211447886 +0000 ..
drwxr-xr-x 1 root root  76 2015-01-07 17:29:49.036462354 +0000 16
drwxrwxr-x 1 git  git   76 2015-01-07 17:23:04.257444444 +0000 17
drwxrwxr-x 1 git  git   76 2015-01-07 17:23:04.245444592 +0000 25
drwxr-xr-x 1 root root  76 2015-01-07 17:29:49.037462342 +0000 33
```

This caused a permission error.

The reason why it happened was due to executing `git gc` as root:
https://github.com/deis/deis/blob/18cf1a99d333bde630f1bd3bad8029752d1799a9/builder/image/templates/builder#L179?

The [builder script](https://github.com/deis/deis/blob/18cf1a99d333bde630f1bd3bad8029752d1799a9/builder/image/templates/builder) was [executed as root](https://github.com/deis/deis/blob/18cf1a99d333bde630f1bd3bad8029752d1799a9/builder/image/templates/gitreceive#L56-L57) because Deis needed root permissions to execute docker commands. Root permissions is not necessary if we add the `git` user to the `docker` group (See: [Giving non-root access](https://docs.docker.com/installation/ubuntulinux/#giving-non-root-access)).

Pull request is on the way!

**Comment by jorihardman** [comment]
:+1: Awesome! Would love to have this squeezed into 1.2 if possible.

**Comment by bacongobbler** [comment]
too late to get a fix into 1.2 unfortunately. We're just kinking out the last few bugs before we ship it.

**Comment by Blystad** [comment]
I've managed to remove the `root`/`sudo` requirement from most of the builder. However, one piece is still remaining, and that's these lines of code: https://github.com/deis/deis/blob/18cf1a99d333bde630f1bd3bad8029752d1799a9/builder/image/templates/builder#L101-L105

We cannot run `chown -R 2000:2000` unless we're root, since we would be giving away the file to another user, which is forbidden - https://superuser.com/questions/697608/chown-operation-not-permitted

I solved this other places by adding the `git` user to the `slug` group, and then do something like this:
```
    # give slug group ownership of TMP_DIR and CACHE_DIR. This is used by the
    # slug builder. Contents in these folders will be owned by slug:slug.
    chown -R :2000 $TMP_DIR $CACHE_DIR
    chmod g+rwx $TMP_DIR
    chmod g+rwx $CACHE_DIR
```

(which works). However, that only works since I know that TMP_DIR and CACHE_DIR will be created as `git:git` and I can then move it to `git:slug`. `/buildpacks` could be owned by root or some random uid/gid, and then I'm out of luck.

I can add `chown -R 2000:2000 /buildpacks` as the single root command allowed to execute for `git` as `sudo`, but I'm wondering if anyone has any better alternatives?

**Comment by bacongobbler** [comment]
The reason for that chown is because docker volumes are always created with a uid/gid of 0, and deis/slugbuilder runs as a non-priveleged user. Some buildpacks unpack archives into its own filesystem so it's essential that the slugbuilder user gets r/w access to that layer. More info at #1972

**Comment by Blystad** [comment]
Alright. I'll use `sudo` on that one `chown` command then.

**Comment by joaoluiznaufel** [comment]
write permission at .git folder inside your project.

**Comment by shaktik** [comment]
cd /home/git/myrepo.git/objects
chown -R "git:git" ./

**Comment by angeldelacruzs** [comment]
mamaguevo
