### ISSUE TITLE
App not started error on test-integration

### ISSUE THREAD

**Issue by gabrtv** [deis/deis#2287]
We are seeing intermittent errors on Jenkins test runs that result in the following output:

```console
    itutils.go:118: App not started (200)
FAIL
exit status 1
FAIL    github.com/deis/deis/tests  296.549s
make[1]: *** [test-full] Error 1
make[1]: Leaving directory `/home/jenkins/workspace/test-integration/src/github.com/deis/deis/tests'
make: *** [test-integration] Error 2
```

This seems to be correlated with a `start-pre` or `auto-restarting` unit subState as printed by the `fleetctl list-units` during log dumps.  I suspect the root cause is Fleet's UnitState() endpoint returning inconsistent results.  However, it requires more in-depth debugging.

**Comment by bacongobbler** [comment]
this doesn't seem like an issue any more, correct? Haven't seen this bug in a while unless it's a PR that breaks scheduling logic.

**Comment by gabrtv** [comment]
@mboersma are we still seeing this particular test failure on the ec2 runs?

**Comment by mboersma** [comment]
We are seeing something superficially similar, but no unit in the "dead/dead" state. That is, we still wrestle with units that don't appear to have been started by fleet, but on investigation there's no unit created at all. I'm going to close this since I don't think it describes accurately the current CI issues we're working on, but I'll open new ones when we have those better categorized.

**Comment by bacongobbler** [comment]
> we still wrestle with units that don't appear to have been started by fleet, but on investigation there's no unit created at all.

I think that accurately describes `fleetctl load`, which is essentially the equivalent API call we're making in the scheduler :) https://github.com/coreos/fleet/blob/master/Documentation/using-the-client.md#scheduling-units
