### ISSUE TITLE
Installation on bare metal stalls after loading the router

### ISSUE THREAD

**Issue by remohammadi** [deis/deis#2469]
Here is the output:

```
core@pasha /var/lib/deis $ deisctl install platform
● ▴ ■
■ ● ▴ Installing Deis...
▴ ■ ●

Storage subsystem...
deis-store-metadata.service: loaded
deis-store-gateway.service: loaded
deis-store-monitor.service: loaded
deis-store-volume.service: loaded
deis-store-daemon.service: loaded
Logging subsystem...
deis-logger.service: loaded
deis-logspout.service: loaded
Control plane...
deis-cache.service: loaded
deis-controller.service: loaded
deis-registry.service: loaded
deis-database.service: loaded
deis-builder.service: loaded
Data plane...
deis-publisher.service: loaded
Routing mesh...
deis-router@1.service: loaded
```

I waited for more than 20 minutes but nothing happened. Is there something like `--verbose` for the installation command?

**Comment by josh-padnick** [comment]
Just in case my solution helps anyone else...

I found this thread because my `deisctl install platform` also stalled on:

```
Routing mesh...
deis-router@1.service: loaded
```

My problem was also that I didn't have a functioning CoreOS cluster.  And that, in turn, was because I had set the `AssociatePublicIpAddress` property of the `CoreOSServerLaunchConfig` in the AWS CloudFormation template to `false`.  

When this is false, the individual EC2 instances can't access public websites, which means they can't communicate with https://discovery.etcd.io, which means that they can't join a cluster.  Anyway, setting this to true seems to have fixed my issue.
