### ISSUE TITLE
`deis push`: push to Deis from local Docker graph

### ISSUE THREAD

**Issue by renegare** [deis/deis#2680]
```
In order to deploy a privately built image to deis cluster
As a developer
I would like to execute the following commands to push and deploy a local image

`deis push <local_image_name>:<tag>`
`deis deploy <local_image_name>:<tag>` # not to be confused with `deis pull`
```

Currently as of `deis v1.0.2` all of this is possible, but through the [not so elegant] steps:

```
docker build -t <app_name>... # build your image locally
docker tag <app_name>:latest 127.0.0.1:5000/<app_name>:`git rev-parse --short HEAD` # tag your app locally
ssh -Nf -L 5000:127.0.0.1:5000 core@$REGISTRY_HOST # port-forward the deis-registry port (make sure also your docker daemon allows this insecure registry)
docker push 127.0.0.1:5000/<app_name>
killall ssh # not elegant
deis pull <core-host-docker-registry-service-ip>:5000/<app_name>:<tag> # actually deploy your image
```

This clearly not elegant (I have it running on a CI #ignant) and a few too many moving parts.

I'm hoping for a discussion around this, I am still oblivious to any related concerns around the possibility of this feature.

**Comment by carmstrong** [comment]
This feature is on our open roadmap: http://docs.deis.io/en/latest/roadmap/roadmap/

**Comment by renegare** [comment]
Nice one guys. Been AWOL, but great to see this.

**Comment by bacongobbler** [comment]
So to think about this feature, there are a few things I can think of. If this is good, then I'll move to a more formal proposal:

 - break out the authentication API in the controller as its own microservice. It should be pluggable, having the ability to communicate to other auth servers (like LDAP). This'll most likely be pulling out the existing auth service built into the controller and re-implementing it as a standalone service
 - update reference docs, API docs, architecture diagrams etc. to reference this new service
 - lock down auth access through registry v2's [pluggable auth system](https://github.com/docker/distribution/issues/535) by communicating to this new auth microservice. This means we're blocked until we close #3814, since the v1 registry has no pluggable auth service
 - provide a client workflow that wraps `docker push` with the auth server + a call to the controller to create a new build
 - deprecate `deis pull` with this new workflow. This might be just a big fat warning in the client before we remove those endpoints in a future release.

Does that seem reasonable to everyone? :)

**Comment by aledbf** [comment]
@bacongobbler please do not remove `deis pull`. I use a remote registry to deploy to production, not something from a loca docker graph

**Comment by bacongobbler** [comment]
I guess there's no true need to remove it. The motivation to remove `deis pull` is that it's a giant hack to pull in an image, with intimate logic around the v1 image layer format. It doesn't work with v1.6+ images at all and we cannot support it with the v2 registry unless we re-implemented the crazily slow "pull, push, pull" workflow with a docker engine, so we'd need to do that in tandem with #3814.

cc'ing @mboersma for visibility

**Comment by alexanderkiel** [comment]
I really like the idea from @renegare of a simple `deis deploy <image>` and I like to extend it to remove the need of a `deis push` before it. The deis client could handle the retrieval of local or remote images and just deploy it through one single API. There is no need that the deis servers pull images from somewhere or that I have to push images into the deis registry before I can deploy them. All I want to do is: create an app, deploy an image and config it.

**Comment by deis-admin** [comment]
This issue was moved to deis/workflow#709
