### ISSUE TITLE
Additional checks for go code

### ISSUE THREAD

**Issue by aledbf** [deis/deis#2827]
I found this script https://gist.github.com/hailiang/0f22736320abe6be71ce that could complement the existing checks in go:

1. [gofmt](http://golang.org/cmd/gofmt/)
2. [goimports](https://github.com/bradfitz/goimports)
3. [golint](https://github.com/golang/lint)
4. [go vet](http://golang.org/cmd/vet)
5. [race detector](http://blog.golang.org/race-detector)
6. [test coverage] (http://blog.golang.org/cover)

**Comment by bacongobbler** [comment]
`goimports` seems like a convenience tool for fixing import names so that may not be necessary. We're trying to stick to standard tools/libraries unless we absolutely need to rely on others (one less dependency is always nice, IMO).

We could certainly use the checks for golint, go vet, coverage and the race detector. I think `go test -covermode=count -coverprofile=profile.tmp ./...` should cover all of https://gist.github.com/hailiang/0f22736320abe6be71ce#file-goclean-sh-L24-L34 though.

**Comment by mboersma** [comment]
I use `goimports` instead of `gofmt` in my editor's on-save trigger, but I don't think it's necessary to include in code checking, just `gofmt`. It primarily allows me to be lazy about typing proper imports. The others would be very helpful.

**Comment by carmstrong** [comment]
refs #2412
