### ISSUE TITLE
Docker image pull hangs if latest tag does not exist

### ISSUE THREAD

**Issue by glogiotatidis** [deis/deis#2830]
Steps to reproduce:
 - deis create foo
 - deis pull giorgos/masterfirefoxos

waits forever while it should return saying that no 'latest' tag exists and that user should define a tag to pull.

**Comment by bacongobbler** [comment]
nice catch. this is odd behaviour because it'll still pull the image and think everything is all fine and dandy until it's actually deployed. There are two ways we could fix this:

1. discover that the image does not have a 'latest' tag after pulling it down and error out before it gets to the scheduler
2. force `deis pull` to be explicit about tag `latest`

The former seems like the better solution here, IMO.

**Comment by glogiotatidis** [comment]
I like the second solution as well. If user does not define a tag to pull `deis pull` defaults to `latest`. 

I want to try to fix this if you think it's a good candidate for contributors. Is this part of the django controller? Any pointers / tips?

**Comment by bacongobbler** [comment]
Inside the controller is a registry module for communicating with a registry. controller/registry is the path, I believe. The pull logic is somewhere in controller/api/models.py

**Comment by bacongobbler** [comment]
After talking internally, we want to tackle this by being explicit about the tag in the client, which means that we'd drop support for an implied tag. In other words:

```
GOOD deis pull foo:latest
GOOD deis pull foo:someothertag
BAD deis pull foo
```

If you want to take a look into implementing this, that would be greatly appreciated!

**Comment by glogiotatidis** [comment]
Cool. I'll try to tackle this on Friday.

**Comment by glogiotatidis** [comment]
Obviously I didn't tackle this "on Friday". I don't have time to work on this atm so if anyone else is interested before I find time, feel free to take it :)
