### ISSUE TITLE
git push is rejected after upgrading builder

### ISSUE THREAD

**Issue by ngpestelos** [deis/deis#2876]
We just upgraded deis-builder and we started to see a lot of these errors:

    ! [remote rejected] master -> master (pre-receive hook declined)
      error: failed to push some refs to 'ssh://git@....git'

**Comment by carmstrong** [comment]
@ngpestelos Is it possible your local ssh-agent is no longer offering the key you use for Deis? That error almost always means an auth issue.

Also, what version of Deis did you upgrade to? There's a known bug related to config variables that are integers and not strings (so things like ports that are set in your application), but that was fixed in v1.1.1: https://github.com/deis/deis/commit/962a1814c6aed02ce8c1166126e244918efb10ad

**Comment by ngpestelos** [comment]
@carmstrong Thank you, we'll take a closer look. We're building off the `master` branch.

When we restarted `deis-builder`, the problem went away.

**Comment by carmstrong** [comment]
> When we restarted deis-builder, the problem went away.

Good to know. Maybe it just needed a poke to write out your auth keys from etcd.
