### ISSUE TITLE
store: Automatically remove nodes from Ceph on autoscale or IP change

### ISSUE THREAD

**Issue by carmstrong** [deis/deis#2877]
Ceph expects nodes to have constant IP addresses. When nodes are added to the cluster, there's no problem - the Ceph services start and join the cluster. When nodes are removed (such as on an auto-descale), however, Ceph sees the host as down. This potentially becomes a problem once there are a lot of dead nodes that haven't been properly removed from Ceph, potentially resulting in Ceph not having enough healthy monitors to achieve a cluster quorum.

Additionally, when AWS relocates an instance to a new host machine, its IP is likely to change. When the store containers come up on the new IP address, they see themselves as new and Ceph creates new host entries. The old IP address becomes a stale entry in Ceph which will never come up again.

Removing entries from the cluster is done quite easily by following the [Adding/Removing Hosts](http://docs.deis.io/en/latest/managing_deis/add_remove_host/). However, this process is manual, and oftentimes I imagine users are unaware that their nodes are autoscaling or being relocated. We should try to find a way to detect these changes and automatically remove old nodes from the cluster.

**Comment by Blystad** [comment]
+1 on this. I encountered this when one of my nodes failed AWS health checks (of course the "most important" node).

deis/database wouldn't start because of "corrupt" database copies. deis/controller wouldn't start because of missing deis/database, and so on so forth. By manually removing the "dead" node, Ceph was able to recover and then deis/database would get up and running.

**Comment by ianblenke** [comment]
This has happened to me multiple times now. All it takes is one run-away app allocating RAM to one-by-one decimate your deis cluster as the ASG merrily replaces deis nodes, driving ceph into a pit of self loathing.

**Comment by mgartner** [comment]
+1

My AWS autoscaling group restart a node it thought was unhealthy, taking down one of my applications and leaving my Deis cluster in an unstable state. Most deis commands were hanging and ultimately led to some significant downtime in production. #2914

**Comment by carmstrong** [comment]
Since Amazon attempts to shutdown the machine cleanly, I'm thinking a reasonable approach to this would be to hook into systemd/CoreOS to run a custom script at system termination.

**Comment by Blystad** [comment]
Wouldn't etcd TTL be a more solid/safe solution? If AWS health checks fail and the script isn't executed then we will still have the problem.

**Comment by carmstrong** [comment]
> Wouldn't etcd TTL be a more solid/safe solution?

It's not a matter of just removing it from etcd - we need to actually tell Ceph the nodes are leaving. Essentially, a script that performs: http://docs.deis.io/en/latest/managing_deis/add_remove_host/

I'm starting to think the only real solution to this is to write a service which keeps track of the cluster, and prevents it from losing quorum by removing hosts after they've been offline a certain amount of time and the cluster is in danger of having too many dead hosts. But that'd take some time to build and test.

**Comment by Blystad** [comment]
I know. I think a dedicated service for this makes the most sense and will be the best solution, but I agree it will take some time to build and test.

**Comment by aledbf** [comment]
@carmstrong why not use fleet metadata to limit the nodes that will run ceph as a first step? 
This can avoid the quorum problems.

**Comment by mgartner** [comment]
It's ubfortunate that Ceph isn't robust enough to handle node replacement on its own. I'm curious what the best practices are when using Ceph on a cluster that will be frequently auto-scaled. I hope not manual intervention each time...

**Comment by carmstrong** [comment]
> It's ubfortunate that Ceph isn't robust enough to handle node replacement on its own. I'm curious what the best practices are when using Ceph on a cluster that will be frequently auto-scaled. I hope not manual intervention each time...

I reached out to the Ceph mailing list for advice, but keep in mind that running a 3-node cluster is probably small potatoes for Ceph. The issue here isn't that we're adding and removing hosts - rather, it's that when losing one host we are in dangerous waters of not being able to form quorum. Ceph is usually used in clusters with dozens or hundreds of OSDs (or more!), so losing quorum isn't a common occurrence.

**Comment by ianblenke** [comment]
If etcd punts out a member due to a failed heartbeat, the data may still be there, and we wouldn't want to potentially lose that data - particularly in the case where _many_ nodes disappear entirely when an AWS Availability Zone becomes partitioned.

Remember the 'P' in CAP? That's really what we're talking about here.

It's one thing to lose etcd membership temporarily. Re-syncing the data from etcd is minor compared to gigabytes of data stored in ceph.

If AWS has TERMINATED an instance, there is no way to get the data back. At that point, we would want he auto-scaling group to send a notification to the deis cluster, which can be routed to something with the ability to prune the terminated instance from ceph to retain its quorum.

This is less to do with having the ceph-osds lay around and pile up than it is to do with the ceph-mon quorum being retained.

**Comment by carmstrong** [comment]
> This is less to do with having the ceph-osds lay around and pile up than it is to do with the ceph-mon quorum being retained.

Correct. Ceph actually automatically will `out` an OSD after it has been down for a certain amount of time, anyhow - see http://ceph.com/docs/master/rados/configuration/mon-osd-interaction/#configuration-settings for relevant settings we could tweak.

> If AWS has TERMINATED an instance, there is no way to get the data back. At that point, we would want he auto-scaling group to send a notification to the deis cluster, which can be routed to something with the ability to prune the terminated instance from ceph to retain its quorum.

Yep, although I'm not sure how to have AWS notify on a scale operation other than by sending an email, which is something that we couldn't easily manage within Deis. I agree that the issue here is how to detect *permanent* failure as opposed to a reboot, but I think the goal of a service like I'm proposing would be to only intervene when absolutely necessary to retain cluster quorum.

**Comment by Blystad** [comment]
> Yep, although I'm not sure how to have AWS notify on a scale operation other than by sending an email [...]

I havn't tested this, but I would guess creating a [SNS notification on autoscale change](http://docs.aws.amazon.com/AutoScaling/latest/DeveloperGuide/ASGettingNotifications.html) which is sent to a SQS queue that a Deis (environment specific) component polls?

**Comment by carmstrong** [comment]
> I havn't tested this, but I would guess creating a SNS notification on autoscale change which is sent to a SQS queue that a Deis (environment specific) component polls - should work?

Interesting - that should work well. We also want a solution which should ideally work transparently on all providers, though, without relying on vendor-specific features :(

**Comment by mgartner** [comment]
I just had my autoscaler replace another node. I've found that apps that were running on the replaced node fail to start up on other nodes in the cluster after an event like this. I had to manually restart the store-gateway to get them to work. Not really sure if this belongs in this thread but I thought I should mention it.

**Comment by carmstrong** [comment]
So our solution for this has turned into a separate project called mortician: https://github.com/deis/mortician

It's still in its infancy, but the idea is that it'll be a Go binary which talks to Amazon SNS/SQS to get autoscale notifications. It will support plugins to trigger when an autoscale event occurs.

**Comment by Mil0dV** [comment]
Has any progress been made on Mortician or another solution for this? The Mortician repo doesn't show any activity..

**Comment by ianblenke** [comment]
Given the quorum needs for etcd and ceph, and the growing number of other CAPish things that also need quorum (zookeeper, mesos-master, influxdb...), it seems best to break off a static control plane of 3-9 nodes that services these needs.

Any auto-scaling-group should be on fleet tagged application tiers with no quorum requirement, so that applications can be scaled dynamically to thousands of nodes if need be, and there can be less concern about retaining quorum.

This is something I'm working on here presently. CloudFormations can be nested with `AWS::CloudFormation::Stack`.

It would be ideal to have a top-level primary _VPC stack_ with subnet, ELB, and other related "glue" that all of the nested stacks must rely on.

Under that _VPC stack_, a _control stack_ would be a statically defined as a collection of `AWS::EC2::Instance` resources with `DisableApiTermination` set to `true`. These CoreOS instances would act as the etcd election leadership, as well as the ceph monitor quorum, and other other CAP quorum engines necessary for keeping a highly available replicated state.

Under that _control stack_ would be one or more fleet tagged _application stacks_. These stacks would be built on `AWS::AutoScaling::AutoScalingGroup` resources that have no inherent state and can grow and shrink without consequence.

Eventually, multiple other _service stacks_ could also be managed under the _VPC stack_ without directly impeding the function of the _control stack_.

This is the direction we are headed. I would love to contribute this back to the deis project, though I'm concerned that this is CloudFormation (AWS/Eucalyptus) centric - which may be importable to HEAT (OpenStack), but definitely isn't cloud agnostic like TerraForm.

**Comment by carmstrong** [comment]
@iancoffey's work in #3561 has introduced a node removal script which will be triggered on graceful shutdown once it's activated. This doesn't solve the case where the machines go unresponsive and are killed, but it'll be helpful in a lot of cases.

Additionally, @krancour's work in #3635 and in PRs around decoupling the control plane sounds up your alley, @ianblenke. Any feedback on #3679 or #3718?

**Comment by carmstrong** [comment]
This issue itself is resolved by #3561. A solution to handle failed instances may not be something that can live in Deis itself, and may be provider-specific.
