### ISSUE TITLE
AWS autoscaler terminated then restarted node - how to get cluster back to normal?

### ISSUE THREAD

**Issue by mgartner** [deis/deis#2914]
For some reason which I'm still trying to figure out, my AWS autoscaling group thought one of my nodes in my 3-node cluster was unhealthy, terminated it, then created a new node in its place. It's pretty vague on the reasoning behind terminating it. All it says is: `At 2015-01-17T21:35:37Z an instance was taken out of service in response to a EC2 instance status checks failure.`

As a result of the automated termination and restart, my ceph cluster and deis-store components seem to be in an unhealthy state. Also, it seems to have crashed one of my applications. The `deis-store-volume` container on the new host is stuck in `start-pre` mode on one of the machines in the cluster, but everything else looks fine according to `fleetctl list-units`.

```
deis-store-daemon.service	3e465ae1.../10.21.1.1	active		running
deis-store-daemon.service	46d81123.../10.21.2.2	active		running
deis-store-daemon.service	812989d1.../10.21.1.3	active		running
deis-store-gateway.service	3e465ae1.../10.21.1.1	active		running
deis-store-metadata.service	3e465ae1.../10.21.1.1	active		running
deis-store-metadata.service	46d81123.../10.21.2.2	active		running
deis-store-metadata.service	812989d1.../10.21.1.3	active		running
deis-store-monitor.service	3e465ae1.../10.21.1.1	active		running
deis-store-monitor.service	46d81123.../10.21.2.2	active		running
deis-store-monitor.service	812989d1.../10.21.1.3	active		running
deis-store-volume.service	3e465ae1.../10.21.1.1	active		running
deis-store-volume.service	46d81123.../10.21.2.2	active		running
deis-store-volume.service	812989d1.../10.21.1.3	activating	start-pre
```

However, when I check the status with `deisctl status deis-store-<component>` I get the message: `Unit deis-store-volume.service does not appear to be running.` for every store component except `deis-store-gateway` which appears healthy.

I tried getting the status of the ceph cluster with `ceph -s`, but it never returns the status, just shows ping-like ouput, then eventually times-out.

I stopped and unloaded the crashed application via `fleetctl`, but when I try to scale it back up with `deis ps:scale cmd=1` it just hangs. I'm assuming this is because of the deis store being corrupt. 

Another odd thing I thought I'd note - When running `df -h` on the two original nodes in the cluster, the command just hangs, while `df -l`. Both commands work fine on the newly spawned node. Not sure, but could this be related?

I'm using Deis v1.2.0.

First, what are the steps I need to take to get my cluster back into a healthy state? Second, is there anyway to find out more information about why my autoscaler thought that the node was healthy? How can I prevent this from happening in the future?

**Comment by Blystad** [comment]
I've seen this happen myself. In our case, one of the nodes ran out of memory and froze, which made EC2s health checks fail. The auto scaling group killed it, and a new instance took it's place. I also scaled the cluter up to 5 when that happened, just so it wouldn't happen again.

In our case, `deis-database` was running on the unhealthy node. When `deis-database` starts up, it attempts to recover it's previous state from `deis-store`. Very fair, but unfortionally `deis-store` ended up in a corrupt state where one of the database backups reported a size of 0 instead of <whatever it's supposed to be>. To fix it, I had to use `ceph` commands to remove the dead node. This caused `deis-store` to do some automatic recovery things and after about 5 minutes and some restarts of `deis-database` and `deis-controller` our cluster was up and running again.

I was able to get the ceph status using `ceph -s`. I'm a bit unsure why you couldn't get it. Did you try from multiple hosts?

If `deis scale` hangs thats most likely due to a dead `deis-controller`.

To avoid it in the future, well, eh...You need to have some server health monitoring running. Unfortionally, I have yet to find one solution which gives the best possible solution for CoreOS (since CoreOS is very Docker focused, and Docker isn't the easiest thing to monitor because of it's daemon process model). The best solution I've found so far is Datadog. Ensure that you always have memory available, even if one host goes down and all non-global units (e.g. your applications and most deis components) needs to be rescheduled to the remaining two servers.

**Comment by mgartner** [comment]
I've tried to follow the directions to remove a ceph node in the Dies documentation, but just about every ceph command gives me an endless stream of messages that look like:

```
2015-01-18 20:50:12.550405 7f2d54228700  0 -- :/1000170 >> 10.21.1.3:6789/0 pipe(0x7f2d50029890 sd=4 :0 s=1 pgs=0 cs=0 l=1 c=0x7f2d50029b20).fault
```

Except on one of the hosts, ceph commands seem to hang with no output.

**Comment by carmstrong** [comment]
> However, when I check the status with deisctl status deis-store-<component> I get the message: Unit deis-store-volume.service does not appear to be running. for every store component except deis-store-gateway which appears healthy.

That's to be expected - we really should add some better output for running `deisctl status` on global units. I filed #2917 to track this.

> Another odd thing I thought I'd note - When running df -h on the two original nodes in the cluster, the command just hangs, while df -l. Both commands work fine on the newly spawned node. Not sure, but could this be related?

That definitely points to a problem with Ceph - when getting the volume information for `/var/lib/ceph`, it's hanging because of an issue with the cluster.... although as long as *one* of your monitors is functioning properly, it should work just fine.

> I stopped and unloaded the crashed application via fleetctl, but when I try to scale it back up with deis ps:scale cmd=1 it just hangs. I'm assuming this is because of the deis store being corrupt.

Yep, as @Blystad said, the controller depends on the database which depends on store, so if the Ceph cluster is in a weird state, you'll have problems with controller.

> I tried getting the status of the ceph cluster with ceph -s, but it never returns the status, just shows ping-like ouput, then eventually times-out.

This is what bothers me - clusters should almost always be recoverable, but if you can't communicate with the cluster, there's nothing you can do. 

I've actually been thinking about this last issue. @mgartner, could you enter a **daemon** container and gist `cat /etc/ceph/ceph.conf`? I bet you won't see any of your new monitors there. If there are no monitors in that file that are active and running in your cluster, no `ceph` commands will work. 

You should be able to get these files to be re-templated by `deisctl restart store-daemon`, but we should investigate a way to re-template this these with the daemon running. This isn't possible with the way the /bin/boot scripts are currently authored (as we need to exec to replace the process with the monitor or daemon process), but perhaps #2701 gives us that opportunity.

**Comment by mgartner** [comment]
Ahh I had already run `deisctl restart store-daemon` in an attempt to fix things, but here is the output anyway: https://gist.github.com/mgartner/81899c87475750c1dc82

Two of the IP's listed under `mon host` are no longer part of the cluster (I found out the AWS terminated and started an intance in the cluster twice).

Even with the monitors listed there, `ceph -s` still doesn't work.

**Comment by mgartner** [comment]
Another oddity I thought I should note - the IP of the most recently created node is not listed in /deis/store/osds. `10.21.1.144` is missing. `10.21.1.169` and `10.21.2.172` are the nodes that were automatically terminated.

```
core@ip-10-21-2-116 ~ $ etcdctl ls /deis/store/osds/
/deis/store/osds/10.21.1.169
/deis/store/osds/10.21.2.172
/deis/store/osds/10.21.1.168
/deis/store/osds/10.21.2.116
```

**Comment by carmstrong** [comment]
@mgartner That output made me spot what I think is a bug with 690b3807763e40cc6f93d30763a5f532c8db4cd0 - your `mon host` listing should be hostnames, not IP addresses. I doubt that'd be the cause of your woes, but I'm whipping up a fix now. 

And that's certainly odd - as soon as an OSD comes up, it should publish itself. Does the output from that daemon reveal anything? 

You'll need to manually clean up the entries from the old monitors/osds following the Add/Remove Instructions. The components publish before they exec for the store process, so these etcd keys are not removed automatically. Try removing the monitors/OSDs from the healthy nodes. At the very least, remove the etcd keys for the dead mons/OSDs.

**Comment by carmstrong** [comment]
> I'm whipping up a fix now.

#2918

**Comment by mgartner** [comment]
@carmstrong definitely some problems with the new nodes store-daemon: https://gist.github.com/mgartner/435e9aef08907d798359

> Try removing the monitors/OSDs from the healthy nodes. At the very least, remove the etcd keys for the dead mons/OSDs.

How exactly should I do this? `ceph osd out 3` just hangs for me.

**Comment by carmstrong** [comment]
> How exactly should I do this? ceph osd out 3 just hangs for me.

As long as at least one of your mons enumerated in `/etc/ceph/ceph.conf` is up, `ceph` should connect. The client will try each of the monitors in turn. You can try reducing the connect timeout with `--connect-timeout` to something like 5 seconds.

**Comment by mgartner** [comment]
I still can't get ceph to connect. Editing `/etc/ceph/ceph.conf` didn't seem to help.

**Comment by carmstrong** [comment]
> I still can't get ceph to connect.

What does your ceph.conf look like now? Does it only list monitors that are up?

**Comment by mgartner** [comment]
I can manually take out the bad hosts in ceph.conf, but if I `deisctl restart store-monitor` they get added back in automatically. How can I manually update ceph.conf and restart the monitor without resetting the config?

Here's the output of `ceph --admin-daemaon /var/run/ceph/... mon_status`:

```
{ "name": "ip-10-21-2-116.us-west-2.compute.internal",
  "rank": 2,
  "state": "probing",
  "election_epoch": 0,
  "quorum": [],
  "outside_quorum": [
        "ip-10-21-2-116.us-west-2.compute.internal"],
  "extra_probe_peers": [],
  "sync_provider": [],
  "monmap": { "epoch": 4,
      "fsid": "30476296-e883-4dd3-9ce1-974b44757757",
      "modified": "2015-01-16 23:12:58.178080",
      "created": "2015-01-14 00:11:30.876248",
      "mons": [
            { "rank": 0,
              "name": "ip-10-21-1-168.us-west-2.compute.internal",
              "addr": "10.21.1.168:6789\/0"},
            { "rank": 1,
              "name": "ip-10-21-1-169.us-west-2.compute.internal",
              "addr": "10.21.1.169:6789\/0"},
            { "rank": 2,
              "name": "ip-10-21-2-116.us-west-2.compute.internal",
              "addr": "10.21.2.116:6789\/0"},
            { "rank": 3,
              "name": "ip-10-21-2-172.us-west-2.compute.internal",
              "addr": "10.21.2.172:6789\/0"}]}}
```

**Comment by carmstrong** [comment]
> I can manually take out the bad hosts in ceph.conf, but if I deisctl restart store-monitor they get added back in automatically. How can I manually update ceph.conf and restart the monitor without resetting the config?

The config is written from the keyspace /deis/store/hosts, so if those keys exist they will be written to the config.

**Comment by mgartner** [comment]
Hmm, still having trouble getting ceph monitors to connect. Looks like the monitors are stuck at "probing". Could it be an issue that the `initial members` in `ceph.conf` lists a host that no longer exists? Where is it getting that host from when I start the deis-store-monitor?

```
[global]
fsid = 30476296-e883-4dd3-9ce1-974b44757757
mon initial members = ip-10-21-1-169.us-west-2.compute.internal
mon host = 10.21.1.141, 10.21.2.116, 10.21.2.28
mon addr = 10.21.1.141:6789, 10.21.2.116:6789, 10.21.2.28:6789
auth cluster required = cephx
auth service required = cephx
auth client required = cephx
osd pool default size = 3
osd pool default min_size = 1
osd pool default pg_num = 128
osd pool default pgp_num = 128
osd recovery delay start = 15
log file = /dev/stdout

[client.radosgw.gateway]
host = deis-store-gateway
keyring = /etc/ceph/ceph.client.radosgw.keyring
rgw socket path = /var/run/ceph/ceph.radosgw.gateway.fastcgi.sock
```

**Comment by carmstrong** [comment]
> Could it be an issue that the initial members in ceph.conf lists a host that no longer exists?

That's only used if you're lost all of your monitors, and tells Ceph that if a monitor is coming up by itself (as when the cluster first initializes), that it's OK to form quorum with just that one monitor.

To recap - you only lost one node, which was then replaced, yes? I really don't understand how things got in this state with only one node being replaced. Ping me on IRC and I can try to help you resolve this interactively.

**Comment by mgartner** [comment]
It looks like a node was replaced twice, and it got into this state. Ceph seemed to have lost quorum and would hang on any commands. I've since manually terminated some unhealthy nodes where the deis-store-monitor wouldn't restart for whatever reason - but I've had no luck. `ceph -s` continues to hang.

**Comment by carmstrong** [comment]
I solved this interactively with @mgartner. We successfully recovered the cluster even though we only had one host with data. #2877 would have prevented this particular failure case, and I filed #2925 and #2926 for lessons learned from this recovery.
