### ISSUE TITLE
Add root domain to an application

### ISSUE THREAD

**Issue by mhahn** [deis/deis#3060]
I want to add a landing page to the root domain, lets say "example.com"

i ran:

```$ deis domains:add example.com```

I see "example.com" listed under the domains when running: `$ deis info`.

I also looked at the nginx config and see that the domain was added properly:

`server_name ~^application\.(?<domain>.+)$ example.com;`

hitting example.com doesn't seem to get to the router though (`deisctl journal router` doesn't display any hits).

is there another place that maybe blocking this?

**Comment by mhahn** [comment]
I also verified that: `$ deisctl config platform get domain` returns "example.com"

**Comment by carmstrong** [comment]
@mhahn Adding the root domain will only work if your DNS provider supports CNAMEs for the apex (root) domain - not all do. You'll still need to CNAME example.com to yourapp.deiscluster.tld

**Comment by mhahn** [comment]
i see, following these instructions helped.

adding the "www" record and running: `$ deis domains:add www.example.com` worked.

thanks!

**Comment by bacongobbler** [comment]
> adding the "www" record and running: $ deis domains:add www.example.com worked.

To clarify, that works because the documentation describes you to set up wildcard DNS to route over to the routers, so any *.example.com request will go to the routers. In the case with using the TLD, the DNS records aren't set up so you have to follow @carmstrong's comment on setting the correct records.

Glad we could help! :)
