### ISSUE TITLE
store: Consider switching to official ceph-docker images

### ISSUE THREAD

**Issue by carmstrong** [deis/deis#3198]
The Ceph team (with the great @ulexus, whose work our deis-store is based on) recently started publishing official Docker images for Ceph: https://github.com/ceph/ceph-docker

We should consider switching to them, as presumably they know more about Ceph than we do :)

Most interesting to me is the [config](https://github.com/ceph/ceph-docker/tree/master/config) container, which sets up the cluster and uses etcd(!) to manage cluster configuration.

**Comment by Ulexus** [comment]
@carmstrong Thanks for the kudos, but I've gotten a lot of great help since moving over to the official repo.  We'd be delighted to work with you.  We're still trying to figure out the "official" structure, too, so your input from the deis side of things would certainly be valuable.

I'm also quite happy to see `ceph/config` come in, but I'd caution that it was just merged in, and it's not really ready for use yet.  Help is always appreciated, though. ;)

**Comment by carmstrong** [comment]
This may not be something worth doing with the Go-based rewrites in #3758

**Comment by bacongobbler** [comment]
would this be worthwhile for the LTS release?

**Comment by carmstrong** [comment]
> would this be worthwhile for the LTS release?

Probably not worth the effort. Our logic works, and any attempts at rewrites would likely just introduce bugs. Closing.
