### ISSUE TITLE
Cannot start platform, if etcd uses SSL

### ISSUE THREAD

**Issue by sitya** [deis/deis#3201]
Due to the [Security considerations](http://docs.deis.io/en/latest/managing_deis/security_considerations/)  in our CoreOS cluster I configured etcd to [use SSL and client certificates](https://coreos.com/docs/distributed-configuration/etcd-security/), it works fine, but I cannot make deisctl to start platform.

`deisctl --etcd-cafile=/path/to/ca.pem --etcd-certfile=/path/to/cert.pem --etcd-keyfile=/path/to/key.pem --endpoint=https://1.2.3.4:4001 start platform`

Configuring, listing, installing worked, but starting did not.

I have checked logs and the Unit Files (eg: `deis-store-monitor.service`), and I think it hangs at `ExecStartPre=/bin/sh -c "etcdctl set /deis/store/hosts/$COREOS_PRIVATE_IPV4 `hostname` >/dev/null"` because `etcdctl` cannot access etcd, and I have no idea how to tell etcdctl to use client certificate. 

I would appreciate any idea, thanks.

**Comment by carmstrong** [comment]
I think you'd have to find any instance of `etcdctl` in any of our scripts and add the `ca-file`, `cert-file`, and `key-file` flags. Because many of our components use etcdctl inside their /bin/boot scripts, I'd think that you'd need to custom-build the components themselves and somehow pass through your cert and key, maybe bind-mounting the file in the container. 

Simply put, it's a large undertaking. Thinking off the top of my head, a reasonable approach would be to propose a PR that makes all uses of `etcdctl` use an environment variable called `$ETCD_OPTS` or something, which could be passed into the running container. So, for example, the publish loop in a component changes from:
```
until etcdctl --no-sync -C $ETCD ls >/dev/null 2>&1; do
```
to
```
until etcdctl $ETCD_OPTS --no-sync -C $ETCD ls >/dev/null 2>&1; do
```

It's fine if it's blank, but users could add additional options.

**Comment by sitya** [comment]
Thanks for the reply, I will think it over next week.

As I see, there are three parts of the task.
1. UnitFiles and Dockerfiles are supposed to use newer version of etcdctl which already knows the cert options (0.4.6 does not know these options).
2. Implement `$ETCD_OPTS` you advised
3. This is the most difficult to solve simply: the cacert, the cert and the key must be accessible by the containers. Bind-mounting, or generate certs in the Dockerfiles. I will examine the possibilities. If it works I will make a PR.

**Comment by carmstrong** [comment]
> This is the most difficult to solve simply: the cacert, the cert and the key must be accessible by the containers.

Agreed. I'm not sure how best to achieve this. Maybe we bind-mount `/etc/certs` or some path on the host into the container, but this starts to go down the route of specific functionality that most Deis users probably wouldn't use.

**Comment by sitya** [comment]
> 1. UnitFiles and Dockerfiles are supposed to use newer version of etcdctl which already knows the cert options (0.4.6 does not know these options).

I think using etcd version differs from the main version used by CoreOS hosts or by Deis containers cannot be maintainable, so a correct and useful PR could be proposed after upgrade of etcd at least v2.0 in the main entities. If this upgrade happens, I will make a PR. Do you think, if it happens in this spring?

> but this starts to go down the route of specific functionality that most Deis users probably wouldn't use.

I think, in production enviroment the access to the etcd must be restricted. Using client certificates may be easier than maintain iptables continuously.

**Comment by bacongobbler** [comment]
> Do you think, if it happens in this spring?

We have no idea when CoreOS will release etcd 2.0 into the main release channels.

> I think, in production enviroment the access to the etcd must be restricted

We already do that. etcd is currently binding to the private address space on boot such that users external to the cluster cannot access etcd through the node's public IP address, which is why @carmstrong thinks that most users probably wouldn't use this unless they were somehow exposing etcd to the world.

**Comment by ianblenke** [comment]
It also depends on how paranoid you are about your cloud provider's internal security. Case in point: Google now HTTPS encrypts traffic all the way through:

http://techcrunch.com/2014/03/20/gmail-traffic-between-google-servers-now-encrypted-to-thwart-nsa-snooping/

It really depends on how much you trust your cloud provider and the security of their network topologies.

**Comment by sitya** [comment]
I think it is not about the cloud provider's network topologies. For example: I run a wordpress container. WP has a security hole, the bot comes and uploads a php file with a system call inside: `etcdctl ls --recursive`. The container can reach the private network, so the attacker can read the whole etcd, can't he? Or do I misunderstand something?

**Comment by bacongobbler** [comment]
that loophole will get closed up via #986, but essentially yes, the container can reach the private network so long as the attacker knows of a way to get the container's host IP address.

**Comment by ianblenke** [comment]
Arguably, the attacker only needs to know 172.17.42.1

**Comment by wenzowski** [comment]
there is no such thing as a "private" network, unless you're talking about privately monitored networks. I monitor my own subnets but I don't monitor beyond that. Just because you monitor it, doesn't mean you can trust it. All your hosts can and will be compromised. Chat with etsy, they're much better at explaining ramifications of monitoring vs protection than I.

**Comment by ianblenke** [comment]
@wenzowski, the mention of 172.17.42.1 was with regard to the default docker0 interface IP address on all CoreOS hosts. Also, that etcd by default binds to INADDR_ANY (0.0.0.0) port 4001, and is reachable from that 172.17.0.0/16 network that is used by all docker containers on a CoreOS host. Meaning, after you've gotten a toehold into your docker container that is your app (via the HTTP traffic that is routed to it), you have carte blanche to 172.17.42.1:4001, which is where the OP of this issue comes into play: using SSL certs restricts access to the etcd instances over the network in addition to enabling encryption of the traffic between them.

**Comment by wenzowski** [comment]
Yep exactly @ianblenke thanks for spelling that out. All it takes is one toehold. My point is that even with #986 this will still be a concern. Given this, encrypting etcd traffic seems very important: we should all probably be doing what OP is.

**Comment by sitya** [comment]
I think there might be an easier (and maybe a better) option: #3572

**Comment by bacongobbler** [comment]
etcd will be going away in v2 and we won't be able to get to this for the LTS release so I'm going to close this, but thank you very much for posting this :)

**Comment by sitya** [comment]
It is fine, I am looking forward v2 ;)
