### ISSUE TITLE
Can I extract time-series data easily from the platform?

### ISSUE THREAD

**Issue by haf** [deis/deis#3228]
I'm trying to get up to speed on the deis platform, and was wondering if there are easy APIs that I can point in the direction of a "resource"/service -- Heka in this case -- which can then ship to another resource -- InfluxDB for saving and monitoring of time-series data? I'm at this point looking for docs on how to instrument the deployed containers, or even better, use their internal metrics, so that I can react to adverse conditions when it's deployed.

I haven't been able to find that much docs on this; are there any around?

**Comment by ianblenke** [comment]
Haf, I have cloud-init units that I've used to implement cadvisor + influxdb:

https://github.com/ianblenke/coreos-vagrant-kitchen-sink/blob/master/cloud-init/influxdb.unit
https://github.com/ianblenke/coreos-vagrant-kitchen-sink/blob/master/cloud-init/influxdb.write_file
https://github.com/ianblenke/coreos-vagrant-kitchen-sink/blob/master/cloud-init/cadvisor.unit
https://github.com/ianblenke/coreos-vagrant-kitchen-sink/blob/master/cloud-init/cadvisor.write_file
https://github.com/ianblenke/coreos-vagrant-kitchen-sink/blob/master/cloud-init/heapster.unit
https://github.com/ianblenke/coreos-vagrant-kitchen-sink/blob/master/cloud-init/heapster.write_file

The problem I ran into was that influxdb is challenging to repair when anything happens to it. Manually curl'ing URLs for API calls to repair it is tedious. I've since given up on it for the moment in favor of NewRelic:

https://github.com/ianblenke/coreos-vagrant-kitchen-sink/blob/master/tested/newrelic.cloud-init

ElasticSearch, on the other hand, has been a very reliable replicated persistence layer for me:

https://github.com/ianblenke/coreos-vagrant-kitchen-sink/blob/master/tested/elasticsearch.cloud-init
https://github.com/ianblenke/coreos-vagrant-kitchen-sink/blob/master/tested/packetbeat.cloud-init

That gives me a very boundary.com like interface for watching network traffic.

**Comment by bacongobbler** [comment]
closing, as documentation exists for both use cases(#980 and #981):

http://docs.deis.io/en/latest/managing_deis/platform_logging/
http://docs.deis.io/en/latest/managing_deis/platform_monitoring/
