### ISSUE TITLE
How to interact with the storage layer?

### ISSUE THREAD

**Issue by haf** [deis/deis#3229]
I was wondering if there are any docs on how to let applications write data to the redundant storage layer of deis?

**Comment by azurewraith** [comment]
There aren't any docs, and I've found a lot of Dockerfiles that require redundant storage for persistence.

My temporary workaround is to deploy a Dockerfile manually via fleet on the control plane (the ones with deis-store-*) and creating custom directories in `/var/lib/deis/store` to be used as Docker volumes.  `/var/lib/deis/store` is the location where log files are written to, and it is a CephFS mount.  So, you'd be basically reusing that pathway into the redundant storage layer.  My initial experiments show writing content there on one host, eventually winds up on the other hosts...which is what I'd expect from Ceph.

Feel free to correct if I am mistaken...

**Comment by haf** [comment]
This seems to be how it should work out. I've also found that there are permission problems when using per-service users inside containers. The 'official' way is using [data containers](https://medium.com/@ramangupta/why-docker-data-containers-are-good-589b3c6c749e), so if we could get data containers' paths to be stored on the ceph mount point, we'd be good to go.

It seems that should be easy once https://github.com/docker/docker/pull/8484 comes in.

**Comment by haf** [comment]
Furthermore, there's the 'local data container' that should be used when you have a cluster which does its own replication; there should be a way to specify that the volume container belongs together with a docker container and create a 'NAME-data' volume container for each 'NAME' container and host.

**Comment by bacongobbler** [comment]
Right now we strongly recommend that you do not give access to your control plane from the application plane. If there is a security exploit in your application which grants filesystem access, they could simply write to the filesystem and kill off not just the application but the entire cluster (Ceph consumes every host's disk space). Because of security exploits like that, there are plans to segregate the control plane from the application plane so expect this connection (to ceph, etcd, fleet, etc.) to be cut off in the future: #986 

Because of the above reasons, we strongly recommend that [you use Amazon S3](https://devcenter.heroku.com/articles/s3) or some other external persistent filesystem layer for your application plane because our filesystem acts very similar to Heroku.

If you really want to access Ceph, this would be a great project to take a look at after #231 is implemented. Someone could create a Ceph Service Broker which would shave part of the Ceph cluster in a secure, safe and multi-tenant way for consumption by applications.

**Comment by haf** [comment]
Given enough disk, couldn't one chroot a container to a subfolder that deis' control plane doesn't touch? Like `/var/lib/deis/storage/apps/{app-name}`?

My use-case is writing immutable data - possibly millions of large files, which need to be available from all machines. Does Deis write a larger replication factor than floor(N/2+1)? (2 nodes for 3 deployed?) like is [described in the Pools page](http://ceph.com/docs/master/rados/operations/pools/) of the Ceph docs?

**Comment by ianblenke** [comment]
Given personal operational experience with cephfs on HVM instances as part of issue #2959, I don't think it is stable enough to consider using in a production capacity.

You may want to check with @mgartner, but I'm pretty sure he is running PV and is having a similar problem.

In our production environment with deis v1.0.1, we've hacked things up to resort to using S3 and avoiding ceph entirely to increase stability.

Again, YMMV, but know that operational experience is somewhat mixed with regard to the stability of ceph.

**Comment by ianblenke** [comment]
Issue @3030 is related, with regard to ceph stability and PV.

**Comment by azurewraith** [comment]
The way you have to set it up is special case and a path that isn't available to general users.  I'm only doing it for one thing I couldn't 12-factorize without significant effort.  I'll happily migrate to a supported path once it exists.

You can't deploy a good majority of service Dockerfiles because they require Docker volumes for persistence.  Buildpacks are fine because they generally are apps you've rolled yourself with S3 support or built for Heroku with intrinsic 12-factorization.  The HA present in the deis cluster is nice, but the app gets overwritten on config:set, deploy, limits:set, external forces, etc.  Deis realized this quickly and ditched(ish) container volumes and instead created the Ceph cluster to hold its end of the bargain (DB backups with wal-e, log storage via CephFS, etc.).  #231 is needed, but getting those services to survive in a HA way is half the battle and one not easily accomplished.

A Ceph Service Broker with a pathway to get that filespace into Docker containers would do well towards that. Deis has crafted an innovative, functional solution that should be reusable in the service layer.

**Comment by carmstrong** [comment]
> A Ceph Service Broker with a pathway to get that filespace into Docker containers would do well towards that.

That's interesting. I don't think we've thought of the service broker using Ceph, but that's an option.

**Comment by bacongobbler** [comment]
> I don't think we've thought of the service broker using Ceph, but that's an option.

It was basically one of the first thoughts towards an initial PoC, though in my thoughts it was for the database (we didn't have Ceph at the time). Slicing chunks of Ceph buckets for application use isn't too far off the beaten path :)

**Comment by carmstrong** [comment]
> It was basically one of the first thoughts towards an initial PoC, though in my thoughts it was for the database (we didn't have Ceph at the time). Slicing chunks of Ceph buckets for application use isn't too far off the beaten path :)

I don't know - seems like different worlds to me, since there is also the possibility of consuming Ceph FS, Ceph block storage, etc. in addition to the S3-compatible blob store. But yes, there are lots of options with the service gateway that we can explore.

**Comment by azurewraith** [comment]
right, @bacongobbler, I was reusing your concept and applying it to my particular use case... giving Dockerfiles with persistence volumes a place to shove their data.  You can also offer up S3 compatible buckets through the rados gateway as well and then you wouldn't have to farm out to your S3 account.

A bare-metal cluster within an intranet typically wants to keep things off of the cloud.  A startup may want to cut out the middleman for external services to save on margins.  In both cases, implementing the most common services (REDIS, SMTP, PostgreSQL, etc.) in a HA fashion simplifies Ops load over rolling that service DIY on separate hardware.  Maybe a separate "Service Plane" is applicable in addition to Control/Data Planes.

The service broker should allow common services to be enabled internally ala' carte and also give should you a pathway towards provisioning those services in common cloud offerings (redis-to-go, sendgrid, etc.) by just simply making a Deis API call.  Some of this might be better said in #231, I'll cut/paste a snippet.

**Comment by ianblenke** [comment]
@Xe turned me on to ipfs.io, and there are a few things there I'm quite keen on.

@Xe and I were also talking at one point about 9fs and something like gfarmfs with an LD_PRELOAD. I mentioned it in #flynn the other day as they were thinking about making flynn offer a 9fs filesystem for the containers to communicate with (in userspace).

**Comment by bacongobbler** [comment]
I think we've answered your question and this conversation has gone stale so I'm going to go ahead and close this, but please feel free to continue the discussion on the user mailing list as that's a better place to ask these questions. That way other users can answer your question which may not be tuned into the github issues. Thanks! :)
