### ISSUE TITLE
Docs on bootstrapping clusters?

### ISSUE THREAD

**Issue by haf** [deis/deis#3233]
While not all clusters are made the same (some use broadcast (cloud haskell), some DNS SRV records (eventstore), some have a single bootstrap IP (consul) and some have any bootstrap IP (riak)) -- it would be great to document a way of coordinating the coalescing and start of a cluster on Deis with the aim to let it spawn on its own, automatically (without intervention with `nse`).

Related to #3227, #3072 -- let me know if I've missed an existing issue discussing this.

**Comment by ianblenke** [comment]
I've not had to use nse or docker exec to create a new Deis cluster.

I've actually managed to submit a fleet unit as part of a cloud-init that  pulls deisctl and does the deisctl steps necessary to initialize a Deis cluster. 

The CoreOS cluster auto-discovers using the cluster discovery url as specified in your cloud-init YAML under coreos.etcd.discovery:

As each CoreOS host defaults to the standard Docker network of 172.17.42.0/24, having DNS discovery doesn't really buy you direct access to other containers deployed for units in the fleet unless you enable flannel, which is something Deis does not do by default.

If you avoid using flannel, it is also possible to have your spawned docker containers communicate with etcd 172.17.42.1:4001 local to each CoreOS machine in order to accomplish service discovery. It is also possible to script `$(fleetctl list-machines -fields=ip -no-legend)` to enumerate the IPs of all of the CoreOS machines in your cluster.

If you use flannel, this would not be as "easy", but is still doable with some sort of DNS approach as you describe.

Another option is using something like mdns/zeroconf discovery with avahi:

https://registry.hub.docker.com/u/ianblenke/avahi/

There are a number of different options, of course, each with their own implementation details and caveats.

**Comment by mboersma** [comment]
> document a way of coordinating the coalescing and start of a cluster on Deis with the aim to let it spawn on its own

This seems like external documentation or a blog post, but not really in scope for the Deis project at this point. Thanks for the pointers @ianblenke. I'm going to close this.
