### ISSUE TITLE
deis-builder: git repositories persistence

### ISSUE THREAD

**Issue by ngpestelos** [deis/deis#3251]
What happens if `deis-builder` gets re-scheduled to another node? Does it lose the git repositories of the currently deployed apps?

**Comment by carmstrong** [comment]
> What happens if deis-builder gets re-scheduled to another node? Does it lose the git repositories of the currently deployed apps?

Yes. And I believe this even happens when it restarts, since it doesn't use a Docker volume for storage. It doesn't break anything, but it means the next deploy may take slightly longer since it's pushing all of the git objects again.

@aledbf Looked at backing up the repos in Ceph, I think, although I can't find the issue/PR.

**Comment by wenzowski** [comment]
I can confirm it loses all repo commits, but that this doesn't really impact much due to how git works. The host pushing the branch has a complete copy of saod branch so there's not much point making sure it's backed up in ceph...unless you're ensuring `git push --force` compliance

my 2 cents is to avoid the :rabbit2: hole

**Comment by bacongobbler** [comment]
the magic isn't git actually moreso than https://github.com/progrium/gitreceive which is the project that handles these repositories.

**Comment by bacongobbler** [comment]
Though I agree that this isn't much of an issue and we shouldn't be spending time fixing what ain't broken :)

**Comment by carmstrong** [comment]
Closed, as the question is answered.
