### ISSUE TITLE
Add command to rebuild app

### ISSUE THREAD

**Issue by klaussilveira** [deis/deis#3271]
Something that i've been missing a lot when moving from Dokku to Deis is the possibility of rebuilding apps: https://github.com/scottatron/dokku-rebuild

In Deis, i have to create empty commits just to bump the HEAD and trigger a rebuild. And this is very dirty.

**Comment by carmstrong** [comment]
@klaussilveira Can you share a use-case for this? I'm not sure I understand why you'd need a rebuild if you haven't changed code or configuration (either of which will trigger a new build).

**Comment by bacongobbler** [comment]
Sometimes if your buildpack relies on something like Amazon S3 uptime and they're down, your build will break. In that case users have to `git commit --allow-empty -m 'bump'` in order to force a new build once S3 is back up.

**Comment by klaussilveira** [comment]
Sometimes you're testing a build change. Or testing a new buildpack. Or sometimes the buildpack is buggy and fails during build time. (node.js, for example, fails a lot)

**Comment by bacongobbler** [comment]
> Sometimes you're testing a build change. Or testing a new buildpack. Or sometimes the buildpack is buggy and fails during build time. (node.js, for example, fails a lot)

In those cases, the build will fail and the commit should be rejected as per the pre-commit hook should do. You should be able to re-push the same commit again. There was a bug in 1.4 which did not cause this behaviour to occur, but https://github.com/deis/deis/pull/3207 was recently merged which should fix this behaviour once again.

**Comment by ticosax** [comment]
May I suggest another use case ?
Applying security update inside the container. For this we need to trig a new build that doens't require code update.

**Comment by carmstrong** [comment]
> Applying security update inside the container. For this we need to trig a new build that doens't require code update.

That makes sense.

**Comment by bacongobbler** [comment]
We don't have access to the app slug after the build is completed. `git commit --allow-empty && git push deis master` allows you to re-push the app with the same code such that you can apply security updates. Given our current infrastructure, I don't think this is something that we can handle.

**Comment by clayzermk1** [comment]
:+1: 

I'm using Node.js and I can provide fuzzy versions for external library dependencies (for example: "~1.2.3" would mean that I installed version 1.2.3 but would accept any hotfix release >= 1.2.3). I can have a successful deployment of my app to the deis cluster, a dependency can release an update, I will want to use that update but have no clean way of rebuilding the app on the cluster just to pull in the new dependencies.

**Comment by Crispy1975** [comment]
Same here. Updates to Node.js modules that are not part of the main repo and are pulled in at build time. Without a rebuild there is no way to pull in the updated plugins or modules.

**Comment by bacongobbler** [comment]
At the moment `git commit --allow-empty && git push deis master` will allow you to perform a rebuild, though I know that's a sub-optimal solution for most users who don't want arbitrary commits in their history.

**Comment by Crispy1975** [comment]
Would be great to get a `deis apps:rebuild -a <app>`. ;)

**Comment by robeferre** [comment]
I want to rebuild an app for this case:

Successfully built 30ca4c05dfd5
-----> Pushing image to private registry
To ssh://git@deis.192.168.57.69.xip.io:2222/queued-sailfish.git
 * [new branch]      master -> master
root@james:/u01/deis_apps/portal# deis info
=== queued-sailfish Application
updated:  2015-11-17T14:58:15UTC
uuid:     76835efd-5767-4aba-a32f-399527657029
created:  2015-11-17T14:58:15UTC
url:      queued-sailfish.192.168.57.69.xip.io
owner:    admin
id:       queued-sailfish

=== queued-sailfish Processes

=== queued-sailfish Domains



I dont have enough info, the processes are down and I cant git push again:

root@james:/u01/deis_apps/portal# git push deis master
Everything up-to-date

**Comment by krancour** [comment]
Just weighing in on this.  I'm against this for a few reasons...

Although the current solution (also recommended by Heroku) of using an empty commit for this use case might feel somewhat clunky, the alternative (the suggested `deis apps:rebuild`) feels even clunkier to me for the simple fact that it's a _departure_ from the git-based deployment workflow.  IMO, the clunkiness that adheres to the promise of a "git-based deployment workflow" is better than the clunkiness that does not.

The whole notion of _rebuilding_ an app is predicated on the notion that builds are semi non-deterministic.  That is to say, building twice over some period of time might produce different results if, for instance, a new version of the buildpack in question or new versions of fuzzy-versioned dependencies are released in the interim.  Since the effective output of the first build vs the second are _different_ deployable artifacts, handling this in git seems the _right_ thing to do.  You may end up with an empty commit, but the message on that empty commit might contain an invaluable explanation for why the application was rebuilt.

On technical grounds, `deis apps:rebuild` would be very difficult to implement.  Currently, the builder does not store git repos anywhere that they will persist between reboots of that component.  What this effectively means is that if the builder component is rebooted, Deis no longer _has_ the latest source for your application.  To rebuild, you would have to be pushing it again, regardless.  To "fix" this would introduce a new dependency for the builder upon Ceph or some other distributed block or object storage.  Given the other two arguments above, I think this is a relatively high price to pay for something that we maybe shouldn't do.

**Comment by Crispy1975** [comment]
@krancour we have now put our daemons to rest and quite happy using the clunkyness of an empty commit. Easy enough to then revert the local so we don't muddy our repo history. :)

This will of course will be something of a moot point when Deis can deploy Docker images from a private registry, nudge, nudge. :)

**Comment by krancour** [comment]
@Crispy1975 would you mind opening an issue for that if you haven't already?  I'm going to close this one.

**Comment by Crispy1975** [comment]
@krancour have started a new issue here: https://github.com/deis/deis/issues/4756
