### ISSUE TITLE
Proposal: have store use CephFS instead of the fragile backup/restore logic

### ISSUE THREAD

**Issue by carmstrong** [deis/deis#3278]
Currently, the deis-database component achieves HA by pushing full backups and WAL logs to the store component via an S3 API. Should the host fail, the component moves hosts, restores from the latest backup, and replays WAL logs until it is fully restored. The backup/restore loop in store seems to be fragile (#2741) and in some cases, it seems to stop backing up entirely (#3276). 

This issue proposes changing database to write its Postgres data directly to the CephFS shared filesystem, removing the fragile bin/boot backup logic. Backups to Ceph/S3 via WAL-e would become optional and a true backup strategy, no longer necessary for restoration during HA failover.

This would have some advantages:
* Recovery is instantaneous once the component starts -- currently, restoring from a backup and replaying WAL logs can take a few minutes
* Data loss wouldn't be possible -- if database can't write to CephFS for some reason, it should crash/restart, indicating an issue with the underlying storage

This change would make it harder for folks to remove the Ceph requirement (#3223), although arguably it would make the implementation more stable/reliable.

An alternative would be to rewrite the backup/restore logic for database using WAL-e, although it seems difficult to get 100% correct in every event.

Curious to hear thoughts from folks.

/cc @aledbf @ianblenke

**Comment by ianblenke** [comment]
Given past experience I had with cephfs on HVM, I'd be hesitant. Since then, however, I've had some pretty good experiences with cephfs on PV. For sheer speed, I wouldn't recommend it. But Deis doesn't need speed here, it needs reliability.  So long as the ceph-mds doesn't eat itself (which has actually happened to me a few times with HVM), it does seem to power through with availability.

The larger risk here though is IO fencing. By this, I mean you do _not_ want more than one postgres writer _able_ to write to the same postgres datastore at the same time. 

CephFS isn't GFS2. It isn't OCFS2. Both lean on a DLM like GULM to ensure IO fencing between the multiple players in the filesystem, locking writes to ensure the storage is quiescent.

Postgres has never been meant to "share" a data store. Knowing how well it handles timelimes today, I can only imagine the horrors that will happen _if_ two postgres instances on two separate servers are permitted to simultaneously write to a shared directory tree containing the raw pg_xlog/pg_clog/pg_log/* files. Remember that slaves write too, it's how they replicate.

For that reason, I'm not sure if it is wise to move the shared postgres data store to ceph-fs.

Have you taken a look at Joyent's SDC stuff, specifically manatee? (https://github.com/joyent/manatee)
That's the approach the flynn project has taken.

**Comment by carmstrong** [comment]
Given @ianblenke's comments and that the root cause of #3276 seems to be addressed by #3128, I'm going to close this as a won't-fix.
