### ISSUE TITLE
feat(controller): add deis ps:stop command

### ISSUE THREAD

**Issue by pjvds** [deis/deis#3293]
Is there a way to stop an application beside executing `deis destroy`?

**Comment by bacongobbler** [comment]
No, but a `deis ps:stop` command should be relatively easy to implement :)

**Comment by pjvds** [comment]
Lets make that my goal for this weekend then. Any pointers?

**Comment by bacongobbler** [comment]
You'll probably want to start [on a proposal](https://github.com/deis/deis/blob/master/CONTRIBUTING.md#design-proposals) similar to [this](https://github.com/deis/deis/pull/3110) PR. After that, you'll want to take a look at the fleet scheduler and implement `.stop()` and hook that into the API.

https://github.com/deis/deis/blob/master/controller/scheduler/fleet.py#L207-L209

**Comment by bacongobbler** [comment]
@pjvds could you please elaborate on why this feature would be useful? I know for heroku this allows you to stop your dynos, effectively stopping from heroku billing you but I'm not sure how a `ps:stop` would be helpful in Deis.

**Comment by ianblenke** [comment]
How about a `deis ps:scale web=0` ?

**Comment by mboersma** [comment]
I agree with @ianblenke that `deis scale web=0` is the way to accomplish this. `deis ps:stop` could be implemented in terms of that.

Not to stifle the proliferation of ideas, but since this hasn't seen any activity in three months I'm closing it. Please do re-open it or just submit a PR @pjvds if you get re-energized about this. :electric_plug:
