### ISSUE TITLE
Docs: comparison with Flynn?

### ISSUE THREAD

**Issue by olalonde** [deis/deis#3333]
I tried to Google for an answer but haven't found one. What are the main differences between Deis and Flynn? Maybe this could be added to the docs as well?

**Comment by ianblenke** [comment]
There are numerous differences between Deis and Flynn, Tsuru, Paz, Solum, Dokku, Dokku-Alt, Galaxy, and other Heroku like PaaS implementations. There are numerous other PaaS implementations that aren't git push centric, like Stratos (WSO2), Cloud Foundry, OpenShift, Stakato, Cloudify, but even those are easily hooked into a git repo to trigger after a git push finishes. The real challenge in any PaaS is release versioning, orchestration of rolls, container scheduling, and ancillary services.

Flynn doesn't use CoreOS, it prefers Ubuntu, though there is "no actual package dependency on it". 

Flynn has a random scheduler, Deis inherits the "least number of units" scheduler presently in Fleet.

Flynn has a postgres database layer using a master/slave failover technique modeled after Joyent SDC Manatee, with no direct backups with wal-e yet.

Deis prefers to run one postgres master (deis-database) and use wal-e and s3 compatible ceph radosgw (deis-store-gateway) for backups and restores.

Deis implements everything as Fleet units which run simple scripts or docker containers with the complexity embedded within. This makes Deis feel very modular (because it is!) 

For CAP, Deis inherits Fleet and etcd for GOSSIP/RAFT by using CoreOS. Many other opensource projects use etcd as well (kubernetes, etc). Flynn has its own discoverd RAFT implementation.

You _can_ submit "services" in flynn via some pretty interesting JSON posts, but it's not really intuitive yet. CoreOS fleet units model well in cloud-init yaml files, and can be installed alongside Deis. Here are some of mine: https://github.com/ianblenke/coreos-vagrant-kitchen-sink/tree/master/tested

This is my limit of exposure to Flynn at the moment. It does seem a bit young, but promising. Many other OpenSource projects have borrowed heavily from Flynn over the past year. It has a bit of maturing to go through operationally, but I wouldn't count it out (continue to keep an eye on it).

There are many other PaaS options out there. I keep coming back to Deis, mostly because I like CoreOS cloud-init fleet units, and I can wrap my brain around how the fleet units that comprise Deis work together.

Honestly, it feels a bit disingenuous to compare Deis to Flynn when there are so many other PaaS implementations to compare it to as well. Gaining operational experience with these tools is something we're all in the middle of at the moment. It probably isn't fair to compare them yet, as most of them are still very young in their lifecycles.

**Comment by bacongobbler** [comment]
> There are numerous other PaaS implementations that aren't git push centric, like Stratos (WSO2), Cloud Foundry, OpenShift, Stakato, Cloudify, but even those are easily hooked into a git repo to trigger after a git push finishes.

Just to correct you (I used to work for ActiveState), but most of them (Cloud Foundry, Stackato, OpenShift) are `git push`-centric. They just have [application manifests](http://docs.cloudfoundry.org/devguide/deploy-apps/manifest.html) which help automate a lot of the tasks people have to do in Deis. Other than that they're practically identical to Deis from the outside... plus or minus a few features here and there.

> Honestly, it feels a bit disingenuous to compare Deis to Flynn when there are so many other PaaS implementations to compare it to as well.

True, but Flynn and Deis came out at practically the same time and are both "open source docker-based PaaS"es when each came out with their PoCs. Most of the other PaaSes came well before Docker, relying on LXC directly. I think that's a valid comparison point :)

As for my contribution to the discussion (from an old Hacker News comment):

From the outside, not much. It's like comparing a toaster to another toaster. Both can toast bread, even if the internals could be completely different.  One could support a "bagel" function and one has a pretty pink accent stripe, but at the end of the day they're both toasters. ;)

Both model the Heroku-style workflow with regard to application deployment. Asides from Deis being production-ready and tacking on a few extra features like `deis pull` and Dockerfile deployment workflows, we take a different philosophical approach towards the platform and its components. We use the best-of-breed components from other OSS projects that work **today** and focus entirely on the application deployment workflow. Flynn is focused on building the platform from the ground up. They provide the network equipment and messaging primitives (layer 0, as they call it) as well as the platform itself (layer 1) completely from scratch. Deis uses common OSS tools such as `nginx` and `ceph` to provide our layer 0 and part of our layer 1 for us and focus entirely on using those components to serve our needs.

![it also got us to market faster](http://i.imgur.com/5h2v6xm.jpg)

**Comment by bacongobbler** [comment]
As an aside, I don't think it's necessary to point out the key differences between Deis and Flynn in the docs. It's just going to be a maintenance hassle to keep it updated as both we and Flynn continue to innovate, and the [PaaS](http://en.wikipedia.org/wiki/Platform_as_a_service) wikipedia article should provide most of the information required.

**Comment by olalonde** [comment]
Wow, great answers but just skimmed so far. I also really like the fact that Deis runs on a CoreOS cluster. I've just successfully installed bitcoind as a CoreOS service alongside Deis (hope it won't mess up with Deis but I don't think so right?).

**Comment by gabrtv** [comment]
Thanks to @ianblenke and @bacongobbler for providing detailed answers to this commonly asked question.  With regard to vision and philosophy, let me point out 3 big differences I see:

1. Deis prioritizes collaborating with other projects and focusing our development resources on integrating best-of-breed technologies into a solid platform.  We believe this will result in the best platform _over time_, as we incorporate improvements to upstream projects.
2. Deis has always had the goal of being the "Docker Native PaaS".  The definition of this means different things at different times, but right now it means contributing to and integrating with Swarm, Compose, etc.  Other PaaS's are less interested in being Docker native.
3. To @bacongobbler's point Deis has always emphasized solving what we view as "real problems" versus "theoretical problems" -- backed by a heavy amount of customer/user interaction.  This is my guess for why Deis has so many production deployments compared to other PaaS's in our space.

This is probably a good opportunity for a blog post :smile:

**Comment by mboersma** [comment]
> This is probably a good opportunity for a blog post

Agreed, but I'm going to close this issue. :bug: :hammer:
