### ISSUE TITLE
Docs: revise deisctl installation instructions

### ISSUE THREAD

**Issue by elepedus** [deis/deis#3353]
On CoreOS 607.0.0, using `curl -sSL http://deis.io/deisctl/install.sh | sh -s 1.4.1` from the documentation failed to create /opt/bin (Permission Denied). Manually creating the directories and re-trying also failed:

    Uncompressing Deis Control Utility  100%  Extraction failed.
    sh: line 27: 14187 Terminated              sh /tmp/$DEIS_INSTALLER $INSTALLER_OPTS

In the end I used `wget http://deis.io/deisctl/install.sh` and `sudo bash install.sh`, which appears to have worked. I recommend updating the installation instructions to make the process more robust.

**Comment by M0dM** [comment]
+1

**Comment by mboersma** [comment]
If you provision Deis according to the documentation, you *should* already have `deisctl` on each node. There is an [install-deisctl.service](https://github.com/deis/deis/blob/master/contrib/coreos/user-data.example#L47-L56) that runs once as root which fetches [`install.sh`](https://github.com/deis/deis.io/blob/gh-pages/deisctl/install.sh) and runs it.

I don't see why `wget` would succeed where `curl -sSL` didn't, but we do add `--retry 5 --retry-delay 2` in the unit file to be more robust. It's true that `install.sh` needs `sudo` on CoreOS itself, but otherwise we prefer `deisctl` be installed by a non-root user. We skipped over this detail I assume to keep the [deisctl install doc](http://docs.deis.io/en/latest/installing_deis/install-deisctl/) simpler, but I agree it's incorrect. I will add a note about `sudo` to the docs.

**Comment by mboersma** [comment]
This works for me&trade; on CoreOS 607.0.0:
```console
$ curl -sSL http://deis.io/deisctl/install.sh | sudo sh -s 1.4.1
```
@elepedus does adding `sudo` after the pipe **|** work for you?
