### ISSUE TITLE
builder: confd[80]: ERROR exit status 123

### ISSUE THREAD

**Issue by bacongobbler** [deis/deis#3382]
This seems to be an issue with the check-repos script after being templated out for the first time. After turning on debug mode for confd, I see:

```
2015-03-26T18:45:12Z 9ed07977d848 confd[80]: DEBUG Overwriting target config /home/git/check-repos
2015-03-26T18:45:12Z 9ed07977d848 confd[80]: DEBUG Running /home/git/check-repos
2015-03-26T18:45:12Z 9ed07977d848 confd[80]: ERROR exit status 123
```

So there's probably some precondtion that's causing this exit code, but it seems fine after the first time.

**Comment by bacongobbler** [comment]
note that the hack in #3408 will probably fix this as well, since check-repos is called on reload: https://github.com/deis/deis/blob/master/builder/image/conf.d/check-repos.toml#L11

**Comment by mboersma** [comment]
> note that the hack in #3408 will probably fix this as well

Yes, except in that case it's `/home/git/check-repos` that has itself as its own check_cmd script. I'll make a similar PR for that one.

**Comment by mboersma** [comment]
In this case, it's because of these lines in `check-repos`:
```shell
docker images | grep $appname | awk '{ print $3 }' | xargs docker rmi -f
docker images --filter "dangling=true" | awk '{ print $3 }' | grep -v IMAGE | xargs docker rmi -f
```
`docker images` may return nothing, and `docker rmi` returns 123 if not given any further arguments. We can fix this by using [`xargs -r`](https://www.gnu.org/software/findutils/manual/html_node/find_html/xargs-options.html), so that the target command is never run unless there are arguments for it. `xargs` default is to run once regardless.
