### ISSUE TITLE
multi tenancy proposal

### ISSUE THREAD

**Issue by apps4u** [deis/deis#3390]
First I want to state Im not expert in security but Ive tested a thought I had about securing the the data deis stores in etcd .

First an key in Etcd that starts with a underscore (_) can not be listed so if the system were to use a large random string that could be set a install or even better updated that started with a underscore would limit any one on the platform from getting to keys that they should not be able to access . Ive tested this and it dose work so for example I replaced the etcd keys that started with ```deis``` to
   
    _somereallylongrandomstringwithnumbers/database/adminUser

so as I siad Im no security expert but if we could make this key be updated after install so it can be changed to stop long running brut force guessing of the hash string than I think that can secure access the to hidden keys.

**Comment by PierreKircher** [comment]
there is no security as of now special not at container level .. a container is not a VM .. its a simple process .. and not even a vm is secure .. you need way more to archive multi tennancy then just a "etcd" scoping and that problem is gone with etcd 2.0 

but you realy want to scope the networking ! ( and with the current overlay mechanics  thats not possible) .. + noone realy knows the security implications of an internal vector .. in short dont run anything in a container you did nod audit carefully .. 

1 example is just a drain of the bandwidth .. kills etcd / datastore communication and produces an dead cluster .. while the goal is certainly reachable unsure if you are aware of the scope + inovation involved cuz there is near to no tooling for that

**Comment by PierreKircher** [comment]
while coreos takes care of the os updates who updates sec holes inside a container ? right noone .. please dump the idea of multitennancy with containers unless you know exactly what you are doing .. and thats going to result in a highly time / cash expensive task

**Comment by PierreKircher** [comment]
https://github.com/coreos/etcd/blob/master/Documentation/rfc/api_security.md

**Comment by apps4u** [comment]
its was just the ectd keys I needed to secure , that's what was on the deis.io site .. I'm not going to use in a public network I just need a way for my clients to be able to run services that we supply that can edit the code but most don't I just wanted to make sure that and passwords in etcd could not be accessed by any one else on the platform. while Im not worried about having one of my client bring down the network as they will kill there own service in the process I do want to make sure any database password or other etcd data is not access able

**Comment by carmstrong** [comment]
@apps4u Let's try a discussion on the [deis-users](https://groups.google.com/forum/#!forum/deis-users) mailing list - I'm not sure this approach is the best one, and hopefully more brains can provide input. Thanks for bringing this up!
