### ISSUE TITLE
proposal renaming of the clients

### ISSUE THREAD

**Issue by PierreKircher** [deis/deis#3401]
deisctl /deis does not realy reflect what they are doing

deis_server_ctl / deis_ops_ctl
deis_client_ctl / deis_dev_ctl

would be more clear,
even if more typing is involved.

of course thats just semantics but for new guys trying deis for the first time .. its all about understanding

**Comment by bacongobbler** [comment]
We've always referred them as `deis` being the client to *use* the platform and `deisctl` being the client to *control* the platform. That seems pretty clear to me. We already have hard links set up with a couple of other platforms like homebrew and pip, so I'm not sure there's a way we can work around this.

To better explain the separation of concerns here:

`deis` communicates with the controller (AKA the API) and provides the developer workflow for users of the platform.

`deisctl` communicates with a scheduler backend to manage the core components, including installation, platform logging, configuration, and health management. This is meant for the administrators of the platform rather than a user.

Is that more clear as to why they're split apart? I don't think we should rename the components, but if there's a way we can improve documentation to make this more clear then that would be the better alternative.

**Comment by mboersma** [comment]
Originally there was just `deis` (a la `heroku`), but it didn't seem correct to bolt on provisioning logic to one binary. So `deisctl` was created for that purpose, once provisioning and cluster control migrated away from scripts. Heroku didn't have a similar tool, and we largely followed the `fleetctl` / `etcdctl` naming convention of our friends at CoreOS when we started the new go codebase for `deisctl`.

I don't think there's a strong reason to change the names now. Is the distinction between `deis` for dev and `deisctl` for ops maybe something we should add to the [FAQ](http://docs.deis.io/en/latest/faq/)?

**Comment by PierreKircher** [comment]
agree, as i sayed its just semantics .. but people get confused all the time. better reflecting docs shoud do just fine
