### ISSUE TITLE
Trouble determining controller URL in Azure

### ISSUE THREAD

**Issue by oddnotions** [deis/deis#3439]
New to Deis, running through the docs to set up an initial base cluster in Azure. I've gotten to the point where Deis seems to be installed and running appropriately; deisctl list gives me a nice long list of loaded, active and running containers across my 3 CoreOS hosts (http://pastebin.com/4kPmVfw4). The docs state that my next step is to register the first user, the superuser, using the deis CLI, using the controller URL provided by "my Deis administrator". I believe my issue is related to the domain that I set in a prior step with deisctl and an inability to reach "http://deis.mydeisdomain.com". In Azure, per the platform instructions in the Deis docs, I created a cloud service container to which my vm hosts are attached. While each host has a unique <hostname>.cloudapp.net, as far as I can tell the only externally resolvable name right now is [containerID].cloudapp.net; going to that URL gets me the Nginx default page of what I assume is the router. And I assume that since it's used likely for every user in Azure at some point that "cloudapp.net" isn't going to cut it here.

I would prefer to do this without purchasing a "real" domain; is that possible in this context? What I've not yet tried is to set up a DNS server locally in my office. Is the only way to do this in Azure to purchase a domain name for the purpose? What's the best/easiest way to get past this and start playing with deploying apps on my test cluster in Azure?

**Comment by chrisgeo** [comment]
In Azure, all your boxes should be behind the same subdomain. In your case myapp.cloudapp.net. They're part of a cluster and all get private IP addresses that are routable between the virtual machines.

After that you need to use the public IP address for your cluster to setup your DNS entries that are part of that cluster. You can see what I mean in the video below where I highlight the path to find that info:

![Azure Cluster IP](http://g.recordit.co/6suOqj25Vx.gif)

Your DNS setup should then use an A record to that IP with a CNAME for *.mydomain.com so all apps point to it. 

Your register setup looks correct, so I think your biggest issue is that you're hosting each VM under it's own cloudapp.net subdomain right now instead of under the same <mysub>.cloudapp.net.

**Comment by itsbrok3n** [comment]
Thanks for the response @chrisgeo. The setup of my cluster actually looks just like yours, with different host names of course. The cluster members are not under their own subdomains -- each has its own hostname, that's true, as with yours, but all are behind the same dns name (the one you highlight in your loop) of <containername>.cloudapp.net. They are individually pingable. It sounds like what you're saying is: yes, you do need to purchase or have access to your own domain name, and that I need to dns map the cluster node IPs to that domain name. Thanks again.

**Comment by bacongobbler** [comment]
> It sounds like what you're saying is: yes, you do need to purchase or have access to your own domain name, and that I need to dns map the cluster node IPs to that domain name.

alternatively, you can use the magic http://xip.io/ DNS service

**Comment by itsbrok3n** [comment]
Fair enough @bacongobbler -- I saw that option, but was not sure I wanted to go down that road. But magic, now that's hard to argue with :-)

Now, since I shut down my cluster nodes from Azure rather than from within the VM consoles, I deallocated my IPs. I figured I could deal with that, but when I restarted the machines Azure gave them all the same public IP (?!) which was... unexpected. Not sure how Deis will handle that since it was my impression that I still wanted to have (as you have) 3 distinct public IPs for my cluster hosts, plus a cluster IP.

**Comment by carmstrong** [comment]
@itsbrok3n Did you use the Azure provision script in the Deis repository? The script outputs the instructions for setting up DNS, including the records you can copy and paste into your registrar.

**Comment by itsbrok3n** [comment]
Yeah, I did. But then instead of using my registrar I tried to get around that, which was the wrong idea. Then I forgot to shut them down by ssh'ing in and doing a shutdown command -- did it from the Azure management interface, and so they all got deallocated. I figured that at worst I'd fire them back up and get 3 new IPs, but that wasn't the case, they came up instead with all of them sharing the same vIP. I'm thinking I might have to just blow them away and run through the script a second time to recreate the whole thing. Went smoothly enough the first tim.

**Comment by carmstrong** [comment]
> I'm thinking I might have to just blow them away and run through the script a second time to recreate the whole thing. Went smoothly enough the first tim.

Ah. Yes, I would destroy the hosted service and create a new one with a completely separate name.

**Comment by carmstrong** [comment]
@oddnotions Is this okay to close?

**Comment by oddnotions** [comment]
Yep, you can close it. Thanks.
