### ISSUE TITLE
Request: no downtime for apps during Deis platform upgrade

### ISSUE THREAD

**Issue by croemmich** [deis/deis#3461]
During platform updates the routers are started last. This means all deployed apps will be offline until the builder has started, which can take quite a while. To reduce downtime, would it make sense to start the builder last?

**Comment by carmstrong** [comment]
> To reduce downtime, would it make sense to start the builder last?

That would work. Several people have asked about supporting better uptime during platform upgrades. We could think about how to allow the routers to remain up as long as possible.

**Comment by szymonpk** [comment]
Maybe It's stupid question - Instead of stop, uninstall, install, can't it be done via 'upgrade' where platform container would be replaced step by step, with respect of proper ceph upgrade if needed? 

For router upgrade maybe it's possible to redirect traffic to other routers? Or allow for supervised router upgrade, where it would be message like 'Press enter to upgrade router#1, you can pull it out from our dns records now' after upgrade 'router#1 was upgraded succesfully, it can be re-added to dns records'. However it make sens only wherever is no ELB-like solution in front of deis.

**Comment by haf** [comment]
If you could model your cluster as a graph in a formalisation like petri nets or hierarchical state machines, you could let a workflow/saga implementation run that graph and ensure different stages... It would also be easier to discuss such a formalisation rather than imperative python code.

**Comment by bacongobbler** [comment]
> If you could model your cluster as a graph in a formalisation like petri nets or hierarchical state machines, you could let a workflow/saga implementation run that graph and ensure different stages...

We have [an informal workflow](https://github.com/deis/deis/blob/4b6cc67dfa6874c4cb5206bbda6b38b3f4bad0d8/deisctl/cmd/cmd.go#L157) for deploying the platform. We just don't have formal "State of the Architecture" documentation.

> It would also be easier to discuss such a formalisation rather than imperative python code.

The controller and the client are the only things written in Python in present. `deisctl` - the tool that handles platform deployments - is pure Go.

**Comment by bacongobbler** [comment]
related: #1988

**Comment by krancour** [comment]
Closed via #4175
