### ISSUE TITLE
Feature request: customize controller host name

### ISSUE THREAD

**Issue by FreakinaBox** [deis/deis#3488]
Is there a config option to set the deis controller url? (deis.example.com)
if not there should be. I am runnig in a corporate environment with strict DNS rules

**Comment by mboersma** [comment]
It's not currently possible to set the "deis" part of the host prefix separately, if that's what you are asking. Whatever domain you use to access your Deis cluster, there are some hard-coded prefixes that the router mesh recognizes in order to route traffic to the proper component, and this is one of those.

**Comment by bacongobbler** [comment]
there are a few edge cases which concerns me a little with changing the controller URI in the router:

1. We have to refuse API requests for creating apps with the same name
2. We have to refuse API requests for custom domains with the same endpoint

We have [those measures in place](https://github.com/deis/deis/blob/master/controller/api/models.py#L93-L96), hence the concerns. Any thoughts on this?
