### ISSUE TITLE
Error: 501: All the given peers are not reachable (Tried to connect to each peer twice and failed) [0]

### ISSUE THREAD

**Issue by pdhar-tibco** [deis/deis#3489]
I have tried many times and looked around for similar hiccups while trying to get my feet wet with deis.
I am stuck at the first deisctl usage step in the following order from my macosx(192.168.1.75) terminal to the vm running CoreOS(192.168.1.77)
 
ssh-add ~/.ssh/deis
export DEISCTL_TUNNEL=192.168.1.77
deisctl config platform set sshPrivateKey=~/.ssh/deis
where I end up getting the Error:501.

I made sure I use a fresh new discovery url https://discovery.etcd.io/480c56c72474af10aabfc66b60d1014f

I am not sure where I am going wrong or there is a problem in deis.

**Comment by bacongobbler** [comment]
FYI we don't support single-node deployments. You need [at least 3](http://docs.deis.io/en/latest/installing_deis/system-requirements/) nodes to deploy Deis.

As for your question, I'd inspect etcd on the CoreOS host. Start by ssh'ing in and running `systemctl status etcd`, `systemctl status fleet` and `journalctl`. Could you please provide those logs into a gist? Thanks!

**Comment by pdhar-tibco** [comment]
I have posted into a gist deis.log <https://gist.github.com/pdhar-tibco/fe02cfc5bf9d2fef2867> .
When there is a requirement of at least 3 nodes. Does it mean I need to create 3 coreOS virtual machines instances on the vmware fusion running on the host mac book.

-Pranab

**Comment by bacongobbler** [comment]
your etcd is in a `auto-restart` loop, which means that it is indeed failing. A `journalctl --no-pager -u etcd` should reveal the problem.

> When there is a requirement of at least 3 nodes. Does it mean I need to create 3 coreOS virtual machines instances on the vmware fusion running on the host mac book.

Indeed it does. Since it requires a minimum of 2GB per node it's best to have at least 16GB of RAM on your host so that there's enough space for the host system (my laptop with 8GB consistently crashes with virtualbox, for example).

**Comment by pdhar-tibco** [comment]
I do see the etcd repeating in a failure loop. The output gist is here journalctl --no-pager -u etcd <https://gist.github.com/pdhar-tibco/e1af8793c9fff96a0e29>

-Pranab

**Comment by bacongobbler** [comment]
VMWare Fusion doesn't set up a private IPV4 address properly on CoreOS, which is why you'd be seeing https://gist.github.com/pdhar-tibco/e1af8793c9fff96a0e29#file-journalctl-no-pager-u-etcd-L5083. It's one of the reasons why we don't fully support that platform for Deis. :(

CoreOS has said that they can't support providers which don't have a hosted metadata service to determine the IPv4 addresses in coreos/bugs#97. As mentioned in one of the comments, you'll have to statically configure the addresses, so if there is a will, there is a way. It's just un-treaded territory :)

**Comment by bacongobbler** [comment]
closing in favour of CoreOS' response in coreos/bugs#97. Short of "officially" supporting VMWare Fusion there's nothing actionable to fix this in deis. If you do get it working, a PR to update the docs on working with VMWare Fusion would greatly be appreciated :)
