### ISSUE TITLE
After upgrading to 1.5.1 deis uses lot more resources

### ISSUE THREAD

**Issue by nathansamson** [deis/deis#3501]
Hi

I've upgraded to v1.5.1 a few days ago.

Since then I see on resource usage graphs (bandwidth & cpu) that all my nodes are a LOT more active.

I also noticed that deploying new apps seems to take more time than before (although this was a feeling that I can't proof).

This is even resulting in etcd timeouts & other impacting problems.

I believe this might be related to #3479 

One thing I noticed that some nodes are running more than one confd at the same time, I am not sure if that is normal.

**Comment by bacongobbler** [comment]
we heard from @aledbf that this is due to the `--watch` changes for confd in v1.5, which basically turns out that this new feature is not how we expected it to work.

> One thing I noticed that some nodes are running more than one confd at the same time, I am not sure if that is normal.

Yes, that is normal. Each container runs its own confd process so a `ps faux` on the host would show all of those running processes.

**Comment by bacongobbler** [comment]
more specifically check out the asciicasts on https://github.com/coreos/etcd/issues/2679#issuecomment-93019720
