### ISSUE TITLE
deisctl install platform hangs when < 3 nodes

### ISSUE THREAD

**Issue by bastilian** [deis/deis#3529]
When running less then 3 nodes `deisctl install platform` will hang indefinitely waiting for routers to be loaded.

This is likely caused by `deisctl` itself, due to it trying to install 3 routers ([cmd.go#L441](https://github.com/deis/deis/blob/master/deisctl/cmd/cmd.go#L441)): 

```go
b.Create([]string{"router@1", "router@2", "router@3"}, wg, outchan, errchan)
```

The documentation "strongly recommends" 3 nodes, the above kinda "requires" it.

I'm not sure if simply reducing the array to just router@1 would be the right thing to do or changing the documentation to state that 3 nodes are required for deis to run correctly.

**Comment by onbjerg** [comment]
What are the specs on the individual nodes?

**Comment by onbjerg** [comment]
It says right here in the documentation: http://docs.deis.io/en/latest/installing_deis/system-requirements/#cluster-size

>Deis clusters of less than three nodes are unsupported.

**Comment by onbjerg** [comment]
But yes, the "strongly recommend" part would need to be updated in /docs/contributing/hacking.rst as well.

**Comment by bacongobbler** [comment]
The hard requirement is really due to ceph. If ceph loses quorum then your data is lost, so we make it set up 3 OSDs:

https://github.com/deis/deis/blob/master/store/monitor/bin/boot#L9
https://github.com/deis/deis/blob/master/store/base/templates/ceph.conf#L9

We can easily run just one router, but the storage layer isn't as scalable when it was first implemented.

**Comment by carmstrong** [comment]
> If ceph loses quorum then your data is lost, so we make it set up 3 OSDs:

Not quite - data isn't lost. And the monitors are what maintain quorum, not the daemons. Daemons store replicas of data.

The requirement for having multiple hosts, for Ceph or otherwise, is redundancy. Deis is a distributed system, and requiring three nodes is more or less hard requirement. If fewer hosts is a requirement for your environment and you're happy to give up the benefits of a fault-tolerant redundant distributed system, check out [Dokku](https://github.com/progrium/dokku).

**Comment by bastilian** [comment]
Thanks all for clearing this up!

I think that  /docs/contributing/hacking.rst should reflect that it is a requirement or mention the requirement by referencing "Cluster Size" on the installation guide.

The reason I ran into this is that I'd like to hack on my Macbook Air, which dies when booting three VMs, and therefor I lowered the number of instances. I believe if it is possible to lower the requirements for development, it would ease the way into hacking on deis.

**Comment by carmstrong** [comment]
> I think that /docs/contributing/hacking.rst should reflect that it is a requirement or mention the requirement by referencing "Cluster Size" on the installation guide.

We'd be happy to review a PR that makes the docs clearer!

> I believe if it is possible to lower the requirements for development, it would ease the way into hacking on deis.

Understood, and we discussed this when we bumped the requirement to three hosts. But Deis is a distributed, clustered system. Development environments should really replicate this environment as closely as possible, since so much of the functioning of Deis is dependent on having multiple hosts.
