### ISSUE TITLE
Clarification: how scalable is deis-registry?

### ISSUE THREAD

**Issue by krancour** [deis/deis#3617]
`deisctl` permits the `deis-registry` component to be "scaled," and comments in the `deisctl` code specifically call it out as being one of the few components that can currently scale.

But when I look at unit files for deployed applications, they all get the registry address from the etcd keey `/deis/registry/host`.

So, I'm looking for some small bit of clarification here.  Am I missing something?  Or does "scalable" here actually have more to do with creating warm standbys than it does with scaling capacity?  If additional registries are nothing but warm standbys, what advantage (if any) does creating those offer over, say, simply preseeding all nodes with the Deis component images?

If nothing else, there's an opportunity to address this in the documentation, which I am happy to work on once I understand this better.

**Comment by bacongobbler** [comment]
> If additional registries are nothing but warm standbys, what advantage (if any) does creating those offer over, say, simply preseeding all nodes with the Deis component images?

The failover is slightly faster because you don't have to wait for the registry to boot, but otherwise the advantage is minimal.

As for `deis-router`, that is up to the load balancer. The load balancer will route requests and pass it off to one of the routers for processing, so the routers are a true master/master setup. The registry *can* be a master/master setup, but components like the builder require a single endpoint. Since we don't have internal DNS discovery, we use the "masterLock" logic to force `/deis/registry/host` to be one of the hosts until it goes down, which then another registry will take its place. See https://github.com/deis/deis/pull/2434 for the justification behind the masterLock publishing logic.

**Comment by krancour** [comment]
Ugh... sorry... any reference to "router" in my original post, was _meant_ to say "registry."  My bad.  Editing accordingly so the question actually makes sense.

**Comment by bacongobbler** [comment]
Okay. My statement still stands though. The only reason why it was made "scalable" was for fast fail-over. At present it's not necessarily scalable as in it can handle a larger load, rather it was originally for redundancy purposes. It is possible to turn it into a master/master setup, but we don't have that infrastructure available at the moment.

Does that help answer your question? :)

**Comment by krancour** [comment]
Sure does.  Thanks for clarifying.  Closing.  :)
