### ISSUE TITLE
ec2: Consider using EBS volume for etcd

### ISSUE THREAD

**Issue by jwaldrip** [deis/deis#3618]
When running a 5 node cluster, stopping and starting a node causes the cluster to fail.

Using the cloud formation scripts do the following:

* Boot a 5 node cluster in amazon.
* Ensure etcd is running and has consensus.
* Stop a node (thus wiping out ephemeral storage).
* Start the Node.

Expected: Cluster Unaffected, Node Rejoin
Actual: Cluster-wide failure, Ephemeral disk fails to mount, All nodes crash etcd.

Solution?

Don't use ephemeral storage for etcd.

**Comment by carmstrong** [comment]
We use ephemeral storage because it's fast. We previously had issues where etcd's disk writes would be blocked by system IO to other disks, and fleet would consider the host dead because it would effectively leave the cluster. This caused etcd leader thrashing, constant rebalancing, and a slew of other issues.

I was under the impression that stopping a node would indeed wipe ephemeral storage, but a reboot will not. I would think that stopping an instance is something that wouldn't normally happen with day-to-day usage. Is this something you saw in a live cluster, @jwaldrip, or was this something you came across during resiliency testing?

> Actual: Cluster-wide failure, Ephemeral disk fails to mount, All nodes crash etcd.

I'm not sure how one node would take down the whole cluster. Do you have etcd logs from the other cluster members? This sounds like a bug we could open upstream at coreos/etcd.

**Comment by jwaldrip** [comment]
This is something we saw in a live cluster. It may have to do with the disk trying to mount that triggered the failure. Unfortunately I do not have the logs handy anymore. Also is gp2 storage that much slower than ephemeral?

**Comment by carmstrong** [comment]
Ok - this is something we should try to reproduce. 

> Also is gp2 storage that much slower than ephemeral?

Maybe not. Originally we were using the default EBS volume types, which were magnetic, so the difference was significant. We should revisit this and consider using an EBS volume for etcd too.

**Comment by helgi** [comment]
gp2 would be slower than ephemeral due to network but you can also get Provisioned IOPS (PIOPS) if you wanted to make it a bit more consistent and closer to ephemeral (I have no real numbers at hand). 

One thing to consider is that without PIOPS you get a certain allotment of IOPS (3k) per each half hour interval so depending on churn you could hit a wall (https://aws.amazon.com/blogs/aws/new-ssd-backed-elastic-block-storage/ the under the hood bit has the relevant details).

Maybe consider one of the memory filesystems that drop to disk to allow for the persistance if this becomes a bottleneck. Generally gp2 should be enough for this, just wanted to give some background.
