### ISSUE TITLE
Discussion: app unit publishing timeouts between publisher and router

### ISSUE THREAD

**Issue by glogiotatidis** [deis/deis#3674]
Changes in the apps, like deployment of new versions or scaling, are not instantly reflated to the routers which results in routers sending traffic to dead containers.

I manage to reproduce this using this simple scenario:
1. Build an app with the example-ruby-sinatra app
2. Make sure that there is 1 web process
2.5 Start a loop, requesting the app url 
3. Scale the down to zero using `deis scale web=0`
3.5 Stop request the app url

The logs collected between steps 2.5 and 3.5 are the following
```
HTTP/1.1 200 OK
HTTP/1.1 200 OK
HTTP/1.1 200 OK
HTTP/1.1 200 OK
HTTP/1.1 200 OK
HTTP/1.1 502 Bad Gateway
HTTP/1.1 502 Bad Gateway
HTTP/1.1 502 Bad Gateway
HTTP/1.1 503 Service Temporarily Unavailable
HTTP/1.1 503 Service Temporarily Unavailable
HTTP/1.1 503 Service Temporarily Unavailable
```

The `200 OK` lines are expected, since the application is running. The `503 Service Temporarily Unavailable` are OK too since we scaled down to zero, thus there are no gateways. But the three `502 Bad Gateway` lines mean that nginx redirects traffic to servers that no longer exist.

**Comment by carmstrong** [comment]
> Changes in the apps, like deployment of new versions or scaling, are not instantly reflated to the routers which results in routers sending traffic to dead containers.

This is by design, although I agree it's something we need to improve upon. Here's how it currently works:

* An application container is started with `deis scale`
* The `publisher` component, which is connected to the Docker daemon and listens to its event stream, detects that a container was started and [publishes](https://github.com/deis/deis/blob/a7301968bba5b3b1d7f8cb6c278fc77fda14d294/publisher/server/publisher.go#L45-L69) it with a TTL of [20s](https://github.com/deis/deis/blob/a7301968bba5b3b1d7f8cb6c278fc77fda14d294/publisher/main.go#L15-L16)
* The `router` component runs `confd` every 5 seconds, which templates `nginx.conf` with the app containers which have been published to etcd and then instructs nginx to gracefully reload

When an application container stops, publisher does not renew the etcd key's TTL on its next pass. Remember that these keys have a 20s expiry. Once the key expires from etcd, the router's confd (within 5s) re-templates the configuration and reloads nginx. 

So, there is indeed a delay from when an application container stops and when the router stops serving traffic for that application container. Note, though, that seeing a 503 in this case is expected, since there are no upstreams defined to service the request after the single container stops. The 502 is probably evidence of this "upstream existing but not responding" case.

Some thoughts:
* We may be able to tweak the publisher's TTL for keys as well as the router's frequency of confd updates - the router could update 1s or so which would increase load on etcd substantially, but perhaps this is acceptable to have better responsiveness for apps
* With a large number of app containers, perhaps the publisher loop through all containers takes too long? I could imagine a scenario where thousands of containers would take some time for publisher to renew all keys, in extreme cases even taking longer than 20s to get through them all

**Comment by bacongobbler** [comment]
> When an application container stops, publisher does not renew the etcd key's TTL on its next pass. Remember that these keys have a 20s expiry. Once the key expires from etcd, the router's confd (within 5s) re-templates the configuration and reloads nginx.

This used to be true, but as of #3204 we remove the etcd keys once the container is stopped, so maybe there's a timing issue here.

**Comment by carmstrong** [comment]
> This used to be true, but as of #3204 we remove the etcd keys once the container is stopped, so maybe there's a timing issue here.

Ok, so that means the delay is likely isolated to router. We should do some testing to see if having the router update more frequently causes any issues.

**Comment by glogiotatidis** [comment]
> Ok, so that means the delay is likely isolated to router. We should do some testing to see if having the router update more frequently causes any issues.

This seems a plausible solution. I'm offering to try if you can provide me with instructions / image.

**Comment by carmstrong** [comment]
> I'm offering to try if you can provide me with instructions / image.

Great. I can build you a custom router container with the change. I'm just trying to decide which route to take - we can:
* Lower the [confd update interval](https://github.com/deis/deis/blob/ebc3df479a672acb4a81525ba1edd0fb4d70a6a9/router/boot.go#L136) for the router to something smaller than 5 seconds
* Re-enable confd watch for the router - we previously enabled this for all components in #3387 and then had to revert in #3517 -- see the reasons in #3505. Basically, this resulted in a ton of traffic to/from etcd, since we were getting notified every time a key's *TTL* changed, not just its value.

@glogiotatidis Maybe I'll build you two routers, one with an update interval of 2 seconds or so, and one with confd watch enabled. You could switch them out at your discretion.

**Comment by carmstrong** [comment]
Ok @glogiotatidis, here are the images as promised. Let me know how these work out for you! Just a note that these were built off master, so will have nearly all the changes that are going into Deis 1.7.0.

Using `carmstrong/deis-router:2secinterval` will give you a router using an interval of 2 seconds instead of 5 seconds:
```console
$ deisctl config router set image=carmstrong/deis-router:2secinterval
$ deisctl restart router@*
```

Here's the diff:
```diff
diff --git a/router/boot.go b/router/boot.go
index 10d21e8..3256336 100644
--- a/router/boot.go
+++ b/router/boot.go
@@ -133,7 +133,7 @@ func waitForInitialConfd(etcd string, timeout time.Duration) {
 }

 func launchConfd(etcd string) {
-       cmd := exec.Command("confd", "-node", etcd, "--confdir", "/app", "--log-level", "error", "--interval", "5")
+       cmd := exec.Command("confd", "-node", etcd, "--confdir", "/app", "--log-level", "error", "--interval", "2")
        cmd.Stdout = os.Stdout
        cmd.Stderr = os.Stderr
```

Using `carmstrong/deis-router:watch` will give you a router using confd watch:
```console
$ deisctl config router set image=carmstrong/deis-router:watch
$ deisctl restart router@*
```

Here's the diff:
```diff
diff --git a/router/boot.go b/router/boot.go
index 3256336..44c3cdc 100644
--- a/router/boot.go
+++ b/router/boot.go
@@ -133,7 +133,7 @@ func waitForInitialConfd(etcd string, timeout time.Duration) {
 }

 func launchConfd(etcd string) {
-       cmd := exec.Command("confd", "-node", etcd, "--confdir", "/app", "--log-level", "error", "--interval", "2")
+       cmd := exec.Command("confd", "-node", etcd, "--confdir", "/app", "--log-level", "error", "--watch")
        cmd.Stdout = os.Stdout
        cmd.Stderr = os.Stderr
```

**Comment by glogiotatidis** [comment]
Thanks @carmstrong. 

I tried the watch image without luck, I still get 502s.

**Comment by ben-ng** [comment]
The original issue is about the gateway errors when processes are scaled to zero, but i'm also seeing the gateway errors in between deploys. Using [this test app](https://gist.github.com/ben-ng/7c8d0c537acfb0289617) that sleeps 45 seconds before listening, I see about 40 seconds of the gateway error after a deploy.

This is causing us issues at Getable, because we go down for several minutes in between deploys.

**Comment by ghostbar** [comment]
I think the optimal solution for this is waiting until `web.1_v30` actually starts listening on the port in order to replace it with `web.1_v31` on the nginx configuration and then kill the `web.1_v30` container.

**Comment by glogiotatidis** [comment]
> The original issue is about the gateway errors when processes are scaled to zero, but i'm also seeing the gateway errors in between deploys. Using this test app that sleeps 45 seconds before listening, I see about 40 seconds of the gateway error after a deploy.

We get exactly the same errors. I just reported with scaling down to zero b/c it's the easiest scenario to reproduce.

**Comment by carmstrong** [comment]
This is being tracked in #3813, which is a solution to address a number of issues for application health checks during deploy and publishing.
