### ISSUE TITLE
Feature Request: Configurable Upchecks

### ISSUE THREAD

**Issue by jwaldrip** [deis/deis#3723]
Allow the configuration of "up checks" that will be called to confirm if a container is up during a deploy. The upcheck should be in the form of an http action and url and optional response substring.

`deis upcheck:set get /heartbeat "lubdub"`
`deis upcheck:unset`

**Comment by carmstrong** [comment]
This sounds related to #1829 and #3674. @jwaldrip what do you think of the discussions in those issues?

**Comment by jwaldrip** [comment]
1829 is canary deploys, I am not talking about doing that here. This is just true zero downtime deploys. Simple and straight forward.

**Comment by carmstrong** [comment]
So to define this in terms of code/scope/work: you're proposing a per-app healthcheck that the controller would use to confirm a container is running beyond checking the controller state, correct?

**Comment by PierreKircher** [comment]
@carmstrong the thing we see at brandfolder is an old version gets destroyed before a new one is up and running .. 

so publisher needs a check at least for status 200 ( and possible a regex body matcher configureable via etcd ofc ) before mapping that stuff to etcd ,, that prevents the issues seen in #3674

the other problem is that the controller tells the scheduler to delete the old version as soon as the new version is there even if it did not boot up sucessfull .. we could write a state with publisher to etcd .. and clean them up with a job in the controller instead of destroying them directly .. 

that way we might have 2 versions online for a few seconds but archice a true 0 downtime .. 

id like to hear thougths on that

**Comment by carmstrong** [comment]
This is being tracked in #3813, which is a solution to address a number of issues for application health checks during deploy and publishing.
