### ISSUE TITLE
ssh-cert.key and password on Azure

### ISSUE THREAD

**Issue by josephwinston** [deis/deis#3732]
I've run `azure-coreos-cluster` and added the suggested lines to `~/.ssh/config`.  However, ssh now is asking for the password for the SSH key "ssh-cert.key'.  Where in the documentation do I go to find what value needs to be used here?

**Comment by carmstrong** [comment]
So that key is generated by [generate-mgmt-cert.sh](https://github.com/deis/deis/blob/master/contrib/azure/generate-mgmt-cert.sh) which uses [cert.conf](https://github.com/deis/deis/blob/master/contrib/azure/cert.conf). The config didn't specify a password, so I'm not sure why you're being prompted...
