### ISSUE TITLE
deisctl start platform takes very long time to complete

### ISSUE THREAD

**Issue by cddr** [deis/deis#3742]
As per the installation instructions, I ran `deisctl start platform` to start deis on a set of vagrant machines. For me, the command takes around 20 minutes to complete. I thought this might just be the first time due to downloading dependencies but it seemed to take even longer the next time.

**Comment by PierreKircher** [comment]
thats normal builde is huge / the cloudinit has a preseed command which helps to speed stuff up .. run that on every node .. and you see a huge speed improvement

**Comment by bacongobbler** [comment]
When the units are started, they have to [pull the image](https://github.com/deis/deis/blob/master/deisctl/units/deis-builder.service#L8) which can take some time. Builder has some images that it depends upon, so it needs to pull those during boot in order to accept pushes for the first time. As @PierreKircher mentioned there is a [pre-seed script](https://github.com/deis/deis/blob/master/contrib/coreos/user-data.example#L141) that you can run on each host, but again it will take some time to complete.

We are continuing to make the images as small as possible (we've probably hit the limit by now). Short of shipping our own CoreOS images with the components pre-seeded on each host (#1153) there's not much else we can do at this point. If you have any ideas we are always welcome for input!

**Comment by cddr** [comment]
> If you have any ideas we are always welcome for input!

If that's just as long as it takes that's fine. I was just concerned that I might have had something mis-configured which caused it to take longer than it should. One thing I'm still not clear on though is how much of this you have to redo when you restart the host machine. Would the preseed help in a vagrant setting?

**Comment by bacongobbler** [comment]
> One thing I'm still not clear on though is how much of this you have to redo when you restart the host machine.

Since the host will leave the cluster, it will begin by re-scheduling the units to other hosts. You shouldn't have to re-do anything.

> Would the preseed help in a vagrant setting?

I guess that depends on how fast your internet is at your office and if you're willing to pull every component on every host.

**Comment by mboersma** [comment]
Let's add something to the documentation and / or `deisctl start platform` itself that makes it more clear that this is a time-consuming operation.

**Comment by technosophos** [comment]
I'm looking into running the Docker image building in parallel during builder's boot. Are there any known issues with trying to do that?

**Comment by bacongobbler** [comment]
As long as the builder isn't accepting git pushes at that time, that should be fine. Obviously the builder needs these images to be available to run the build process for non-Dockerfile builds.

**Comment by mboersma** [comment]
There isn't much really to be done about the startup time overall, especially now that Deis is required to serialize all the `docker pull` operations on a host. I'm closing this, but see #3568.
