### ISSUE TITLE
Are there any docs on how Deis handles servers going down?

### ISSUE THREAD

**Issue by scottrobertson** [deis/deis#3743]
Hey,

Sorry if this has been asked, or is obvious. I have tried to find some docs on how Deis handles the host machines going down, but I couldn't see anything. 

Say we have 3 host machines, i know that if 1 goes down, it will route the traffic to the other 2, but what happens if 2 go down? Will Deis run on 1 machine for a short time? Or is it like Mongo, and just refuse to do so?

**Comment by yebyen** [comment]
There should be some docs, for sure, but I can share my experience for some anecdotal stories.  The first thing to note should be, for most of my experience I have been running the minimum number of nodes with the minimum amount of RAM (4GB).

I have heard it said that this is not enough RAM for ceph to correctly recover from an unexpected store node going out.  So, your experience may vary with adding more RAM on each node.

I have also heard it said that Deis requires a minimum of 3 nodes to operate normally.  This seems to be almost correct from my experience -- the caveat that if you have 3 nodes and your apps are all scaled to 2 or more workers, you may be able to suffer the loss of one node without incurring any downtime on your apps, but you won't be able to deploy new apps or app versions until you relieve the situation.

With only two nodes, even with enough RAM, I suspect you will probably get split-brained.  You need three or more to be up for the usual reason in any cluster, even numbers during leader election can result in ties.

For me, this "relieving the situation" has usually meant rebuilding the cluster.  (It's significantly faster than diagnosing ceph issues or attempting a recovery to just rebuild the whole thing from scratch.  This might not be true if I knew more about ceph.  That stuff is probably very well documented.)

Advice I have received says that building 5-node clusters will leave you resilient to the loss of 2 nodes.  I have not confirmed this experimentally; the only time I have "tested" removing nodes (oops), it was 3 nodes of 5 going down at once, my apps were not scaled up to run on each node, the two machines that were left were less than a quorum, therefore the failure did not result in apps gracefully remaining available to the router, and ceph did not come back so fleet could not restore the downed containers successfully.

A doc detailing "the various ways that DEIS can fail (both gracefully and otherwise)" might be best approached with a format like "Don't do what Donny Don't does."  The summary at the top could probably read "have enough nodes with enough ram and don't forget to scale your apps."

Any other advice?  "Try it in a test environment before it happens in production" is one more.

**Comment by Joshua-Anderson** [comment]
PR #4277
