### ISSUE TITLE
After upgrade to 1.7, sites are 404'ing and cannot push

### ISSUE THREAD

**Issue by scottrobertson** [deis/deis#3819]
I am using the ruby buildpack, it pushes, builds the image, and then i get the following:

```
/home/git/builder: line 175: cd: /home/git/site.git: No such file or directory
```

**Comment by scottrobertson** [comment]
All sites are down, so any help would be appreciated. I have backups from 1.6 if needed.

**Comment by mboersma** [comment]
@scottrobertson that probably corresponds to this line of code: https://github.com/deis/deis/blob/master/builder/rootfs/etc/confd/templates/builder#L175

Did builder actually run the buildpack, or was everything up-to-date? I'm curious how we could get that far in the script without the directory existing. Could you post more context from the builder log? I'm wondering if somehow the `check-repos` script was invoked and didn't find the expected keys.

**Comment by scottrobertson** [comment]
@mboersma yeah it runs the full buildpack totally fine. I just tried again and got a different error, not sure if it's helpful:

```
-----> Building Docker image
remote: Sending build context to Docker daemon 54.65 MB
remote: build context to Docker daemon
Step 0 : FROM deis/slugrunner
 ---> c33e3f1fb966
Step 1 : RUN mkdir -p /app
 ---> Running in e768d54e834c
 ---> a8408ecbead6
Removing intermediate container e768d54e834c
Step 2 : WORKDIR /app
 ---> Running in 604479db07f1
 ---> 80ec89250df4
Removing intermediate container 604479db07f1
Step 3 : ENTRYPOINT /runner/init
 ---> Running in 3cc4518b9411
 ---> ff595f49644e
Removing intermediate container 3cc4518b9411
Step 4 : ADD slug.tgz /app
fatal: Unable to read current working directory: No such file or directory
time="2015-06-08T18:59:04Z" level="info" msg="lstat /var/lib/docker/overlay/421f41bd300066c97023b945428595bf07015b3a8f55e0c63b7fd4fabd49f19f/merged/usr/share/locale-langpack/el/LC_MESSAGES/subdomain_parser.mo: no such file or directory"
```

**Comment by mboersma** [comment]
I'm wondering if somehow the builder cleanup script is getting triggered when it shouldn't--see #3752. Although if the /deis/services/appname directory exists, it should be left alone, and deleting the .git directory generally only has the effect of removing the cached artifacts in my testing.

If it's possible to capture more builder log lines above and below one of these errors, we could maybe tell if that's what is happening. You would see some Docker image cleanup messages.

Other than that, the big hammer workaround is usually to destroy and recreate the app.

**Comment by scottrobertson** [comment]
@gabrtv is having a look into it at the moment. Shall update you on the progress. Thank you

**Comment by mboersma** [comment]
To follow up with offline investigations: the problem is that v1.6.x created `/deis/services/appname` dirs with a TTL, and having publisher down for longer than that amount of time causes the keys and dirs to age out and disappear, which can clean out the appname.git directory as well now that the `check-repos` script is functional.

#3822 should fix this behavior on upgrade by giving the dirs a TTL of 0, meaning "never expire".

**Comment by carmstrong** [comment]
@scottrobertson Do you have your shell history for your upgrade commands? We're actually having trouble reproducing this on an upgrade from 1.6.1 to 1.7 -- the apps continue to publish just fine.

Anything you can provide that would help us to replicate your environment and your upgrade strategy would be super helpful. Thanks!

**Comment by bacongobbler** [comment]
@scottrobertson I think I found the real issue here. Did you forget to uninstall the old units, then reinstall the new v1.7 units as per the docs? deis-publisher in v1.7 relies on the `--host` and `--etcd-host` flags which are in the new units. If you did a straight `deisctl config platform set version=v1.7.0 && deisctl restart platform`, publisher won't know where to read/write from etcd, as well as the actual host to publish.

**Comment by scottrobertson** [comment]
Hey @bacongobbled,  sadly I did not forget. I fully uninstalled everything first,  exactly like the the docs say.

**Comment by scottrobertson** [comment]
@carmstrong here is my full history of what I did:

```
s3cmd sync s3://db_wal .
s3cmd sync s3://registry .
rsync -avz deis-1.hostname.com:dump_all.sql .
deisctl stop platform && deisctl uninstall platform
curl -sSL http://deis.io/deisctl/install.sh | sh -s 1.7.0
deisctl config platform set version=v1.7.0
deisctl install platform
deisctl start platform
```

**Comment by carmstrong** [comment]
> here is my full history of what I did:

Could you gist your local copy of `deis-publisher.service` in `~/.deis/units`?

**Comment by scottrobertson** [comment]
@carmstrong https://gist.github.com/scottrobertson/11a11abc5235b141ad16

**Comment by carmstrong** [comment]
@scottrobertson That unit is older than v1.7 (note that it's missing `--host=$COREOS_PRIVATE_IPV4 --etcd-host=$COREOS_PRIVATE_IPV4`), so that would explain that you are indeed seeing the issue as @bacongobbler described it. The deisctl installer should automatically run `refresh-units`, though a bug identified in v1.7 would explain this issue (#3832). So it sounds like you were quite unlucky :(

Could you run `systemctl cat deis-publisher` on one of your CoreOS hosts? That would confirm for sure that you're using the older unit. The new one should look like this: https://github.com/deis/deis/blob/master/deisctl/units/deis-publisher.service

I'm betting that once we fix #3832 and build a new `deisctl`, that installing that and installing the new publisher unit would get you running on v1.7 just fine...

**Comment by scottrobertson** [comment]
@carmstrong me.. unlucky with an upgrade? I don't believe you! :P

The publisher on the hosts is an older one, as @gabrtv downgraded it to fix it for now.

Good catch on this. Glad we managed to find it before it affects more people.

**Comment by carmstrong** [comment]
> The publisher on the hosts is an older one

Right, but I doubt he updated the unit definition - he probably just set `deisctl config publisher set image`, right? That means the unit definition was never changed from the old one.

In either case, I think we've found our smoking gun. We'll need to hotfix #3835

**Comment by ineu** [comment]
Hi guys. Just upgraded to 1.7, and everything is down for me as well. ~/.deis/units is also full of files without .service extension for me, and deis is running old images. Looks like I'm unlucky as well :)
So, while the fix is going to the repo, could you please describe how do I make cluster working again?

**Comment by scottrobertson** [comment]
I would wait for others, but by the looks of it, this is what fixed mine for now:

```
deisctl config publisher set image=deis/publisher:v1.6.1
deisctl restart publisher
```

Like I said, I would wait for someone else to reply though, as I am not 100% sure.

**Comment by dpretty** [comment]
@ineu : I had the same problem and can confirm that @scottrobertson's solution to set publisher to 1.6.1 worked for me too.

**Comment by scottrobertson** [comment]
Just to point out, it was @gabrtv who worked this out originally. I don't want to take any credit here :P

**Comment by ineu** [comment]
Thanks guys, it fixed things for me. Looking forward for 1.7.1 :)

**Comment by jjungnickel** [comment]
I just did a fresh install of 1.7 on EC2 and encountered a similar error. Pushing worked, the apps started just fine, but /deis/services/<app> in etcd was always empty.

Downgrading the publisher to 1.6.1 solved this, too.

**Comment by scottrobertson** [comment]
^ @bacongobbler that disproves my theory that it was Digital Oceans fault :P

**Comment by sstarcher** [comment]
I will second I had the same problem on AWS EC2 and the publisher downgrade worked.

**Comment by bacongobbler** [comment]
The correct solution is to [append .service](https://github.com/deis/deis/issues/2498#issuecomment-110592369) to the v1.7 units in ~/.deis/units, then uninstall and then re-install publisher. For verbosity:

```
# optional: for those who set publisher's image to v1.6.1
deisctl config publisher rm image
for fn in ~/.deis/units/* ; do mv $fn{,.service} ; done
deisctl uninstall publisher
deisctl install publisher
deisctl start publisher
```

That should get publisher working again.

**Comment by ineu** [comment]
@bacongobbler There are other files in ~/.deis/units without extension that differ from 1.6.0 version. Mostly because of ubuntu->alpine replacement, so not that important, but still it's not only publisher which needs to be reinstalled.

**Comment by bacongobbler** [comment]
I'm aware of that. I'm just demonstrating the fix for publisher. We should have a v1.7.1 out by EOD anyways so this will all be moot in a few hours.

**Comment by bacongobbler** [comment]
v1.7.1 has been released. Be sure to use the new version of `deisctl` as that should resolve the root issue here. For users like @scottrobertson who manually set publisher's image to v1.6.1, you'll have to run `deisctl config publisher rm image` to clear this setting and follow the upgrade documentation as normal.

**Comment by scottrobertson** [comment]
Thank you @bacongobbler, that worked perfectly.
