### ISSUE TITLE
Use flocker to replace Ceph for database & builder & ...

### ISSUE THREAD

**Issue by nathansamson** [deis/deis#3920]
https://github.com/ClusterHQ/flocker

> Flocker is an open-source Container Data Volume Manager for your Dockerized applications.
> By providing tools for data migrations, Flocker gives ops teams the tools they need to run containerized stateful services like databases in production.
> Unlike a Docker data volume which is tied to a single server, a Flocker data volume, called a dataset, is portable and can be used with any container, no matter where that container is running.
> Flocker manages Docker containers and data volumes together. When you use Flocker to manage your stateful microservice, your volumes will follow your containers when they move between different hosts in your cluster.
> You can also use Flocker to manage only your volumes, while continuing to manage your containers however you choose.

**Comment by bacongobbler** [comment]
It's a cool thought, but I think that's a backwards-incompatible change since we wouldn't be able to migrate data over from Ceph to Flocker. I'm concerned about the pain point for administrators would switch from "how do I manage Ceph" to "how do I manage ZFS", so it feels like we'd be migrating to another system which users need to be knowledgeable about vs. a simple turnkey solution.

From what I've been hearing on these issues, we may want to stick with documenting how we can connect to Amazon's services like S3/RDS for stateful services like the database/logger/registry for now, but maybe in a future version where we feel like breaking things, this could be a solution. Relying on a single vendor isn't necessarily a good thing, but they'll probably be keeping these services around for a while. :confused:

**Comment by mboersma** [comment]
I think documenting external state as in #3947 is the way to go for now.
