### ISSUE TITLE
Possible to pass custom docker flags to Deis app?

### ISSUE THREAD

**Issue by olalonde** [deis/deis#4012]
I'd like to install https://github.com/drone/drone/ as a Deis app but it requires access to the docker daemon. One solution would be to mount a socket from the host as a volume and I was therefore wondering if Deis supported something like this (e.g. http://progrium.viewdocs.io/dokku/docker-options).

**Comment by bacongobbler** [comment]
As discussed on IRC, giving apps access to the host's docker daemon opens up an attacker's ability to ruin your day simply by killing all containers running on that host, or worse yet running arbitrary commands inside your other containers. We do this to allow users who wish to run Deis as a hosting platform make this possible without exposing too much of the underlying software layers involved.

The better solution to this problem is to treat the daemon like a [backing service](http://docs.deis.io/en/latest/using_deis/config-application/#attach-to-backing-services), which drone supports by using `deis config:set DOCKER_HOST=tcp://192.168.0.1:2357`. Flags that make sense like `-m` and `-c` are exposed through commands like `deis limits:set`, but we do this in a proper manner to sanitize input from the user.

**Comment by olalonde** [comment]
I ended up writing this fleet service which exposes the docker socket over TCP and connect to it from the drone app. It assumes that the port is not publicly accessible and will probably break when Deis starts preventing Deis app from connecting to the host.

```
[Unit]
Description=Docker reverse proxy
Requires=docker.socket
After=docker.socket

# Make sure the port 2376 is not accessible from outside your
# internal network. The connection to docker is not authenticated.
[Service]
ExecStartPre=/bin/sh -c "docker history olalond3/docker-reverse-proxy >/dev/null || docker pull olalond3/docker-reverse-proxy"
ExecStart=/bin/bash -c "\
  docker run \
    --name docker-reverse-proxy \
    -h %H \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -p 2376:2375 \
    olalond3/docker-reverse-proxy; \
"

[Install]
WantedBy=multi-user.target

[X-Fleet]
Global=true%
```

```
FROM gliderlabs/alpine

RUN apk add --update-cache \
  socat

CMD socat TCP-LISTEN:2375,reuseaddr,fork UNIX-CLIENT:/var/run/docker.sock 
```

I understand that this kind of feature is not likely to be supported for deis users but wouldn't it be possible to make it available to deis operators? Maybe something like `deisctl config app/drone dockerFlags="-v /var/run/docker.sock"`?

**Comment by carmstrong** [comment]
> I understand that this kind of feature is not likely to be supported for deis users but wouldn't it be possible to make it available to deis operators? Maybe something like deisctl config app/drone dockerFlags="-v /var/run/docker.sock"?

We typically recommend that people build a custom controller component if they wish to pass arbitrary flags to the Docker daemon, but I could see how it'd be useful to be able to specify additional flags to be used for *all* apps. We don't really have an etcd keyspace convention for specifying additional parameters per application.
