### ISSUE TITLE
Wrong path to link deisctl into $PWD

### ISSUE THREAD

**Issue by woopstar** [deis/deis#4065]
Deisctl is installing by default into ```/opt/bin```

The docs on https://github.com/deis/deis/blob/master/docs/installing_deis/install-deisctl.rst wants you to run:

```sudo ln -fs $PWD/deisctl /usr/local/bin/deisctl```

Should be changed into:

```sudo ln -fs $PWD/deisctl /opt/bin/deisctl```

**Comment by mboersma** [comment]
The `install.sh` script will install `deisctl` to /opt/bin only if it detects it's running on CoreOS. (On CoreOS, most locations are read-only, but /opt/bin is writeable.) The instructions about linking are only to help ensure that `deisctl` is found on your search $PATH in the more common case where you're installing it yourself and running it on your workstation, which isn't generally necessary for CoreOS since `/opt/bin/deisctl` should already be found.

**Comment by woopstar** [comment]
Ah okay. Maybe we should just make a note on that in the docs and close the issue?

**Comment by bacongobbler** [comment]
deisctl is going away in Deis v2 and I don't think we will be able to get to this for the LTS release so I'm going to go ahead and close this. Thank you for the report though!
