### ISSUE TITLE
aws elb instances ip addresses mismatch

### ISSUE THREAD

**Issue by szymonpk** [deis/deis#4100]
I'm not sure where the issue origin is. I'm not very familiar with cloudformation but from reading provided template and doc it seems to be fine.

But from the beginning I deploy deis on ec2 via provided scripts. Everything is fine, I'm getting list of instances with ELB address:

```
...
Instances are available:
i-b35a5660	<ip1>	m4.large	us-east-1c	running
i-d6ce8e7e	<ip2>	m4.large	us-east-1b	running
i-489203e4	<ip3>	m4.large	us-east-1d	running
Using ELB <elb id> at <elb address>
Your Deis cluster has been successfully deployed to AWS CloudFormation and is started.
Please continue to follow the instructions in the documentation.
Enabling proxy protocol
1
```
Before installation I do quick dig query, strangely I'm getting list o 3 ips, which AREN'T my instances from previous message, I don't even have such instances in my AWS account. Reponse should be empty list, because these instances aren't passing health checks yet (no platform installed!, elb shows 0 operational instances).

```
dig <elb address> +short
<ip4>
<ip5>
<ip6>
```
So I continue install platform, instances are operational now (elb panel shows 3 of 3 up) but dig still shows ips4-6 which AREN'T mine. If I add one more instances dns query shows this one added properly + three instances which I don't know where they come from.

Does anyone have any idea how to handle this? It isn't issue with dns caching, I'm getting same dns responses if query directly amazon's dns servers and additional instances are showing properly.

**Comment by Blystad** [comment]
I think you're misunderstanding what ELB is.

ELB - Elastic Load Balancer, sits in front of your instances, and proxys incoming data to instances:

![ELB architecture](https://media.amazonwebservices.com/blog/2014/elb_instances_1.png)

You will configure your DNS to point at the load balancer, and the load balancer will distribute incoming requests to your instances by round robin (e.g. first request goes to instance A, second request to instance B, third request to instance C, forth request to instance A, and so on so forth). 

You see multiple IP addresses because there are multiple ELB instances running, both to distribute the load among multiple ELBs, and to handle failure.

If you need to SSH into the instances, (maintenance, introspection, or similar) you do so directly, and not via the load balancer.

**Comment by szymonpk** [comment]
Yup got it now, I've came to same conclusion, just needed some reading :/

Thx @Blystad!
