### ISSUE TITLE
can't run created linodes

### ISSUE THREAD

**Issue by molisoft** [deis/deis#4166]
Hi,
I created 3 linodes by:
```
./provision-linode-cluster.py --api-key=LINODE_API_KEY provision
```
And successful!
But can't run..
result:
```
Cannot Direct Disk boot a disk with no MBR: Kernel not found
```
I don't know why.. 
You can try it.

Thank you ..

**Comment by croemmich** [comment]
Is your account hypervisor set to KVM?

**Comment by molisoft** [comment]
@croemmich  yes, is KVM

**Comment by molisoft** [comment]
@croemmich
I got it.
Run this command and result:
```
$HOME/coreos-install -d /dev/sdb -C  beta -V 647.2.0 -c $HOME/cloud-config.yaml -t /dev/shm
/root/coreos-install: coreos-cloudinit not found. Could not validate config. Continuing...
/root/coreos-install: Image URL unavailable: http://beta.release.core-os.net/amd64-usr/647.2.0/coreos_production_image.bin.bz2
```
This coreos version not found...
Need to change the version to 717.3.0
----
provision-linode-cluster.py
```
    provision_parser.add_argument('--coreos-version', required=False, default='717.3.0', dest='coreos_version',
                                  help='CoreOS version number to install')
    provision_parser.add_argument('--coreos-channel', required=False, default='stable', dest='coreos_channel',
                                  help='CoreOS channel to install from')
```

**Comment by carmstrong** [comment]
@molisoft That CoreOS version will actually cause problems - it comes with Docker 1.6.2, which has a known issue relating to image pulls. We're waiting for Docker 1.7.1 to make its way to the CoreOS stable channel.

If Linode only allows users to use the latest CoreOS image, we're sometimes going to run into issues on that platform.

**Comment by croemmich** [comment]
I'll give this a look. You should be able run any version of coreos, as this is booting as a direct disk instance.

**Comment by croemmich** [comment]
@molisoft Your issue occurred because 647.2.0 only exists in the stable channel. The script was originally set up to install 695.2.0 from the beta channel, as I had a few networking issue with 647.2.0, however the script got changed to 647.2.0 in #3992.

I'm currently running 717.1.0 in production with minimal issues.

With the current script you have, you should be able to add the following arguments to install 647.2.0:
--coreos-version=647.2.0 --coreos-channel=stable

However, I've never tested 647.2.0 on Linode. Here be dragons...

**Comment by molisoft** [comment]
@croemmich  thank you.
