### ISSUE TITLE
`deisctl journal controller` matches both deis-controller and kube-controller-manager

### ISSUE THREAD

**Issue by bacongobbler** [deis/deis#4201]
When displayed, it first shows the controller logs. After a CTRL+C with kubernetes installed, it shows the replication controller's logs. This should only display the controller's logs.

**Comment by krancour** [comment]
I think this is a combination of two problems.

Problem 1: You can type a partial component name and get back logs.  I'm still poking around in the code, but obviously somewhere along the line, a unit is considered a match for the target if the target is a substring of or regex match for the unit name.

Problem 2: You're allowed to specify multiple targets for the `journal` subcommand.  This seems to me that it's, in part, copy/paste error.  Someone probably modeled the command and function signature after existing commands and functions that legitimately can take multiple targets (e.g. `start`).  After all, what does it mean to look at the logs for _two or more_ targets?

With the two problems combined, "controller" is a match for two units, and you're shown the logs for one, and then the other.

IMO, both of these should be fixed so that you can view logs for one target at a time and the name of the target needs to be fully articulated-- no fuzzy matches, else it gets us into trouble as it did here.

Does this seem reasonable?

**Comment by technosophos** [comment]
I believe that both (1) and (2) were intentional. I routinely use `deisctl journal router` to quickly look at all the router journals.

How about this?

1. Look for an exact match (`deis-controller` matches only `deis-controller`)
2. If no exact match, look for a prefix match (`deis-router` matches `deis-router*`).
3. If no prefix match, prepend `deis-` and look for a prefix match (`controller` matches `deis-controller*`)
4. If no match, error.

**Comment by technosophos** [comment]
Offline, @krancour suggested explicit wildcards, which would be even better.

**Comment by bacongobbler** [comment]
+1 for explicit wildcards

**Comment by krancour** [comment]
I'm backing off the wildcards idea.  It's technically a breaking change because people (or scripts) that were accustomed to something like `deisctl journal router` showing them the logs for _all_ routers would have to adapt to new syntax like `deisctl journal router*`

I am liking @technosophos' previous proposal better.  I think I'd refine it a little as follows:

1.  Canonicalize the target component string: if it does _not_ begin with "deis-", prefix it with "deis-"
1.b  Further canonicalize by downcasing?  All Deis' own components exclusively use lowercase.
2.  Look for an exact match for the canonicalized target string; if found, match that _one_ component.  This would solve the issue @bacongobbler  reported.
3.  Look for a match/matches _beginning_ with the canonicalized target string.

This would have the following minor impact:

Today, you can see all `deis-router@#` logs (for instance) with `deisctl journal outer` (no "r").  This altered scheme would invalidate that, but @jchauncey has pointed out offline that it's unlikely anyone depends on that (it's certainly not documented).  Typos happen, so there _could_ be scripts in existence somewhere that take advantage of that weird, undocumented  "feature," but since they'd be extreme outliers, it doesn't seem like motivation to not fix the problem @bacongobbler is reporting.

**Comment by technosophos** [comment]
I'm good with @krancour 's proposal above.

**Comment by jchauncey** [comment]
Same
