### ISSUE TITLE
run command "play evolutions --%prod" [ play framework 1.3.1]

### ISSUE THREAD

**Issue by anissrelicum** [deis/deis#4386]
I'm trying  to run this command `play evolutions --%prod` by calling ` deis run "play evolutions --%prod" -a project_name `, but it doesn't work, I get this error  `Unrecognized option: --project_name_v60.run.66rod` apparently deis replace `%p` by `project_name_v60.run.66`. i'm asking how to execute this command

**Comment by aj-may** [comment]
try `deis run -a project_name -- play evolutions --%prod`

**Comment by anissrelicum** [comment]
same error

**Comment by bacongobbler** [comment]
Sounds like systemd is interpreting %p, since that's what is [being used](https://github.com/deis/deis/blob/master/controller/scheduler/fleet.py#L383-L389).

Try using [systemd-escape](http://www.freedesktop.org/software/systemd/man/systemd-escape.html) to generate the correct string for now, but we should probably integrate with that in the future to prevent this from happening.

**Comment by bacongobbler** [comment]
ping @anissrelicum, did this work for you? you could also try `--%%prod` to see if that works around the issue.

**Comment by anissrelicum** [comment]
Thanks @bacongobbler  it works

**Comment by bacongobbler** [comment]
Okay. We should probably substitute all percent signs with an additional percent so systemd won't interpret it into a flag.

**Comment by bacongobbler** [comment]
We won't be able to get to this for the LTS release, and since kubernetes does not rely on systemd for commands I'm going to close this, but thank you very much for posting this :)
