### ISSUE TITLE
Router and application tagging

### ISSUE THREAD

**Issue by mariusmarais** [deis/deis#4441]
We're considering running a Deis cluster to host a bunch of services in geographically-separated regions.  This is mostly for data-location-compliance, but also plays a major role in application speed.

While the tags will allow us to schedule apps onto specific hosts (grouped by region), everything still travels through the same router, which negates the speed and bring the compliance into question.

Would it be possible to run multiple routers with tags, which can then only route apps with the appropriate tags?

For instance: 
www.example.com -> uk.deis.example.com -> UK router -> UK hosts, and 
www.example.net -> us.deis.example.com -> US router -> US hosts

The alternative seems to be running multiple clusters, but then we're looking at 4x everything and additional client-side complexity.  Ideally an app-level config should set the region and everything flows from there.

(For clarity: IP-level restrictions wouldn't help here -- all apps are still publicly accessible, but we wouldn't pass data through a region unless the user or host is actually there.)

**Comment by krancour** [comment]
Ok.  This is an advanced question!

It sounds like what you're asking for is predicated on the notion of running a deis cluster that spans multiple regions.  My initial reaction was that the higher latency between nodes in two different regions is likely to cause some grief with etcd and result in an unstable cluster, but it looks like you can work around this by following some of the advice here:

https://coreos.com/etcd/docs/latest/tuning.html

You'd also have to peer the networks in the two regions so nodes can still communicate with one another using private IPs.  I you were using Amazon and VPCs, for example, this documentation would be a good starting point:

http://docs.aws.amazon.com/AmazonVPC/latest/UserGuide/vpc-peering.html

As long as you have those concerns addressed first, here's how I would proceed from there:

In each of your two regions, tag a small, fixed number of nodes appropriately such that they are eligible to host `deis-router`-- let's say three per region, for instance.  That gives you a total of six machines that could host a router.  Scale your routers up to six and you'll be guaranteed three running in each region since no machine that _can_ host a router will host more than one.

From there you can use DNS to simply route traffic for the two region-specific domains to a load balancer that's in front of the three routers in one region or the load balancer that's in front of the other three routers in the other region.

All that being said.  I wouldn't necessarily recommend this.

> The alternative seems to be running multiple clusters, but then we're looking at 4x everything and additional client-side complexity.

I'm not sure where the 4x comes from.  Regardless of whether you run one cluster that spans two regions or just run two clusters, you'd end up needing a certain amount of capacity in each region and you'd incur the associated costs.  I don't see any specific cost savings by having it be one cluster.  Again, if using AWS, for example, you'd also incur additional charges for the VPC peering.

One definite disadvantage of the architecture you're shooting for is that you'd have one giant cluster that would take your operations down in two geographic regions if it fails, as opposed to having two separate clusters that would fail independently of one another.

Last, but not least, we've never tried this.  I couldn't vouch for how well things like Ceph will work with the additional latency factored in.

**Comment by mariusmarais** [comment]
Thanks for the detailed answer.  The 4x comes from four regions that we operate in, 3 in AWS and 1 bare metal.

This looks like a fun project, but given your answer I'm inclined to agree that it probably isn't worth the trouble or risk.

My next question would then be how to have the `deis` client-side tool auto-discover between multiple clusters, but I'll search a bit more first :)

**Comment by krancour** [comment]
The client requires you to authenticate to the controller, so that limits the client to using one cluster as a time.  To switch, you log out of one and into the next.  That's definitely inconvenient if you want to push the same app to four clusters.  This is not to mention you'd also have to juggle multiple git remotes for the pushes.

What I'd recommend is using some CI server like Jenkins to accomplish that instead.  The deployment workfliw becomes one where you merge into some branch that Jenkins watches to kick off a deploy.  That could optionally trigger a test suite first and then a chain of jobs, where each one deploys the app to a specific region by logging in to the correct cluster and pushing to the correct remote.  You get a lot of other benefits from that workflow as well, including notifications when deployments are triggered, completed, or failed.

**Comment by jgmize** [comment]
> The client requires you to authenticate to the controller, so that limits the client to using one cluster as a time. To switch, you log out of one and into the next. That's definitely inconvenient if you want to push the same app to four clusters.

Actually this is no longer true: the deis client now supports [multiple profiles](http://docs.deis.io/en/latest/using_deis/install-client/#multiple-profile-support) and you can switch between them with the `DEIS_PROFILE` environment variable.

> What I'd recommend is using some CI server like Jenkins to accomplish that instead. The deployment workflow becomes one where you merge into some branch that Jenkins watches to kick off a deploy. That could optionally trigger a test suite first and then a chain of jobs, where each one deploys the app to a specific region by logging in to the correct cluster and pushing to the correct remote. You get a lot of other benefits from that workflow as well, including notifications when deployments are triggered, completed, or failed.

I strongly agree with @krancour's suggestion of using a CI server like Jenkins to manage deployment pipelines, but I would further recommend building the docker images on the CI server and using [deis pull](http://docs.deis.io/en/latest/using_deis/using-docker-images/#deploy-the-application) deployments (until [deis push](https://github.com/deis/deis/issues/2680) is available), instead of using [git push](http://docs.deis.io/en/latest/using_deis/using-dockerfiles/#push-to-deploy) to ensure consistency between clusters.

**Comment by mariusmarais** [comment]
We're already using Jenkins to manage deploys for our shared systems (specifically for consistency and speed), but not for deploys that are region-specific. Setting the `DEIS_PROFILE` in a tiny wrapper should be very easy then.

I agree that anything which runs across regions should be as consistent as possible, so extending the Jenkins setup makes sense here.  Could maybe add some tooling to easily create Jenkins jobs for new projects so that everything goes through there.

Thanks.
