### ISSUE TITLE
Deis Logs in K8S

### ISSUE THREAD

**Issue by technosophos** [deis/deis#4468]
Kubernetes provides a number of useful logging abstractions. We need to determine the best way to use these services. We need to determine if other services (like logspout) are still necessary.

**Comment by krancour** [comment]
@technosophos I've been knee deep in logging as of late, so I'd like to help out with this.  My initial thoughts are that logspout won't be needed (seems k8s likes fluentd and has nice support for it), but that logger _might_ still serve a useful function for anyone who simply doesn't want or need to ship their logs to somewhere outside the cluster, but would like to still aggregate them somewhere within the cluster and access them with `deis logs`.

**Comment by bacongobbler** [comment]
fluentd performs the same task as what logspout does differently, though the end result is the same (logs need to get shipped to a syslog server). The trick is getting it installed on every node when global scheduling affinity is not supported yet on kubernetes.

I agree about logger still being a required component OOTB. There are blog posts on how some users have set up fluentd with elasticsearch but we should see if we can still ship syslog messages to a logger.

**Comment by krancour** [comment]
How does k8s schedule its own system components and "add-ons" to every node?  Obviously, that's a concern whether we stick with logspout or switch to fluentd.  k8s' own logging docs talk about clusters created with support for cluster-level logging, but they never actually show you how that's enabled.  (Or at least I'm not seeing it.)

**Comment by bacongobbler** [comment]
> How does k8s schedule its own system components and "add-ons" to every node?

It's part of the [bootstrap process](https://github.com/kubernetes/kubernetes/tree/master/cluster/saltbase/salt), so that's not something we can plug into very easily since we're targeting both existing and new clusters.

**Comment by aledbf** [comment]
@krancour you are right, the k8s docs about cluster-level logging is not clear. Here's a post with more details 
https://github.com/kubernetes/kubernetes/blob/master/cluster/saltbase/salt/fluentd-es/fluentd-es.yaml
One advantage of switching to fluentd is that is possible to provide the same functionality (forward to an external syslog server) and add new ones like forward logs to riemann https://github.com/wkf/fluent-plugin-riemann (I'm sure @jchauncey could be interested in this)

**Comment by aledbf** [comment]
> It's part of the bootstrap process

Is possible to just run `kubeletet create -f`. Is possible to run that after the k8s cluster is created

**Comment by jchauncey** [comment]
+1 on fluentd

**Comment by bacongobbler** [comment]
> Is possible to just run `kubeletet create -f`. Is possible to run that after the k8s cluster is created

Well, yes and no. To explain how this works (for others who may not know), the salt bootstrap process installs the manifest to [/etc/kubernetes/manifests/fluentd-es.yaml](https://github.com/kubernetes/kubernetes/blob/master/cluster/saltbase/salt/fluentd-es/init.sls#L1-L3) on every node, which the kubelet will then read on boot and start that pod on every node that has that manifest file on-disk. We cannot run `kubelet create -f` on a node that we do not have SSH access to, such as the case with users who may want to run Deis on [Google Container Engine](https://cloud.google.com/container-engine/). You only get access to the kubectl API so that's what we're restricted to. I recall somewhere on the k8s issue list that someone has found a workaround using port affinity, so that will likely be the workaround for Deis agents.

**Comment by bacongobbler** [comment]
this might also be a good time to investigate running back to rsyslog rather than deis/logger. See https://github.com/deis/deis/pull/4502#issuecomment-142321849

**Comment by bacongobbler** [comment]
see https://github.com/deis/logger.
