### ISSUE TITLE
How can Deis do venerables like Drupal, Wordpress or new comers like Ghost or Discourse? 

### ISSUE THREAD

**Issue by niccolox** [deis/deis#448]
I know this is the 12 Factor App noob question but I'd like to seriously discuss the issue of hosting applications like Drupal, also Wordpress (shudder), Ghost and Discourse on Deis

I see from your docs that stateful apps are not 12 Factor Apps and that's a sin in PaaS land

but I do also notice; 

that the Heroku founder partly funded Pantheon is running on containers and talking up Docker and co
http://www.crunchbase.com/person/orion-henry
http://2013.badcamp.net/sessions/drupal-and-cloud-containers
(video not online, but there are other resources by Pantheon founders)

Having used Pantheon in a day job I also see at least some of the 12 Factor App signs, not all, but some. Under the hood, its a different story
"The most unique technology in the Pantheon Platform is the Content Base — the data utilities that the 12 Factor App manifesto calls Backing Services. No website can live without them."
https://www.getpantheon.com/blog/how-pantheon-content-base-works

that the Drupal trademark owner, project founder's company Acquia is sponsoring talks on LXC, Docker, Vagrant at the Drupal convention
https://prague2013.drupal.org/session/automate-drupal-deployments-linux-containers-docker-and-vagrant
http://blog.ricardoamaro.com/content/drupalcon-presentation-linux-containers-vagrant-docker-great-feedback
https://github.com/ricardoamaro/drupal-lxc-vagrant-docker
https://github.com/ricardoamaro/docker-drupal

that the Docker index has Drupal images available
https://index.docker.io/search?q=drupal

and that the Drupal infrastructure testing people are excited about Docker and containers
https://groups.drupal.org/node/388908#comment-1001333

so, are content management systems, especially the cranky old PhP content management systems an impossible fit? or just a weird one?

an interesting article on Wordpress slumlording
http://developer.rackspace.com/blog/slumlord-hosting-with-docker.html

so, how do we make Deis work Drupal and all the old and new stateful CMS?

How low, in the 12 Factor App compromises can Deis go?

Drupal people seem pretty excited about Docker (and hopefully soon Deis), why isn't it mutual?
https://drupal.org/node/2169095

what are the work arounds?

**Comment by krancour** [comment]
I know this issue was closed quite some time ago, but I have recently migrated 8 separate non-production (staging) Drupal sites to Deis, so I wanted to assure the OP that this _can_ be done.

I feel obligated to say that I have no love whatsoever for either Drupal or WordPress.  From an ops perspective, they were simply _not_ designed to scale horizontally, and that makes them painful to deal with.  The biggest problem I have encountered is that developers (working locally with Drupal, WordPress or other) easily lose site of the fact that production is a _distributed_ environment and depending on local disk for the storage of user-uploaded files (e.g. images) and other similar concerns is tantamount to a cardinal sin in a distributed environment.  And that's the key-- Drupal and WordPress aren't just ill-fitted for containerization, Docker, Deis, etc.  They are ill-fitted for _any_ distributed environment... unless you know what you're doing and hack on your sites quite a bit to make it tenable-- which is what we did with our 8 sites long before Deis was on the scene, simply so that we could scale them horizontally in AWS.

To make this tenable-- we first got all developers working on Drupal sites to understand that production is distributed and educated them on a few caveats that are implied by that.  First: Modules must not be installed via Drupal's admin panel.  In a distributed environment, the server that _serves_ the request to install a module will _have_ that module, but all other servers will not!  We required that any modules they wished to deploy were linked into each site's repository as a git submodule.  Then they can enable and administer the modules as usual using Drupal's admin panel.  Second, user uploaded content shouldn't be stored locally in a "files" directory.  This is harder, but there _are_ modules and libraries available that will allow you to swap local disks for S3 for _all_ user-uploaded content.  It takes some effort to set them up, from what I understand, and performance-wise, it's a bit slower.  The slowness is mainly observable when an administrator or content author browses files (for instance, to select one to embed in a page), because they are actually browsing a bucket, which may have a lot of content in it.  In practice, it seems some of the pain can be taken out of this be making sure you are using the most recent versions of AWS libraries for Drupal, since many performance issues have been tackled in there over time, and impose a sensible "directory" structure on your S3 buckets so that when you browse the bucket via some Drupal module, it's not requesting metadata for hundreds or thousands of files.

Having taken all these steps quite some time ago, these sites moved to Deis with no trouble whatsoever.  So... it's possible.

**Comment by gabrtv** [comment]
@krancour thanks for taking the time to write all this up.  We get asked this all the time.  I have a strong suspicion other folks (not just those using Deis!) will benefit from this knowledge.  If you have time/inclination to reformat this into a blog post, we'd love to cross-post it on our blog.

**Comment by niccolox** [comment]
thanks for this

I saw a talk by a Stanford (Puppet expert) developer at the badcamp in San Francisco earlier this year where they talked about a Docker focussed Drupal paas similar to what @krancour describes

the used Terrafirma to create vms on which they install Docker and Drupal on AWS, plus S3 for file storage and RDS for mysql databases

the Drupal use the fairly well developed S3 Drupal contrib module for file management and the standard db connections work with RDS

I think the Dockerfile and Puppet are both used to deploy the Drupal site on creation time

more details here, not sure if this is current information
https://itunconference.stanford.edu/containerize-all-things-docker-ftw

stepping back from this, Pantheon have a multi-million dollar business running Drupal AND Wordpress using containers on Fedora .. so, it can work 

but, yes, Drupal and Wordpress, are PHP based, are historical, and relatively ancient, they are like the shark and the crocodile, living dinosaurs

**Comment by skyred** [comment]
Application developers love a centralized file management, while system admins love things to be distributed. I think the missing piece is a distributed file system. If there is an open sourced and easy to use DFS, then to me, I think the above challenge will be solved.

**Comment by bacongobbler** [comment]
@skyred we now have a distributed file store deployed in deis which some users are [using outside of deis](http://ian.blenke.com/blog/2014/11/05/self-standing-ceph-slash-deis-store-docker-containers/) for their own clusters. See https://github.com/deis/deis/tree/master/store for more info, or the official documentation at https://docs.deis.io on how to manage this component. :)
