### ISSUE TITLE
Graceful Shutdown does not remove from Discovery URL

### ISSUE THREAD

**Issue by sstarcher** [deis/deis#4545]
The graceful shutdown script will not remove nodes from the Discovery URL.  The effect of this is that the new node that comes up with be a peer always.  So if one of the nodes that is contributing to the quorum goes down and gets replaced the quorum will stay -1.  If you attempt to replace all of your initial nodes or even most it is likely you would lose the cluster.

**Comment by aj-may** [comment]
I also ran into this issue.  I can submit a PR once I test my fix.

**Comment by iancoffey** [comment]
Problem here will be execution order - just adding the proper etcd and discovery url handing to the script wont suffice since the unit will not function unless it can stop without the deis-store-* components being present and active.

Its a little tricky situation, I have a PR forthcoming to address it.

**Comment by aj-may** [comment]
@iancoffey sounds good.  I'll let you address it.  Feel free to tag me on the PR and I'll take a look.

**Comment by iancoffey** [comment]
@aj-may Indeed, your input on the PR would be appreciated https://github.com/deis/deis/pull/4554
