### ISSUE TITLE
deisctl dock has trouble attaching to distributed containers, i.e., "@" units

### ISSUE THREAD

**Issue by jackfrancis** [deis/deis#4558]
For example:

```
$ deisctl list | grep 'router'
deis-router@1.service	ba4076c4.../10.21.1.208	loaded	active	running
deis-router@2.service	f1657db5.../10.21.2.151	loaded	active	running
deis-router@3.service	0ed42297.../10.21.1.210	loaded	active	running
$ deisctl dock router@1
Executing 'docker exec -it deis-router@1 sh' on 10.21.1.208
FATA[0000] Error response from daemon: No such container: deis-router@1
```

**Comment by krancour** [comment]
This is because the container names for such components lack the @#.  So all n of router@# units start a container that's just named "router" and deisctl isn't smart enough to know that's going on.  The best solution, if docker allows it would be to make the container names always match the unit names... i.e. include the @#... but docker may not like special characters in container names.  Nevertheless, it's worth attempting before looking for a more compkex solution wherein deisctl needs specific logic for handling components with @# in their names.

**Comment by krancour** [comment]
Just tried.  Docker doesn't like @'s in container names.  I suppose the next best thing is to make deisctl smart enough to strip out the @# at the end of a container name before trying to exec into it.

**Comment by jackfrancis** [comment]
We could add string substitution pattern logic into deisctl, something like:

- when a new distributed unit's container is created, it gets a name of `router-node-1` (instead using a common name `router` that all distributed router nodes will share on their distinct scheduled hosts)
- deisctl dock will know to translate a target name of `router@1` to `router-node-1` in order to properly exec into it

Of course, we wouldn't want to implement such an approach unless we'd be willing to do it for all distributed unit containers, and it looks like currently only router and registry share this `@` substring pattern (logspout and publisher, for example, which are also distributed components, don't seem to get an ordinal representation, at least in `deisctl list` output).

Also, any existing code in deisctl that references router container names by their current, common shorthand name (e.g., just `router`) will need to be updated as well. So, perhaps this isn't an easy one.

**Comment by krancour** [comment]
The string substitution strategy would work, but making deisctl know it has to perform that substitution isn't any better than making it know it needs to drop the @# before execing into the container.  The difference between the two, however, is that changing how the containers are named is a more sweeping change that we should try to avoid as long as the simpler alternative that's narrower in scope exists.

> logspout and publisher, for example, which are also distributed components, don't seem to get an ordinal representation

There's a reason for that.  Those are global units.  They simply run one and only one everywhere that fleet metadata permits them to.  Contrast that with something like router where we are in _control_ of how many we scale to.  Not simply requiring one and only one calls for a different approach in ensuring no two of such a component ever run on a single host.

Also, as you've observed, the global nature of units like logspout or publisher makes the idea of `deisctl dock logspout@1` impossible.  There's no way in fleet to enumerate global units.  I wouldn't worry about this.  `deisctl dock` is a convenience feature in the first place.  It's still possible to get into any container by ssh'ing to the right machine and then using `nse` or `docker exec`.

> Also, any existing code in deisctl that references router container names by their current, common shorthand name (e.g., just router) will need to be updated as well. So, perhaps this isn't an easy one.

I know first hand that the code used for resolving component names is a little complex.  I don't believe, however, that it needs to be touched at all for this.

The key is remembering what `deisctl dock <component>` actually does.  It's resolving the component name (which is a little complex), figuring out what host that component lives on, ssh'ing to there, then doing a `docker exec <container name>` on the host.  It's _only_ the `<container name>` in this last part that needs to change.  We probably don't need more than a couple line of code to do this.  Something like the following pseudocode:

```
declare containerName
if componentName includes "@":
  containerName = componentName.substring(0, componentName.indexOf("@")
else:
  containerName = componentName
```

**Comment by jackfrancis** [comment]
Looks like we're comprehensively teasing this out. ;) I'd like to add, because it's related, that in my administrative habits, especially as a dev using deis in a quasi-evaluative manner, that I've been manually logging on to the EC2 instances that comprise the deis cluster and `docker ps`'ing them, to see what components live where exactly, and then manually `docker exec -it <container> /bin/bash`'ing in to poke around. I wouldn't be surprised if this isn't an expected pattern of behavior for other evaluators as a way of determining "what is exactly going on here?" and "is this a useful production abstraction that I can use?". As such, being able to avoid the manual logging on and looking for container instances would be great. Are there any downsides to simply presenting the host resource as part of a `deisctl list`? It sounds like from your above description that `deisctl dock` isn't necessarily something we want to expose to every possible containerized component in a deis cluster, but we should expect that at some point we'll want to be able to debug every possible containerized component, and providing easy exposure to where to find those containers would be a win in that direction.

**Comment by krancour** [comment]
There isn't anything at all today that stops an operator from getting into any of the containerized components.  Currently, it's just (very slightly) more difficult for components with global units or units whose names include @#.  We can easily fix the latter because an operator _could_ say `deisctl dock router@2`, for instance and that is very specific about which host to connect to and which container to exec into.  Something like `deisctl dock logspout` on the other hand doesn't make much sense.  It's not specific enough since that component lives on every host and its units also have the same name on every host (a consequence of being global units).  Like I said... there isn't anything that stops someone from still getting into any given logspout container, for instance.  They just have to ssh to the host they want first.  I think that's a trivial enough complication that we don't need to fret over it.

Keep in mind, 100% of this will change in v2.

**Comment by bacongobbler** [comment]
deisctl is going away in Deis v2 and I don't think we will be able to get to this for the LTS release so I'm going to go ahead and close this. Thank you for the report though!
