### ISSUE TITLE
getting application logs out of containers

### ISSUE THREAD

**Issue by gred7** [deis/deis#4624]
I run apache in docker container on deis cluster. how can I get apache's access & error logs to my papertrail? 
i've already configured platform log drain, but i also need apache logs too.
thank you.

**Comment by bacongobbler** [comment]
@gred7 the easiest way would be to send the apache logs to /dev/stdout or /dev/stderr in the container as it's done with Heroku applications. That way we can ship those logs to the configured platform log drain. Will that work for you?

See: http://stackoverflow.com/a/32013582

**Comment by gred7** [comment]
nope, just tried - it doesn't work, sorry.
here's my dockerfile:

FROM quay.io/okfn/python2-apache:latest

COPY ${SETUP} ${APP_DIR}
COPY ${SETUP}/${APP_CONF} ${SUPERVISOR_DIR}/${APP_CONF}

RUN apt-get install -y --no-install-recommends \
    apache2 \
    apache2-mpm-worker \
    apache2-threaded-dev

# NOTE: I'm using the fairly new mod_wsgi-express
# https://pypi.python.org/pypi/mod_wsgi
# http://blog.dscpl.com.au/2015/04/introducing-modwsgi-express.html
RUN pip install mod_wsgi

#to get logs out of container
RUN ln -sf /dev/stdout /var/log/apache2/error.log
RUN ln -sf /dev/stdout /var/log/apache2/access.log
RUN apt-get autoremove -y

**Comment by krancour** [comment]
For lack of anything else to go on atm, I would suggest execing into one of the application containers after it's started and looking at `/var/log/apache2/error.log` and `/var/log/apache2/access.log` to assert they are the symlinks you expect them to be.

I'll try your dockerfile myself when I have a chance.

**Comment by krancour** [comment]
@gred7 I couldn't use your Dockerfile because the `FROM` isn't valid and the `COPY` instructions won't work since I don't have your source.

I did the best I could by putting together this trivial example that shows @bacongobbler's suggestion works.  (fwiw, `deis-router` uses that exact trick and it works there as well.)

My Dockerfile:

```
FROM alpine:3.2

RUN ln -sf /dev/stdout /my.log

ENTRYPOINT for i in $(seq 1 10); do echo $i >> /my.log; sleep 1; done
```

To run:

```
$ docker build -t log-demo .
$ docker run -it --rm log-demo
```

You will see that everything written to `/my.log` also goes to the container's `/dev/stdout`

The only other things that might explain your issue would be if the path to the symlinks doesn't match with where your apache is actually writing logs to _or_ if you actually have a platform-wide configuration issue with `dies-logspout` or `deis-logger`-- that, however, would be immediately evident because no logs from _any_ application or platform component would show up in your Papertrail at all.

**Comment by gred7** [comment]
I have found a better way.

**Comment by krancour** [comment]
@gred7 just to put a little more closure on this, @bacongobbler's suggestion and my example code might have been over-simplified.  Nginx and Apache seem to have a little trouble outputting logs to a device.  (A bug?)  Looking more carefully about how we do this in our own router, Nginx isn't writing directly to the log via symlink-- rather we fork two processes to `tail -f` access and error logs to `/dev/stdout`.  See here:

https://github.com/deis/deis/blob/master/router/cmd/boot/boot.go#L69-L70

That could also work for you, but if you're happy with the papertrail client, then that's cool too.
