### ISSUE TITLE
Cloud Config writing Deis units to /.deis

### ISSUE THREAD

**Issue by iancoffey** [deis/deis#4638]
On install via our contrib/ user-data, the deisctl cloud config unit installs unit files to the root filesystem at /.deis. These units serve no purpose there and shouldnt be written.

This might be due to $HOME not being set during the unit run. If run manually from a tty, units end up in the correct place (~/.deis).

**Comment by carmstrong** [comment]
We could solve this by adding `User=core` to the [installation unit](https://github.com/deis/deis/blob/567c10be7ac8e8b2f217a537f4a0e807c360e8a3/contrib/coreos/user-data.example#L72-L81), but I think that would fail because the Core user won't have permission to drop in the `deisctl` binary. 

We should fix this, but it may involve an update to the unit which performs the install and then changes permissions.

**Comment by carmstrong** [comment]
```
core@deis-01 ~ $ curl -sSL --retry 5 --retry-delay 2 http://deis.io/deisctl/install.sh | sh -s 1.11.1
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 2610k  100 2610k    0     0  2683k      0 --:--:-- --:--:-- --:--:-- 2742k
Creating directory /opt/bin
Verifying archive integrity... All good.
Uncompressing Deis Control Utility  100%  Extraction failed.
sh: line 32:  1183 Terminated              sh /tmp/$DEIS_INSTALLER $INSTALLER_OPTS
```

**Comment by bacongobbler** [comment]
This is not something we'll be able to get to for the LTS release (#4776), and provisioning Deis v2 is done through installing a vanilla kubernetes cluster so I'm going to go ahead and close this.
