### ISSUE TITLE
Ceph install

### ISSUE THREAD

**Issue by admin0a** [deis/deis#4726]
Hello

I have the following equipment:

6 servers containing the following drives: 2x1TB SATA and 10 x 6TB SATA disks

and 2 2x1TB SATA servers.

At the above-mentioned items of Cepha I would like to install. How to install Cepha on these items I'm talking about concepts, design.

Regards
Thank you very much

**Comment by bacongobbler** [comment]
@admin0a if you have dedicated hardware just for ceph, and not for Deis's control plane, I would take a look at the official ceph documentation at http://docs.ceph.com/docs/master/ so you can get the most juice from your servers. Deis deploys its components using Fleet and Docker, which will be different to manage compared to a pure Ceph cluster.

Are you looking to deploy Deis with a dedicated Ceph cluster on these servers, or just Ceph?

That's all being said, we have docs maintained by the community on how to install Deis on bare metal [here](http://docs.deis.io/en/latest/installing_deis/baremetal/) if you're interested :)

**Comment by Joshua-Anderson** [comment]
@admin0a Did @bacongobbler's reply answer your question? :smile_cat:

**Comment by Joshua-Anderson** [comment]
@admin0a Since this isn't specifically a deis issue, I'm going to close this.

If you are looking for help with ceph, the deis community does have a lot of ceph experience. Feel free to ask around our irc channel, #deis on freenode, or our [mailing list](https://groups.google.com/forum/#!forum/deis-users)
