### ISSUE TITLE
Deploying deis to multi AZ/region using cloudformation

### ISSUE THREAD

**Issue by gergelyke** [deis/deis#4769]
Hello,

is there an easy way to deploy deis in a multi-az fashion?

thanks,
Gergely

**Comment by krancour** [comment]
The AWS provisioning process already spreads your hosts across subnets in two AZs.  You also have the option of bringing your own VPC-- which is a better option because it would allow you to spread your hosts across subnets in as many AZs as you like in a given region.  Ideally, for production, you use at least three AZs.

**Comment by gergelyke** [comment]
Thanks!
