### ISSUE TITLE
Intermittent router 404's

### ISSUE THREAD

**Issue by sstarcher** [deis/deis#4778]
Setup: AWS, Stateless, Deis 1.12.1, ELB SSL Termination, EnforceHTTPS, EnforceWhitelist

We have health checks on all of our Deis apps that hit the ELB->Router->App for health checking.
We have noticed for a while intermittent 404's coming back through these health checks.  For a while I assumed the apps themselves were randomly having issues.  The last day we have started seeing these failures more often.  I set a health check to directly test against the container running the app and the last few occurences of the router health check have intermittently failed, but health check going directly against the container and by passing the router is working find.

I just separately tested each router and 1 of the 3 routers is intermittently failing with 404s.
I take that back a second router started getting 404's 50% of the time.

**Comment by sstarcher** [comment]
I previously had 3 routers running.  I restarted each router individually that did not seem to fix the problem.  I scaled the routers up to 5.  The below screen shot is a simple curl hitting each router directly.

$1 = ip of the router
```curl -s -I -H 'Host: hound.cluster.private' -H 'X-Forwarded-Proto: https' $1 | head -n 1```

<img width="2310" alt="screen shot 2015-12-04 at 1 07 02 pm" src="https://cloud.githubusercontent.com/assets/3778974/11597184/0b748c44-9a88-11e5-8a13-078b8523a371.png">

**Comment by jgmize** [comment]
@sstarcher do you have the HEALTHCHECK_URL set on your apps? We ran into a cascading failure problem where a failing deis health check due to high load caused one container to be removed from the router, increasing the load on the other containers and subsequently they failed deis health checks, until no container was being published to the router and we got 404s for the entire app as a result. We had to disable the HEALTHCHECK_URL setting to eliminate the possibility of that happening again.

**Comment by sstarcher** [comment]
All of my apps do have health checks.  There's actually only 1 container for this specific app that I'm testing.  The load to it is almost non-existent.

**Comment by sstarcher** [comment]
@jgmize off of your input I scaled up the app and I'm not currently seeing a health check failure.  The odd part is I never saw a health check failure hitting the app via curl directly.  I'm not sure why the nginx health check would of taken it out of rotation.

**Comment by sstarcher** [comment]
After more research it seems all occurrences of this are my fault.

**Comment by carmstrong** [comment]
> it seems all occurrences of this are my fault.

Glad you got it sorted! Can you share the problem for others who stumble across this issue?

**Comment by sstarcher** [comment]
I would not 100% say I have sorted it out ;)

* Older versions of Deis I did have a router problem where the router would write an invalid config and stop writing the config.  Deis 1.10 and prior I believe.  
* A recent issue was I had an app of scale 1 that would sometimes throw an error which would cause the health check to take it out of rotation and taking the app down since nothing was health.  This was resolved by scaling it up to 2+
* Another recent issue was an haproxy node running inside of Deis that 1 of it's 3 backend routes was invalid causing it to intermittently fail.

To track down these problems I would repeatedly curl each Deis router along with the IP:PORT directly of the docker container I was trying to route to.  This allows you to test if the app itself has a problem or if the routing is causing the issue.

To force curl to send the correct host data spoofed you can use.
``` curl -H 'Host: myapp.private' IP_OF_ROUTER```

**Comment by manuwell** [comment]
By debugging this behavior on our cluster we realized that `etcd` for some reason doesn't have the app key. And when `confd` fetches keys from `etcd` and the app key don't come it won't write the server indise `nginx.conf`.

Tracking down the source code of router I found [these lines listening docker](https://github.com/deis/deis/blob/e5f349dd9fb090aa993ad74758b3bbf038d44d23/publisher/server/publisher.go#L65) events and when docker emits a `stop event` it removes the `app key` from `etcd`.

I observed this behavior by running the cluster version of `confd` connected to the cluster and logging the `nginx.conf` with the same keys of `router`. 

Just don't know for sure what triggers the key removal but this might be the root cause.
