### ISSUE TITLE
Application upgrade - healthcheck fails, but still downtime.

### ISSUE THREAD

**Issue by dmcnaught** [deis/deis#4786]
Is there detailed documentation on the deis application upgrade process?

I just did an application upgrade (application scaled to 5), and I was hoping that the new version would be created and healthchecked before updating the routers. I set the healthcheck to fail, but my application still became unavailable (404 errors) before deis rolled back to the old version. 

Reference @krancour comment in https://github.com/deis/deis/issues/4237 on August 10th.

**Comment by dmcnaught** [comment]
@bacongobbler Could you outline the process here?

**Comment by bacongobbler** [comment]
The deployment process is relatively simple, from a scheduler's point of view: https://github.com/deis/deis/blob/master/controller/api/models.py#L465-L472

If the scheduler implements a "deploy" function, then we use that. For example kubernetes has a way to do a [rolling deploy](https://github.com/deis/deis/blob/master/controller/scheduler/k8s.py#L171-L176). Otherwise, we do it in two steps: start the new containers, then destroy the old ones. If a health check URL is set, then we ensure we perform a [health check](https://github.com/deis/deis/blob/master/controller/api/models.py#L374) before considering that it's been deployed.

**Comment by bacongobbler** [comment]
> I set the healthcheck to fail, but my application still became unavailable (404 errors) before deis rolled back to the old version.

That's *sort of* intentional, but it's also a bug. Publisher will only expose the latest version of an app. Since the new version was released, the old containers were removed from the routing table. It was to work around  an older issue: https://github.com/deis/deis/issues/1149. Unfortunately we cannot remove that feature, but it's likely something we can remove in v2.

Note that v2's health checking will be baked right into the kubernetes manifest itself, so this behaviour will change and will likely be fixed by then.

**Comment by dmcnaught** [comment]
@bacongobbler thanks for addressing that - I was wondering.
Do we have a rough estimate of when v2 is expected? I haven't seen it anywhere.

**Comment by bacongobbler** [comment]
it's on the roadmap :) http://docs.deis.io/en/latest/roadmap/roadmap/#deis-v2

We should be shipping an alpha release by the end of the year.

**Comment by dmcnaught** [comment]
Yup - saw the roadmap, but wasn't sure of the project velocity. Thanks for the estimate.

**Comment by bacongobbler** [comment]
closed via https://github.com/deis/workflow/pull/242.
