### ISSUE TITLE
Add hooks in build step

### ISSUE THREAD

**Issue by alexw23** [deis/deis#4822]
I'm trying to inject authentication into [composer](https://getcomposer.org) and as such you cannot inject environment variables into a docker build. Would it be possible to check for the existence of a `.prebuild.sh` [here](https://github.com/deis/deis/blob/25653e39a1ac8d76eee28563e2601c9750c3e8a7/builder/rootfs/etc/confd/templates/builder#L128) and `.postbuild.sh` [here](https://github.com/deis/deis/blob/25653e39a1ac8d76eee28563e2601c9750c3e8a7/builder/rootfs/etc/confd/templates/builder#L135) and run those if they exist?

**Comment by bacongobbler** [comment]
@alexw23 any environment variables you set with `deis config:set` should be injected into the build environment. Would that work for you?

Something like a pre_hook and a post_hook would be a good idea.

**Comment by alexw23** [comment]
It doesn't work for docker build. Docker created a --build-args for this purpose. But that seems messy.

The pre /post hooks would work well and could double as a slack notification. I feel a deis.yml coming on. You could even take some logic from drone. This might be cleaner then an sh file.

**Comment by krancour** [comment]
I think any change of such magnitude would be more appropriately applied to v2 at this juncture.

**Comment by bacongobbler** [comment]
> It doesn't work for docker build

If it's a basic deploy, we are using `docker run` and [injecting environment variables in](https://github.com/deis/deis/blob/25653e39a1ac8d76eee28563e2601c9750c3e8a7/builder/rootfs/etc/confd/templates/builder#L94-L96). Otherwise then yes, if you're using a Dockerfile that won't be able to work for you.

I agree with @krancour that this should be applied to v2 rather than v1. We'll probably have to figure out how we're going to migrate from one to the other at some point, as right now we have two separate bug trackers, deis/deis (v1) and deis/workflow (v2), but that's for another discussion. :)

**Comment by krancour** [comment]
Closing and moving discussion to deis/workflow#239
