### ISSUE TITLE
switch to Glide

### ISSUE THREAD

**Issue by bacongobbler** [deis/deis#4874]
As v2 moves onto [Glide](https://github.com/Masterminds/glide) for dependency management, we should do the same for v1 as well.

Related to https://github.com/deis/deis/pull/4864#issuecomment-175139827

**Comment by arschles** [comment]
unfortunately, this wouldn't fix the issue described in https://github.com/deis/deis/pull/4864#issuecomment-175139827, because bootstrappers and CI systems would still need to download the code. For dependencies we directly control, it would be best to go to the google code page and export the project to Github - they provide a button on their UI to do so

**Comment by krancour** [comment]
imo, we should leave this alone.  It's not critical to ensuring stability.

**Comment by bacongobbler** [comment]
Yep, I'm all for removing this for LTS if it's not critical. I'm working right now on fixing up Godeps but this was something I was chewing on while working on the former. Closing!
