### ISSUE TITLE
Are repositories meant to be frequently lost?

### ISSUE THREAD

**Issue by iangcarroll** [deis/deis#4919]
Whenever Ceph loses an OSD, Deis loses the Git repository for all of our applications. Is this expected behavior?

**Comment by nathansamson** [comment]
Repositories are lost whenever the builder restarts as they are actually not stored in Ceph.

I would not expect ceph have anything todo with a builder restart by definition (I could be wrong though), but losing  an OSD obviously means instability on at least one node, so it could be the same root cause that the builder restarts together with an OSD.

See also #3355

**Comment by iangcarroll** [comment]
Ah, that sounds like the cause then. Thanks. (Closing as it's a dup)
