### ISSUE TITLE
nginx 502 on apps that take too long to return HTTP responses

### ISSUE THREAD

**Issue by naphatkrit** [deis/deis#4953]
I noticed that Deis apps that take too long on a HTTP endpoint could end up getting cut off by nginx, and so 502 Bad Gateway would be returned. 30 seconds seem to be the threshold. Can we have a way to customize this? I'm thinking the culprit is on https://github.com/deis/deis/blob/master/router/rootfs/etc/confd/templates/nginx.conf#L321 and https://github.com/deis/deis/blob/master/router/rootfs/etc/confd/templates/nginx.conf#L248

**Comment by krancour** [comment]
I'd be more willing to tackle this in v2 than here.  (See deis/workflow and deis/router for v2.)  While the changes on the router end are easy and straighforward, exposing the ability to set this requires one of two approaches:

1. Add new capability to controller (API) _and_ CLI-- too much dev work, considering we're not really undertaking new feature development in v1.x.

2. Expanded abuse (I think) of an anti-pattern (IMO) whereby we obviate the need for changes to the API and CLI by allowing this to be set via an environment variable using `deis config:set`.  This trick takes advantage of the fact that the controller copies all application environment variables into etcd.  Although there is already some precedent for this (healthchecks and whitelists are handled this way) I feel strongly that this is wrong because environment variables should affect _application_ behavior; not _platform_ behavior.  Changes to platform behavior would be more properly configured through means such as no. 1.

All this being said, I'd want to hear @helgi's opinion on whether this belongs in LTS, preferred approach, and thoughts on doing this in v2.

**Comment by naphatkrit** [comment]
What about just having an option to take the value from etcd? It'll be similar to how defaultTimeout is customizable (https://github.com/deis/deis/blob/master/router/rootfs/etc/confd/templates/nginx.conf#L24). Would that be a simple change?

**Comment by naphatkrit** [comment]
UPDATE: this turns out to be a misdiagnosis. The timeout is caused by gunicorn in my Procfile.
