### ISSUE TITLE
router-nginx-status currently is public accessible if enabled

### ISSUE THREAD

**Issue by zhaohanweng** [deis/deis#4965]
Currently the router-nginx-status can be accessed publicly. According to [4368](https://github.com/deis/deis/issues/4368), now we have to flag to enable or disable it.

My question is if enabled, how can I access it only locally?
Can we move the
    
    server {
        listen 80 default_server reuseport proxy_protocol;
        ...
        location /router-nginx-status {
            vhost_traffic_status_display;
            vhost_traffic_status_display_format html;
        }
    }

to
    
    server {
        listen 9090 default_server;
        location /router-nginx-status {
            vhost_traffic_status_display;
            vhost_traffic_status_display_format html;
        }
    }

since 9090 is only accessible internally by ELB.
Or create a flag to enable publicly or only internally.

**Comment by krancour** [comment]
@zhaohanweng-- not a bad idea.  Moving it to the "default_server" vhost that's listening on 9090 would be good because that vhost never uses PROXY protocol-- which would be important if you were looking to hit that endpoint from _within_ the cluster.

If a user opts into exposing the endpoint outside the cluster, then I believe this location block should appear on the "default_server" for _both_ ports 80 and 9090.

Further, there's never any guarantee that port 9090 isn't exposed to the outside world.  It _can_ be, depending on what modifications a user might make to their load balancer.  As such, it _might_ be good to actually lock that location block down to access only by `127.0.0.1` using the `allow` directive-- at least in the case where a user has not opted into exposing it.  (Tangent: we've done something similar in v2.  We never expose it to the outside world, but we make it available only from _within_ the same pod since we run an agent that hits that endpoint to collect these metrics.)

I like this idea, but I think it gets triaged pretty low since we are in full swing on v2 development right now.  I'm going to mark this issue as "help wanted," so if you might like to take a crack at this, please feel free.

**Comment by bacongobbler** [comment]
removed in v2.

**Comment by krancour** [comment]
@bacongobbler this was initially removed from v2, but at one point, it appeared it was needed to help in metrics collection, so it was  added back in and exposed _only_ internally. The `/stats` endpoint allows only requests originating from `127.0.0.1`.
