### ISSUE TITLE
Healthcheck config changes aren't removed from etcd

### ISSUE THREAD

**Issue by szymonpk** [deis/deis#5017]
I've strange issue with my deisv1, we've had healthchecks turned on once in the past, but it was failing with more than 3-4 containers, so we've turned it off, and removed all healthcheck related config values. However from time to time, application is failing to start because healthcheck error, there is no healthcheck-related configuration when running `deis config -a <app name>`, but after looking directly into etcd I've noticed this:

```
$ etcdctl ls deis/config/app | grep health
/deis/config/app/healthcheck_url
/deis/config/app/healthcheck_initial_delay
/deis/config/app/healthcheck_timeout
```

I remember we've removed it manualy from etcd in the past (etcdctl rm...), but now it's back. I've thought it might be related to recent controller restart (IIRC all etcd config values are propagated on restart) I've also looked into Deis postgresql database, and config attached to this particular app doesn't have any healthcheck related settings.

Any advice on this would be greatly appreciated, because it breaks our production environement from time to time.

**Comment by jgmize** [comment]
I recall observing this same behavior as well a while bakc, and had to perform similar steps to manually remove the keys from etcd because the HEALTHCHECK_URL was not showing up in the `deis config` output, but was there in etcd. One additional datapoint is that we had performed a migration upgrade since the last time we removed the healthchecks, so the etcd keys had to have been populated from the db at some point, since the etcd cluster was replaced during the migration upgrade.

**Comment by jgmize** [comment]
I believe I found the issue: in https://github.com/deis/deis/blob/master/controller/api/management/commands/load_db_state_to_etcd.py#L13-L15 I see that the command loads *ALL CONFIGS* into etcd, not just the latest config on a per app basis. In addition to generating a large amount of unnecessary calls to etcd, this will also cause the invalid behavior observed here for *any* config value that is ever set and then later removed from the config.
