### ISSUE TITLE
Deploying test example not working

### ISSUE THREAD

**Issue by aldarund** [deis/deis#5062]
Im trying to deploy test app according to docs https://deis.com/docs/workflow/quickstart/deploy-an-app/
But it fails for me for unknown reason.
```
[dm@localhost kubeform]$ deis pull deis/example-go -a proper-barbecue
Creating build... Error: Not Found
```
```
deis --version
2.1.0-59d8690
```
I guess something wrong with my setup, but the error gives zero hints about wrong and how to fix it.

**Comment by aldarund** [comment]
Nvm, figured out. my bad

**Comment by bacongobbler** [comment]
can you try a `deis apps` and see if `proper-barbecue` exists? From what I've seen this usually indicates the app has not been created.

**Comment by aldarund** [comment]
@bacongobbler yes, didnt realized that it was a name generated by prev command. But now im getting another issue..

Creating build... Error: Unknown Error (400): map[detail:Get https://10.3.0.107:80/v1/_ping: tls: oversized record received with length 20527]

**Comment by bacongobbler** [comment]
is your controller backed by SSL, and if so, how did you set it up? Is this witha  self-signed certificate?

**Comment by rochacon** [comment]
@aldarund I had a similar error because my Docker daemons wasn't configured to accept insecure registries in the k8s-service network range. Deis registry is not backed by SSL, so the HTTPS ping request won't work.

All your k8s nodes must be configured with the `--insecure-registry=<k8s-service-ip-range>`.

**Comment by bacongobbler** [comment]
ah yes that would be the issue. ^ the controller is reporting that it cannot connect to the registry because it is not set up to use `--insecure-registry` as per https://deis.com/docs/workflow/installing-workflow/system-requirements/#docker-insecure-registry. The quickstart documentation should explain that as well. What provider are you using?

**Comment by mboersma** [comment]
This bug has languished and sounds like it's solved, so I'm closing it. Please re-open if there's an issue we can fix here.
