### ISSUE TITLE
Using separate registry

### ISSUE THREAD

**Issue by dekhtyarev** [deis/deis#5066]
Hi to all!

I have more then 200 docker containers, which live on 5 coreos nodes.
When I stopped 1 CoreOS node - about 40 containers start migrating to another nodes.
At last times(after update to CoreOS 1010.6.0) Deis registry is dies, when 20-30+ apps want download images from it.

I would like to use your own Registry v2, which seems faster and stable.
What pitfalls can I expect if I point HA Registry v2 in etcd2? Was there a similar experience?

PS Basic I checked to work with Registry v2 - it works. But will have a little patch controller to the images loaded in the correct namespaces.

PPS DEIS 1.13.0 and CoreOS 1010.6.0 on node with registry
PPS DEIS 1.13.0 and CoreOS 899.17.0 on node with apps
PPS We are in the process of updating to the DEIS 1.13.2 and CoreOS latest stable version.

**Comment by Joshua-Anderson** [comment]
The major pitfall I can think of if you point to a separate registry is lack of authentication. Since the docker registry doesn't support authentication, deis runs it inside the cluster behind a firewall. An external registry would have to be behind a vpc or something similar so it was inaccessible to the internet but still accessible to the cluster.

For deis v2, work to support external registries and authentication, including registries like ecr and gcr is in progress and should be arriving in an upcoming release.

**Comment by bacongobbler** [comment]
Also an FYI that our registry is no different than Docker's registry. In fact it's just a fork of docker/distribution, which we are planning on changing it back to the official distribution image since our storage backends have been merged upstream.

**Comment by Joshua-Anderson** [comment]
[Deis Workflow v2.3.0 was released](https://deis.com/blog/2016/deis-workflow-2-3/) with support for external registries. Deis V1 is maintenance only now, so the feature will not be backported. If you have any more questions about the deis V1 registry, feel free to ask in the deis #community slack channel!
