### ISSUE TITLE
docs(*): convert documentation to markdown

### ISSUE THREAD

**Issue by mboersma** [deis/deis#976]
Deis' documentation consists of a [Sphinx](http://sphinx-doc.org/)/[reStructuredText](http://docutils.sourceforge.net/rst.html) project under the `docs/` directory, and several `README.md` files in other locations. Having two markup languages in use complicates authoring and discourages contributors, and we prefer [Markdown](http://daringfireball.net/projects/markdown/).

Docker recently converted to using [MkDocs](http://www.mkdocs.org/) instead of Sphinx. Our docs host http://readthedocs.org builds and hosts MkDocs now in addition to Sphinx-based projects. The only obvious thing that would be hard to replace is the auto-generated Python documentation in the controller, such as http://docs.deis.io/en/latest/server/api.models/. And perhaps there are other solutions. We've been very happy with Jekyll for http://deis.io, although some work would be required to backfill features we get from readthedocs.org (versioning, CI system for docs).

This is probably a non-trivial effort, and isn't a priority on our roadmap to a stable Deis release. But if someone wants to have a go at it, we would love to see a pull request!

**Comment by bacongobbler** [comment]
I've had a change of heart recently after playing around with different documentation tools. An amazing alternative to MkDocs is `asciidoc`. AsciiDoc has been around since 2002 and is packed full of features which would enable us to generate documentation as manpages, HTML, PDF, eBook, etc. This is the tool which `git` and other well-known projects have been using. The documentation is all written in plain text, which is a format known worldwide as opposed to ReST or Markdown. It also has includes, too!

Only problem is that we probably cannot rely on rtd.org to host our documentation any more, so we;d have to find an alternative (S3, perhaps?). See rtfd/readthedocs.org#17.

http://www.methods.co.nz/asciidoc/

**Comment by mboersma** [comment]
I'm going to close this--it's been open for almost a year and Deis isn't any closer to refactoring the docs to use a Markdown-based system, which was the original motivation so there could be only one markup language in use between the README.md files and the external docs. (Generally if there isn't a fighting chance an enhancement will be implemented in the near future, it's preferable to close it IMHO.)

ReStructuredText: learn it, love it. :book:
