### ISSUE TITLE
Container network segregation / firewalling

### ISSUE THREAD

**Issue by carmstrong** [deis/deis#986]
Application containers don't need access to etcd, for example.

**Comment by blaggacao** [comment]
Out of curiousity, has been thought to swap etcd for consul as the K/V backend? It comes with (acl)[https://consul.io/docs/internals/acl.html]. Might be sensible to continue using etcd for the control layer until the guys at CoreOS catch up and introduce consul for the application part.

@carmstrong wouldn't environment variables not making troubles when morphing and dynamic in the context of the application runtime? - not sure what that would be good for, but I would best guess for some low level multitenancy, which is managed by the application itself. Let's say a dynamic database creaction with automated credentials creation and propagation. There we are still on the hosting level.

**Comment by gabrtv** [comment]
> Out of curiousity, has been thought to swap etcd for consul as the K/V backend? 

Yes, we have actively explored Consul as it can potentially add a lot of value around health monitoring and service discovery.  Unfortunately, it's also a lot of duplicated infrastructure (another raft cluster) and a significant engineering effort.  As a result, it's not a high priority at this moment.

In the interest of providing better network segregation and security, how do folks feel about:

1. Separate k/v stores (and raft clusters) for platform-level and application-level concerns?
2. Enforcing an overlay network to isolate application traffic from platform traffic?

**Comment by blaggacao** [comment]
:+1: 
3. as a "soft" design-rule / documentation: make the better part of the application file system(s) read-only? Not sure though if this is really an effective measure, however it seems to me that in 12-factor apps this becomes an option. Or did I conceptually miss something?

**Comment by bacongobbler** [comment]
The filesystem as per Heroku's cedar stack [is ephemeral](https://devcenter.heroku.com/articles/dynos#ephemeral-filesystem), so that's been the design we've been following. Is there a specific reason that a read-only filesystem would be necessary?

Note: Heroku used to have [a read-only filesystem](https://devcenter.heroku.com/articles/read-only-filesystem) in their bamboo stack which you could only write to ./tmp and ./logs, but they deprecated that in favour of documenting their dynos as ephemeral. Same goes for any other PaaS out there (Stackato, Cloud Foundry, Flynn, Dokku, etc.)

**Comment by blaggacao** [comment]
Beware, it's not an indepth opinion of mine and maybe in the wrong tradeoff scope. 

The intention behind was to close down the runtime app rather completely to injection of malicios tools as it's probably the app itself which is the vulnerable point. I think this should never be enforced in any way, I just thought of building my containers this way and deploying as container images directly.

I'm just guessing loud, don't know much about actual attack patterns. However not being able to write to a filesystem *sounds* secure. Extra compromising tools would have to be loaded and executed directly to ram... persistent store can be monitored for/closed down against improper write access specially. It just would make any attack pattern involving fs writes more dificult.

Maybe this could be an interesting pattern for the control plane as well.

**Comment by apps4u** [comment]
Im not a expert in Deis or CoreOS so this might be a bad idea , but would there be a way to create VLANS then have deis containers on a vlan that can acccess the required service but have all other containers on a different VLAN that is locked from access things like ETCD , This seems like a easy solution so Im guessing this wont work or some one would of thought of it but I thought I might as well ask.

**Comment by wenzowski** [comment]
Seems to me that #3072 must be considered when undertaking this if it is to be implemented in iptables like geard does. In terms of etcd access, what about binding keys to environment varibles on the container and sighup'ing it whenever the environment variables change?

**Comment by azurewraith** [comment]
> In the interest of providing better network segregation and security, how do folks feel about:
> * Separate k/v stores (and raft clusters) for platform-level and application-level concerns?
> * Enforcing an overlay network to isolate application traffic from platform traffic?

Seems reasonable to me.  What is the game plan for driving this home?

**Comment by carmstrong** [comment]
> Seems reasonable to me. What is the game plan for driving this home?

For a change like this, we'd like the larger Deis community's input. Next step would be to open a proposal PR (see #2911 for a good example) adding documentation around the segregation, as if it had already been implemented. Once we agree on that, implementation can commence with a high degree of confidence that it will be merged without significant changes.

**Comment by Brandl** [comment]
Dear Deis Developers,

I came across your software today and read through you documentation. It comes really promising and close to what I am looking for. I was really scared, when I came across the security section:
> "Deis is not suitable for multi-tenant environments or hosting untrusted code."

If this is actually the case, I would call this a security critical bug, because if there actually is a scenario, where getting a web app hacked imposes a thread to all other containers and the actual host, that would be terrifying.  

Maybe I'm just misinterpreting this issue, so what is the actual impact of this?

**Comment by apps4u** [comment]
just don’t run this if you are left users who you don’t trust like random online user. its not designed to work like that. Its safe when say a company runs all its containers on the platform 
Jason Kristian | Director | Apps 4 U Pty Ltd.
ph: +61 075699 8109
mob: +61 0411 389 392
e: Jason Kristian <mailto:jasonk@apps4u.com.au>

**Comment by azurewraith** [comment]
@Brandi has a point, even if you trust all your users a security breach (after all we are on the cloud) can jeopardize the security of the other containers / deis core.

**Comment by gabrtv** [comment]
@Brandl you are correct that a compromised container can pose a threat to other containers and anything accessible over the network (including the underlying host).

Ideally containers would run on an isolated-by-default network segment with explicit access grants to endpoints as permitted (e.g. other containers, control plane infrastructure and external/third-party services).  Unfortunately, achieving this level of network security is non-trivial and we want to be open about that, hence the disclosure in our documentation.

I do want to be clear that there a big difference between running untrusted code _by design_ and running it _by accident_ via application compromise.  While the net result is the same (untrusted code running inside the cluster), the latter scenario is no different in Deis than what you'll find on comparable container platforms or orchestration systems like Mesos, Kubernetes, etc.

We do intend to support multi-tenant environments eventually.  We are exploring technologies along the lines of [ambassadord](https://github.com/progrium/ambassadord) and Apcera's [semantic pipelines](http://docs.apcera.com/tutorials/pipelines/) (not open source) to help us get there.  We also need help from upstream projects like Docker and etcd.  However, until we undergo an audit by a 3rd-party security vendor, it's unlikely we will remove the disclaimer re: true multi-tenancy.

**Comment by apps4u** [comment]
That is correct but they are two different things having your application hacked is different to running code that is designed to be unsafe. So running code in a container that is designed to bring down your cluster could happen if you run untrusted code but if your application was hacked then some one got access to the under laying system is not a Deis issue it would also be a issue if you ran Core OS cluster or a Docker Cluster .  
So yes the platform is secure as any other like system but if you let some run a container that was designed to cause you issue then that could be a problem . Till Deis is truly safe to run in a multi tenant enviroment you should make sure yo run trusted code then you will be safe just unless you leave a whole in your application but that risk is there whether you run Deis or Not.




Jason Kristian | Director | Apps 4 U Pty Ltd.
ph: +61 075699 8109
mob: +61 0411 389 392
e: Jason Kristian <mailto:jasonk@apps4u.com.au>

**Comment by bacongobbler** [comment]
related: #3812

**Comment by nlsrchtr** [comment]
Maybe the [Authentication and Authorization features](https://coreos.com/blog/introducing-etcd-2.1/) introduces into etcd *2.1* could help solve part of the problem. Combined with a network layer based security, like drafted in #3812, would make it even better.

**Comment by jokeyrhyme** [comment]
Regarding @nlsrchtr 's point, it does seem as though key prefixes can now be used to restrict access in etcd: https://github.com/coreos/etcd/issues/2384
From my naive glance at the Godeps, it seems etcd 2.0 is being used. Is there work underway to upgrade to etcd 2.1 or newer?

**Comment by bacongobbler** [comment]
bumping this thread now with v2-related discussion. To bring us all up to speed:

 - Deis (now called Workflow) uses Kubernetes instead of Fleet
 - kubernetes has service discovery built into the system, so etcd has been "removed" from the control plane (kubernetes still uses etcd for skydns, it's built-in service discovery mechanism)

The last thing to resolve would be true network segregation based on which namespace the application is deployed. The application should be able to communicate with any other apps deployed in the same namespace to facilitate #4173, but not with the kubernetes API server, the Workflow API server, or any other application outside of its own namespace (internally, at least). Applications should still be able to go surf the public web, as well as target applications through the router. For example, application `foo` can talk to application `bar` via http://bar.example.com (through the router), but not through the pod's IP address (10.247.144.126) unless `bar` happened to be deployed in the same namespace as `foo`.

**Comment by deis-admin** [comment]
This issue was moved to deis/controller#1216
